import type { Passage } from "@/data-access/types";

// Mục 5.11: ≥25 văn bản đọc hiểu, mỗi văn bản dùng chung cho 5–7 câu hỏi
// (xem exercises/dh-passage-*.ts, mỗi câu hỏi gắn passageId về đây). Tất cả
// văn bản tự biên soạn (Mục 10.1 hướng B) — tránh mọi rủi ro bản quyền,
// không trích nguyên văn tác phẩm nào.
export const ALL_PASSAGES: Passage[] = [
  {
    id: "dh-passage-01",
    title: "Chiếc ô của bà Tư",
    text: 'Buổi chiều mùa hạ, trời bỗng đổ mưa tầm tã. Minh đang trên đường đi học về thì nhìn thấy bà Tư, người hàng xóm già yếu, đứng nép dưới mái hiên một cửa hàng, tay run run vì lạnh. Bà không mang theo ô, còn quãng đường về nhà bà lại khá xa.\n\nKhông chút do dự, Minh chạy đến bên bà, xoè chiếc ô nhỏ của mình ra và nói: "Bà ơi, cháu đưa bà về nhà nhé!" Bà Tư mỉm cười cảm động, nắm lấy tay Minh. Trên đường đi, tuy chiếc ô chỉ đủ che cho một người, Minh vẫn cố gắng nghiêng về phía bà để bà không bị ướt, còn một bên vai áo của cậu thì ướt sũng.\n\nVề đến nhà, bà Tư xoa đầu Minh, rối rít cảm ơn. Bà còn lấy trong túi ra một gói kẹo lạc thơm phức tặng cậu. Minh cười tươi, tuy người ướt nhưng trong lòng cảm thấy ấm áp lạ thường. Trên đường trở về nhà mình, cậu thầm nghĩ: giúp đỡ người khác dù chỉ là một việc nhỏ cũng khiến bản thân cảm thấy hạnh phúc hơn rất nhiều.',
  },
  {
    id: "dh-passage-02",
    title: "Chiếc diều đứt dây",
    text: "Chủ nhật nào Nam cũng ra bãi cỏ đầu làng thả diều cùng đám bạn. Chiếc diều hình con bướm của Nam là món quà bố tặng trước khi đi làm xa, vì vậy cậu quý nó hơn bất cứ thứ gì. Hôm ấy, gió thổi mạnh bất thường, chiếc diều bay cao vút lên bầu trời, sợi dây trong tay Nam căng hết cỡ.\n\nBỗng \"phựt\" một tiếng, sợi dây đứt phăng. Chiếc diều con bướm chao đảo rồi bay mất hút về phía cánh rừng xa, bỏ lại Nam đứng chết lặng giữa bãi cỏ. Nam oà khóc, chạy theo một đoạn nhưng chiếc diều đã biến mất trong tầm mắt. Thấy vậy, các bạn xúm lại an ủi, còn bé Hoa nhường ngay chiếc diều hình con cá của mình cho Nam chơi chung.\n\nTối hôm đó, khi kể chuyện cho mẹ nghe, Nam vẫn còn buồn. Mẹ nhẹ nhàng nói: \"Con ạ, có những thứ dù quý đến đâu cũng có lúc phải rời xa ta, quan trọng là những kỷ niệm về nó vẫn còn mãi trong lòng con.\" Nghe mẹ nói, Nam thấy lòng nhẹ nhõm hơn hẳn. Cậu mỉm cười nhớ lại những buổi chiều được bố dạy cách thả diều, và tự nhủ mình sẽ luôn giữ gìn kỷ niệm ấy.",
  },
  {
    id: "dh-passage-03",
    title: "Chú chim sẻ non",
    text: "Sáng thứ Bảy, khi đang quét sân, Lan phát hiện một chú chim sẻ non nằm run rẩy dưới gốc cây bàng, có lẽ đã rơi khỏi tổ trong trận gió đêm qua. Đôi cánh chú còn chưa đủ lông để bay, đôi mắt nhỏ nhắm nghiền vì sợ hãi.\n\nLan vội gọi em trai là Tuấn ra xem. Hai chị em bàn nhau tìm cách giúp chú chim. Tuấn đề nghị mang chim vào nhà nuôi, nhưng Lan lắc đầu: \"Nếu để lâu xa mẹ, chim non có thể sẽ không sống được. Mình nên tìm cách đưa chim trở lại gần tổ thôi.\" Nói rồi, Lan nhẹ nhàng bắc chiếc thang nhỏ, đặt chú chim vào một chiếc hộp có lót lá khô rồi treo lên cành cây gần tổ cũ, hy vọng chim mẹ sẽ tìm thấy con.\n\nCả buổi sáng, hai chị em cứ thấp thỏm ngóng ra gốc bàng. Đến trưa, một chú chim sẻ trưởng thành bay tới, đậu cạnh chiếc hộp rồi tha mồi cho chim non ăn. Lan và Tuấn vui mừng ôm nhau nhảy cẫng lên. Nhìn cảnh chim mẹ chăm sóc con, Lan thấy lòng ấm áp vì đã giúp được một sinh linh bé nhỏ đoàn tụ với gia đình của nó.",
  },
  {
    id: "dh-passage-04",
    title: "Vì sao lá cây có màu xanh",
    text: "Nếu để ý, em sẽ thấy hầu hết lá cây xung quanh chúng ta đều có màu xanh lục. Đó là vì trong lá cây có chứa một chất đặc biệt gọi là diệp lục (hay còn gọi là chất diệp lục tố). Chất này có khả năng hấp thụ ánh sáng mặt trời để giúp cây thực hiện quá trình quang hợp — quá trình cây tự tạo ra chất dinh dưỡng nuôi sống bản thân.\n\nÁnh sáng mặt trời vốn gồm nhiều màu sắc khác nhau. Diệp lục hấp thụ hầu hết các màu như đỏ, cam, tím để phục vụ quang hợp, nhưng lại phản chiếu lại màu xanh lục. Chính vì vậy, khi mắt chúng ta nhìn vào lá cây, ta chỉ thấy được màu xanh lục phản chiếu ra, khiến ta cảm nhận lá có màu xanh.\n\nĐiều thú vị là đến mùa thu, khi trời trở lạnh, cây giảm dần việc tạo ra diệp lục mới. Lượng diệp lục trong lá giảm đi, các sắc tố khác vốn luôn có trong lá nhưng bị diệp lục che lấp (như sắc tố vàng, cam) mới có cơ hội lộ ra, khiến ta thấy lá chuyển sang màu vàng, cam rực rỡ trước khi rụng xuống.",
  },
  {
    id: "dh-passage-05",
    title: "Món quà đặc biệt",
    text: "Còn hai ngày nữa là đến sinh nhật mẹ, nhưng Hà chỉ có vỏn vẹn năm nghìn đồng tiền tiết kiệm, không đủ để mua món quà nào ở cửa hàng. Cô bé buồn bã ngồi trong phòng, nghĩ mãi mà không ra cách nào.\n\nChợt Hà nhớ đến những bông hoa giấy mà cô được bà ngoại dạy gấp hồi hè trước. Cô liền lục tìm những tờ giấy màu còn sót lại trong ngăn bàn học, cặm cụi gấp từng cánh hoa suốt hai buổi tối liền. Ngón tay cô vài lần bị giấy cứa nhẹ, nhưng Hà vẫn kiên nhẫn gấp cho đến khi hoàn thành một bó hoa giấy đủ màu sắc, xen giữa là một tấm thiệp nhỏ tự tay viết lời chúc.\n\nSáng sinh nhật, khi Hà rụt rè đưa bó hoa giấy cho mẹ, mẹ sững người rồi ôm chầm lấy cô, mắt rưng rưng xúc động. Mẹ nói đây là món quà đẹp nhất mẹ từng nhận được, quý hơn bất cứ món quà đắt tiền nào, vì nó chứa đựng cả tấm lòng và công sức của con gái. Hà cười thật tươi, cảm thấy hạnh phúc hơn cả khi tưởng tượng ra cảnh mẹ vui mừng lúc trước.",
  },
  {
    id: "dh-passage-06",
    title: "Người bạn mới",
    text: "Đầu năm học, lớp 5A đón một bạn mới tên là Khôi, chuyển đến từ một tỉnh miền núi xa xôi. Khôi có nước da ngăm đen, nói giọng hơi khác so với các bạn trong lớp nên ngày đầu tiên cậu cứ ngồi im lặng một góc, không dám bắt chuyện với ai.\n\nGiờ ra chơi, trong khi các bạn khác túa ra sân nô đùa, Khôi vẫn lặng lẽ ngồi lại trong lớp. Thấy vậy, Bình — lớp trưởng — tiến đến gần, mỉm cười hỏi: \"Cậu có muốn ra sân chơi đá cầu cùng bọn tớ không?\" Khôi ngập ngừng một lúc rồi khẽ gật đầu. Cả nhóm bạn vui vẻ kéo Khôi ra sân, chỉ cho cậu cách chơi, không ai chê cười khi Khôi đá trượt cầu liên tục những lần đầu.\n\nDần dần, Khôi trở nên cởi mở hơn, thường kể cho các bạn nghe về những ngọn núi, con suối ở quê mình khiến ai cũng thích thú lắng nghe. Cuối năm học đó, Khôi trở thành một trong những thành viên hoạt bát nhất của lớp 5A. Cậu thường nói với Bình rằng chính sự thân thiện của các bạn ngày đầu đã giúp cậu vượt qua nỗi nhớ nhà và tự tin hoà nhập với môi trường mới.",
  },
  {
    id: "dh-passage-07",
    title: "Cuộc thi vẽ tranh",
    text: "Trường tổ chức cuộc thi vẽ tranh với chủ đề \"Ngôi nhà mơ ước\", giải thưởng là một hộp màu vẽ cao cấp mà Tâm ao ước từ lâu. Suốt một tuần, Tâm miệt mài phác thảo, tô màu cho bức tranh ngôi nhà nhỏ bên sườn đồi, xung quanh là vườn hoa rực rỡ.\n\nTrước ngày nộp bài một hôm, khi đang mang tranh đến lớp, Tâm vô tình va phải bạn Đức khiến ly nước của Đức đổ ngay lên bức tranh, làm nhoè mất một góc quan trọng. Đức cuống quýt xin lỗi, còn Tâm chỉ biết đứng lặng người nhìn công sức cả tuần bị hỏng. Dù rất tiếc nhưng Tâm không trách móc bạn, chỉ nói: \"Không sao đâu, để tớ sửa lại.\"\n\nTối hôm đó, thay vì buồn bã, Tâm quyết định biến vết nhoè thành một đám mây trên bầu trời bức tranh, khiến tổng thể bức tranh trông còn sinh động hơn trước. Kết quả, bức tranh của Tâm không những không bị loại mà còn giành giải Nhất nhờ sự sáng tạo bất ngờ đó. Tâm nhận ra rằng đôi khi, một sự cố tưởng chừng tồi tệ lại có thể trở thành cơ hội để mình sáng tạo hơn nếu biết bình tĩnh đối mặt.",
  },
  {
    id: "dh-passage-08",
    title: "Loài voi và trí nhớ đáng kinh ngạc",
    text: "Voi là một trong những loài động vật thông minh nhất trên Trái Đất, đặc biệt nổi tiếng với trí nhớ đáng kinh ngạc. Bộ não của voi có kích thước lớn nhất trong các loài động vật sống trên cạn, nặng trung bình khoảng 5 ki-lô-gam, chứa hàng tỷ tế bào thần kinh giúp chúng ghi nhớ thông tin trong thời gian rất dài.\n\nCác nhà khoa học đã quan sát thấy voi có thể nhớ được đường di chuyển đến các nguồn nước hoặc bãi cỏ tốt mà chúng từng đi qua nhiều năm trước, thậm chí sau hàng chục năm. Đặc biệt, voi đầu đàn (thường là voi cái lớn tuổi nhất) đóng vai trò như một \"bản đồ sống\" của cả đàn, dẫn dắt những con voi khác đến nơi có thức ăn, nước uống an toàn, nhất là vào mùa khô hạn khi nguồn nước khan hiếm.\n\nKhông chỉ ghi nhớ địa điểm, voi còn có khả năng nhận ra và ghi nhớ hình dáng, mùi hương của những cá thể voi hay con người mà chúng từng gặp, dù đã cách xa nhiều năm. Nhờ trí nhớ tuyệt vời này, đàn voi có thể truyền lại kinh nghiệm sinh tồn quý báu từ thế hệ này sang thế hệ khác, giúp cả đàn thích nghi tốt hơn với môi trường sống luôn thay đổi.",
  },
  {
    id: "dh-passage-09",
    title: "Chiếc thuyền giấy",
    text: "Mỗi khi trời mưa to, Bống lại cùng anh trai là Tùng ngồi bên hiên nhà gấp những chiếc thuyền giấy nhỏ. Đó là trò chơi hai anh em yêu thích nhất từ khi còn bé, do ông nội dạy trước khi ông mất vì bệnh nặng hai năm trước.\n\nBống nhớ như in dáng ông ngồi tỉ mỉ gấp từng nếp giấy, giọng ông trầm ấm kể chuyện ngày xưa ông cũng hay thả thuyền giấy trên dòng kênh trước nhà. Giờ đây, mỗi lần gấp thuyền, Tùng luôn nhường em gái được thả thuyền xuống rãnh nước trước sân, còn mình thì đứng cạnh reo hò cổ vũ mỗi khi thuyền của Bống trôi xa mà không bị lật.\n\nCó lần, chiếc thuyền của Bống bị mắc vào một cành cây nhỏ giữa dòng nước, cô bé buồn thiu vì tưởng thuyền sẽ hỏng mất. Tùng liền xắn quần lội xuống, khéo léo gỡ chiếc thuyền ra mà không làm rách giấy. Nhìn chiếc thuyền tiếp tục trôi, Bống cười tươi rói, thầm cảm ơn anh trai đã luôn ở bên cạnh gìn giữ trò chơi kỷ niệm mà ông để lại. Với hai anh em, mỗi chiếc thuyền giấy trôi đi không chỉ là một trò chơi, mà còn mang theo cả tình yêu thương của ông nội.",
  },
  {
    id: "dh-passage-10",
    title: "Bài học từ chú kiến nhỏ",
    text: "Một buổi chiều, khi đang ngồi nghỉ dưới gốc cây trong vườn, Bảo tình cờ nhìn thấy một chú kiến đang cố gắng tha một hạt đậu to gấp nhiều lần cơ thể mình. Chú kiến ì ạch kéo hạt đậu qua từng viên sỏi nhỏ, có lúc bị hạt đậu đè lật ngửa nhưng vẫn lồm cồm bò dậy, tiếp tục công việc.\n\nBảo tò mò quan sát, thấy chú kiến thử đến ba, bốn lần đều thất bại khi gặp phải một rãnh nứt trên nền đất. Cậu định nhặt lấy hạt đậu đặt sang bên kia rãnh giúp kiến, nhưng rồi lại tò mò muốn xem chú kiến sẽ xoay xở ra sao. Không lâu sau, chú kiến tìm được một chiếc lá khô nhỏ gần đó, cố gắng đẩy hạt đậu lên trên chiếc lá rồi dùng nó như một chiếc cầu để vượt qua rãnh nứt.\n\nChứng kiến cảnh tượng ấy, Bảo vô cùng thán phục. Cậu nhớ lại bài toán khó mà mình đã bỏ dở từ tối qua chỉ vì thử một cách mà chưa ra kết quả. So với chú kiến nhỏ bé kiên trì tìm đủ mọi cách để vượt khó khăn, cậu cảm thấy hơi xấu hổ vì sự bỏ cuộc quá sớm của mình. Tối đó, Bảo quyết tâm ngồi vào bàn học, thử lại bài toán bằng một cách giải khác, và cuối cùng cậu đã tìm ra đáp án đúng.",
  },
  {
    id: "dh-passage-11",
    title: "Chiếc áo len cũ",
    text: "Trời trở lạnh, các bạn trong lớp đều mặc những chiếc áo len mới, nhiều màu sắc rực rỡ. Riêng Vy vẫn mặc chiếc áo len cũ đã sờn vai, màu xanh nhạt bạc màu vì mặc qua từ năm ngoái. Thấy vậy, một vài bạn trong lớp xì xào bàn tán, khiến Vy cảm thấy hơi ngại ngùng, cứ khoanh tay che phần vai áo bị sờn.\n\nGiờ ra chơi, bạn Chi ngồi cạnh Vy khẽ hỏi: \"Áo của cậu có phải mẹ đan cho không? Tớ thấy đường len rất đẹp và ấm.\" Vy ngạc nhiên gật đầu, kể rằng mẹ đã tự tay đan chiếc áo này tặng Vy vào mùa đông năm ngoái, khi ấy nhà Vy chưa có điều kiện mua áo mới. Chi cười tươi nói: \"Áo mẹ tự đan chứa cả tình yêu thương, đẹp hơn nhiều áo mua ở cửa hàng đấy chứ!\"\n\nNghe Chi nói vậy, Vy bỗng thấy tự tin hẳn lên, không còn khoanh tay che vai áo nữa. Từ hôm đó, mỗi khi mặc chiếc áo len cũ, Vy đều nhớ đến đôi bàn tay mẹ tỉ mỉ đan từng mũi len trong những đêm đông, và cô cảm thấy tự hào về chiếc áo ấy hơn bao giờ hết, không còn quan tâm đến những lời bàn tán xung quanh nữa.",
  },
  {
    id: "dh-passage-12",
    title: "Buổi biểu diễn văn nghệ",
    text: "Trường tổ chức đêm văn nghệ chào mừng năm học mới, và An được cô giáo chọn biểu diễn một tiết mục hát đơn ca. Dù rất thích hát, An lại vô cùng sợ đứng trước đám đông. Càng gần đến ngày biểu diễn, An càng lo lắng, có hôm còn mất ngủ vì nghĩ đến cảnh đứng trên sân khấu.\n\nTối trước buổi diễn, An định xin cô giáo đổi tiết mục khác không phải lên sân khấu một mình. Thấy con gái lo lắng, mẹ nhẹ nhàng ngồi xuống bên An, kể rằng hồi nhỏ mẹ cũng từng run rẩy khi lần đầu phát biểu trước lớp, nhưng nhờ tập luyện nhiều lần và tự nhủ chỉ cần cố gắng hết sức, mẹ đã vượt qua được nỗi sợ đó. Mẹ khuyên An cứ tập trung hát cho thật hay, đừng để ý đến ánh mắt xung quanh.\n\nĐêm biểu diễn, khi bước ra sân khấu, tim An đập rất nhanh, nhưng nhớ lời mẹ dặn, An nhắm mắt hít một hơi thật sâu rồi bắt đầu cất tiếng hát. Càng hát, An càng quên đi nỗi sợ, chỉ còn tập trung vào giai điệu bài hát. Kết thúc tiết mục, cả khán phòng vỗ tay rộn rã. An mỉm cười rạng rỡ, cảm thấy tự hào vì đã dũng cảm vượt qua chính nỗi sợ hãi của bản thân.",
  },
  {
    id: "dh-passage-13",
    title: "Vì sao chúng ta cần ngủ đủ giấc",
    text: "Giấc ngủ đóng vai trò vô cùng quan trọng đối với sức khoẻ và sự phát triển của con người, đặc biệt là trẻ em đang trong độ tuổi lớn. Các bác sĩ khuyến nghị học sinh tiểu học và trung học cơ sở nên ngủ đủ từ chín đến mười một tiếng mỗi đêm để cơ thể có đủ thời gian nghỉ ngơi và phục hồi.\n\nTrong lúc ngủ, cơ thể tiết ra một loại hoóc-môn tăng trưởng giúp xương và cơ bắp phát triển, đồng thời bộ não cũng sử dụng thời gian này để sắp xếp lại những kiến thức đã học trong ngày, giúp việc ghi nhớ trở nên hiệu quả hơn. Đây là lý do vì sao nhiều học sinh thức khuya ôn bài thường học kém hiệu quả hơn so với việc ngủ đủ giấc rồi dậy sớm ôn lại.\n\nNgược lại, nếu thường xuyên thiếu ngủ, trẻ em có thể gặp phải tình trạng mệt mỏi, khó tập trung, dễ cáu gắt và giảm khả năng miễn dịch, khiến cơ thể dễ mắc bệnh hơn. Vì vậy, việc xây dựng thói quen đi ngủ đúng giờ, tránh sử dụng điện thoại hay xem ti vi ngay trước khi ngủ, sẽ giúp các em có một giấc ngủ ngon và một cơ thể khoẻ mạnh để học tập, vui chơi hiệu quả hơn mỗi ngày.",
  },
  {
    id: "dh-passage-14",
    title: "Cây bàng cuối sân trường",
    text: "Suốt năm năm học tiểu học, Thảo và các bạn luôn chọn gốc cây bàng cuối sân trường làm nơi tụ tập vào mỗi giờ ra chơi. Đó là nơi các bạn cùng nhau chơi ô ăn quan, kể chuyện cười, và cũng là nơi Thảo từng oà khóc khi bị điểm kém, được các bạn xúm lại an ủi.\n\nNhững ngày cuối cùng trước khi tốt nghiệp tiểu học, Thảo thường đến sớm hơn để ngồi một mình dưới gốc bàng, ngắm nhìn tán lá xanh rợp một góc sân. Cô nhớ lại biết bao kỷ niệm: lần cả nhóm nhặt lá bàng khô xếp thành hình trái tim, lần chơi trốn tìm mà Hùng núp sau gốc cây mãi không ai tìm ra, hay những buổi trưa hè ngồi tránh nắng, vừa ăn kem vừa tám chuyện.\n\nNgày chia tay, cả lớp tụ họp dưới gốc bàng để chụp một tấm ảnh kỷ niệm cuối cùng. Thảo đưa tay chạm nhẹ vào thân cây sần sùi, thầm cảm ơn cây bàng đã âm thầm chứng kiến suốt những năm tháng tuổi thơ của mình và bạn bè. Dù sắp phải chia xa mái trường quen thuộc để bước vào một hành trình mới, Thảo tin rằng những kỷ niệm dưới gốc bàng ấy sẽ mãi là một phần ký ức đẹp đẽ không thể nào quên.",
  },
  {
    id: "dh-passage-15",
    title: "Hạt giống trong sa mạc",
    text: "Ngày xưa, có một hạt giống nhỏ vô tình bị gió cuốn rơi xuống giữa vùng sa mạc khô cằn, xung quanh chỉ toàn cát nóng và không một giọt nước. Những hạt giống khác cùng lứa đã may mắn rơi xuống đồng cỏ xanh tươi, nhanh chóng nảy mầm thành cây con khoẻ mạnh, còn hạt giống nhỏ bé này chỉ biết nằm im giữa cát, tưởng như chẳng còn hy vọng gì.\n\nThế nhưng, hạt giống không từ bỏ. Mỗi đêm, khi sương đêm sa mạc đọng lại dù chỉ một chút ít ỏi, nó lại cố gắng hút từng giọt nước nhỏ nhoi để nuôi dưỡng mầm sống bên trong mình. Nhiều tháng trôi qua, chiếc rễ non yếu ớt của hạt giống vẫn kiên trì đâm sâu xuống lòng cát, tìm kiếm mạch nước ngầm ẩn sâu bên dưới.\n\nCuối cùng, sau một thời gian dài kiên trì, chiếc rễ chạm được đến mạch nước ngầm mát lành. Từ đó, hạt giống bắt đầu nảy mầm, vươn lên khỏi mặt cát thành một cây xương rồng nhỏ xinh, trở thành bóng mát hiếm hoi giữa sa mạc mênh mông, nơi những đoàn lữ hành mệt mỏi có thể dừng chân nghỉ ngơi. Cây xương rồng ấy đã chứng minh rằng, dù ở trong hoàn cảnh khó khăn nhất, chỉ cần không từ bỏ hy vọng và kiên trì cố gắng, sự sống vẫn có thể nảy nở theo cách riêng của mình.",
  },
  {
    id: "dh-passage-16",
    title: "Người lái đò trên sông",
    text: "Ở bến sông đầu làng, đã hơn hai mươi năm nay, bác Tám vẫn ngày ngày chèo đò đưa khách qua sông. Chiếc đò gỗ cũ kỹ nhưng luôn được bác giữ gìn sạch sẽ, chắc chắn. Ai trong làng cũng quý mến bác vì tính tình hiền hậu, sẵn sàng giúp đỡ mọi người dù trời nắng hay mưa.\n\nMột buổi tối mưa gió, khi bác Tám vừa định nghỉ ngơi thì nghe tiếng gọi thất thanh từ bờ bên kia. Đó là chú Sáu, tất tưởi xin bác chèo đò gấp vì con trai chú đang sốt cao, cần đưa đi trạm y tế bên này sông. Không ngần ngại, bác Tám khoác vội chiếc áo mưa, ra sức chèo đò vượt qua dòng nước đang chảy xiết vì mưa lớn.\n\nSuốt chặng đường, bác vừa chèo vừa trấn an chú Sáu đang lo lắng. Nhờ chuyến đò đêm ấy, con trai chú Sáu được đưa đến trạm y tế kịp thời và qua cơn nguy hiểm. Khi chú Sáu ngỏ ý gửi tiền cảm ơn, bác Tám chỉ cười xua tay: \"Cứu người lúc hoạn nạn là chuyện nên làm, tôi không nhận tiền đâu.\" Câu chuyện về bác lái đò tốt bụng được người dân trong làng truyền tai nhau mãi, ai cũng cảm phục tấm lòng nhân hậu của bác.",
  },
  {
    id: "dh-passage-17",
    title: "Chiếc đồng hồ của ông",
    text: "Trong ngăn tủ của bố, Long tình cờ tìm thấy một chiếc đồng hồ đeo tay cũ kỹ, mặt kính đã mờ, dây đeo sờn cũ. Tò mò, Long mang chiếc đồng hồ hỏi bố. Bố trầm ngâm một lúc rồi kể, đây là chiếc đồng hồ duy nhất mà ông nội để lại trước khi qua đời, từng theo ông suốt những năm tháng làm việc vất vả để nuôi các con ăn học.\n\nNghe bố kể, Long xin phép được sửa lại chiếc đồng hồ để có thể đeo nó. Bố đồng ý nhưng dặn dò Long phải giữ gìn cẩn thận. Long mang đồng hồ đến một tiệm sửa chữa quen thuộc trong xóm, nhờ bác thợ lau chùi, thay dây mới. Khi nhận lại chiếc đồng hồ đã chạy đều trở lại, Long cảm thấy vô cùng xúc động, như thể mình đang được kết nối với người ông mà cậu chưa từng có cơ hội gặp mặt.\n\nTừ đó, Long luôn đeo chiếc đồng hồ ấy mỗi ngày, không phải vì nó đẹp hay hiện đại, mà vì nó nhắc cậu nhớ đến những vất vả mà ông nội đã trải qua để xây dựng nên gia đình hạnh phúc hôm nay. Long tự nhủ sẽ cố gắng học tập thật tốt, để xứng đáng với những hy sinh thầm lặng của ông.",
  },
  {
    id: "dh-passage-18",
    title: "Vì sao chúng ta cần uống đủ nước",
    text: "Nước chiếm khoảng 70% trọng lượng cơ thể con người và đóng vai trò vô cùng quan trọng đối với hầu hết các hoạt động sống. Các bác sĩ khuyến nghị trẻ em nên uống đủ từ một lít đến một lít rưỡi nước mỗi ngày, tuỳ theo độ tuổi và mức độ vận động.\n\nNước giúp vận chuyển chất dinh dưỡng và ô-xi đến các tế bào trong cơ thể, đồng thời đào thải các chất cặn bã ra ngoài qua đường mồ hôi và nước tiểu. Ngoài ra, nước còn giúp điều hoà thân nhiệt, đặc biệt quan trọng vào những ngày thời tiết nóng bức hoặc khi vận động mạnh, cơ thể ra nhiều mồ hôi.\n\nKhi cơ thể không được cung cấp đủ nước, chúng ta có thể gặp phải tình trạng mất nước với các biểu hiện như khô miệng, mệt mỏi, đau đầu, khó tập trung, thậm chí chóng mặt nếu tình trạng kéo dài. Vì vậy, thay vì đợi đến khi cảm thấy khát mới uống nước, các em nên tập thói quen uống nước đều đặn trong ngày, đặc biệt là sau khi vận động hoặc chơi thể thao, để cơ thể luôn khoẻ mạnh và tràn đầy năng lượng.",
  },
  {
    id: "dh-passage-19",
    title: "Cuộc phiêu lưu trong thư viện",
    text: "Vy vốn không thích đọc sách, mỗi lần đến thư viện trường chỉ để ngồi cho hết giờ theo yêu cầu của cô giáo. Một hôm, khi đang lơ đãng lướt qua các kệ sách, Vy vô tình làm rơi một cuốn sách cũ có bìa vẽ hình một khu rừng bí ẩn. Tò mò, Vy nhặt lên và đọc thử vài trang đầu.\n\nCàng đọc, Vy càng bị cuốn vào câu chuyện về một nhóm bạn nhỏ phiêu lưu tìm kho báu trong khu rừng kỳ lạ, vượt qua bao thử thách hồi hộp. Vy quên mất thời gian, đọc một mạch đến hết buổi mà không hay biết. Khi tiếng chuông báo hết giờ vang lên, Vy ngỡ ngàng nhận ra mình đã đọc hết một phần ba cuốn sách dày mà không hề thấy chán như mọi khi.\n\nTừ hôm đó, Vy bắt đầu mượn sách về nhà đọc mỗi tối, dần dần khám phá ra nhiều thể loại sách thú vị khác nhau, từ truyện phiêu lưu đến sách khoa học. Vy nhận ra rằng thư viện không hề nhàm chán như mình từng nghĩ, mà giống như một cánh cửa mở ra vô vàn thế giới kỳ diệu, chỉ cần mình chịu khó bước vào khám phá.",
  },
  {
    id: "dh-passage-20",
    title: "Bạn đồng hành trên đường đến trường",
    text: "Sáng hôm ấy, trời mưa to bất ngờ khiến con đường đất dẫn vào xóm của Tân ngập nước, bùn lầy trơn trượt. Xe đạp của Tân đi được nửa đường thì bị sa lầy, bánh xe quay tít mà không nhích lên được. Tân loay hoay mãi vẫn không đẩy được xe qua đoạn lầy, trong khi giờ vào học đã sắp đến.\n\nĐúng lúc đó, Hải — bạn cùng xóm học chung lớp — đạp xe ngang qua, thấy vậy liền dừng lại giúp đỡ. Hai bạn cùng nhau xắn quần lội xuống bùn, người đẩy, người kéo, cuối cùng cũng đưa được xe của Tân qua khỏi đoạn đường lầy lội. Cả hai đều lấm lem bùn đất nhưng không ai than phiền, chỉ cười với nhau rồi cùng đạp xe thật nhanh đến trường.\n\nHôm đó, dù đến lớp trễ vài phút và bị cô giáo nhắc nhở, nhưng Tân không hề buồn, ngược lại còn thấy vui vì có một người bạn tốt luôn sẵn sàng giúp đỡ mình lúc khó khăn. Từ đó, tình bạn giữa Tân và Hải càng thêm gắn bó, cả hai thường xuyên đạp xe đi học cùng nhau, cùng nhau vượt qua những đoạn đường khó đi mỗi khi trời mưa.",
  },
  {
    id: "dh-passage-21",
    title: "Loài ong và công việc thụ phấn",
    text: "Ong không chỉ là loài vật cho chúng ta mật ngọt mà còn đóng vai trò cực kỳ quan trọng trong tự nhiên với công việc thụ phấn cho hoa. Khi ong bay từ bông hoa này sang bông hoa khác để hút mật, những hạt phấn hoa nhỏ li ti sẽ dính vào lông trên cơ thể ong và được mang theo đến những bông hoa tiếp theo.\n\nNhờ quá trình này, phấn hoa từ nhị hoa (bộ phận sinh sản đực) được chuyển đến nhuỵ hoa (bộ phận sinh sản cái) của một bông hoa khác, giúp cây có thể kết trái, tạo ra hạt giống cho thế hệ cây tiếp theo. Các nhà khoa học ước tính có đến hơn một phần ba lượng thực phẩm mà con người tiêu thụ mỗi ngày, như các loại trái cây, rau củ, đều phụ thuộc một phần vào quá trình thụ phấn của ong và các loài côn trùng khác.\n\nĐáng tiếc, trong những năm gần đây, số lượng ong trên thế giới đang suy giảm đáng kể do việc sử dụng thuốc trừ sâu quá mức, mất môi trường sống tự nhiên và biến đổi khí hậu. Nếu loài ong biến mất, không chỉ ngành nông nghiệp bị ảnh hưởng nặng nề mà cả hệ sinh thái tự nhiên cũng có thể mất cân bằng nghiêm trọng. Vì vậy, việc bảo vệ loài ong đang trở thành một vấn đề môi trường được nhiều quốc gia quan tâm.",
  },
  {
    id: "dh-passage-22",
    title: "Chiếc bánh trung thu đầu tiên",
    text: "Năm nay, thay vì mua bánh trung thu như mọi năm, mẹ quyết định cả nhà sẽ cùng nhau tự làm bánh. Bé Su háo hức lắm vì đây là lần đầu tiên cô được tự tay làm bánh trung thu cùng mẹ và chị Hai. Mẹ chuẩn bị sẵn bột, nhân đậu xanh, khuôn bánh hình hoa và hình cá chép truyền thống.\n\nBan đầu, Su nặn bột vụng về, chiếc bánh đầu tiên méo mó, nhân bị lộ ra ngoài trông không được đẹp mắt. Su hơi buồn, định bỏ cuộc, nhưng chị Hai động viên: \"Không sao đâu, ai làm lần đầu chẳng vụng về, cứ thử lại vài lần nữa xem.\" Được chị hướng dẫn cách vo bột đều tay và ém nhân kỹ hơn, những chiếc bánh sau của Su dần đẹp hơn hẳn.\n\nTối hôm đó, cả nhà quây quần bên mâm bánh tự làm, cùng nhau thưởng thức dưới ánh trăng rằm. Dù hình dáng bánh không hoàn hảo như bánh mua ngoài tiệm, nhưng ai cũng khen ngon và ấm áp hơn hẳn. Su cảm thấy tự hào vì chiếc bánh trung thu đầu tiên do chính tay mình làm ra, và Tết Trung thu năm ấy trở thành một trong những kỷ niệm đáng nhớ nhất mà cô sẽ không bao giờ quên.",
  },
  {
    id: "dh-passage-23",
    title: "Bài học từ trận thua bóng đá",
    text: "Đội bóng của lớp 5B do Duy làm đội trưởng đã lọt vào trận chung kết giải bóng đá học sinh toàn trường. Suốt cả tháng, cả đội miệt mài tập luyện mỗi buổi chiều, ai cũng tin rằng năm nay đội sẽ giành được chức vô địch đầu tiên.\n\nTuy nhiên, trong trận chung kết, dù chơi rất nỗ lực nhưng đội của Duy vẫn để thua đối thủ với tỷ số sít sao 2-1, khi cơ hội gỡ hoà cuối cùng bị bỏ lỡ đáng tiếc. Cả đội buồn bã, một vài bạn còn bật khóc ngay trên sân vì tiếc nuối. Duy cũng rất thất vọng nhưng cố kìm nén cảm xúc để động viên đồng đội.\n\nTối hôm đó, thầy giáo chủ nhiệm gọi cả đội lại, nói rằng: \"Thua một trận đấu không có nghĩa là các em thất bại, quan trọng là các em đã cùng nhau cố gắng hết mình và đoàn kết suốt cả mùa giải.\" Nghe thầy nói, Duy và các bạn dần nguôi ngoai, nhận ra rằng tinh thần thể thao và sự nỗ lực hết mình mới là điều đáng quý nhất, không nhất thiết phải chiến thắng mới là thành công. Cả đội hẹn nhau mùa giải sau sẽ tiếp tục cố gắng nhiều hơn nữa.",
  },
  {
    id: "dh-passage-24",
    title: "Cụ già bán bánh mì",
    text: "Ở góc phố gần trường, có một cụ già bán bánh mì đã ngồi đó từ khi Nghĩa còn học lớp một. Chiếc xe bánh mì cũ kỹ của cụ luôn được lau chùi sạch sẽ, dù trời nắng hay mưa cụ vẫn kiên trì ngồi bán từ sáng sớm đến tận trưa. Nhiều bạn học sinh thường nói rằng bánh mì của cụ tuy giản dị nhưng luôn nóng hổi và đậm đà.\n\nMột hôm, Nghĩa vô tình nghe cụ kể chuyện với một người khách quen rằng cụ đã bán bánh mì suốt hơn ba mươi năm để nuôi các con ăn học, giờ các con đã trưởng thành và có công việc ổn định, khuyên cụ nghỉ ngơi nhưng cụ vẫn muốn tiếp tục bán hàng vì đã quen với công việc, hơn nữa cụ thấy mình còn khoẻ, ngồi ở nhà mới thấy buồn chán.\n\nNghe câu chuyện ấy, Nghĩa cảm thấy vô cùng khâm phục nghị lực và tình yêu lao động của cụ già. Từ đó, mỗi lần mua bánh mì, Nghĩa đều lễ phép chào hỏi cụ và đôi khi nán lại trò chuyện đôi câu. Nghĩa nhận ra rằng, dù công việc giản dị đến đâu, nếu được làm với sự cần cù và tình yêu, nó vẫn mang lại ý nghĩa và niềm vui to lớn cho con người.",
  },
  {
    id: "dh-passage-25",
    title: "Vì sao có sấm sét",
    text: "Vào những cơn mưa giông, chúng ta thường thấy những tia chớp sáng loé trên bầu trời, sau đó vài giây mới nghe thấy tiếng sấm ầm ầm. Hiện tượng này xảy ra là do bên trong những đám mây giông có sự va chạm mạnh giữa các hạt nước, hạt băng nhỏ, tạo ra một lượng điện tích rất lớn.\n\nKhi lượng điện tích tích tụ đủ lớn, nó sẽ phóng ra ngoài không khí dưới dạng một tia sáng chói loà mà chúng ta gọi là sét, đôi khi phóng giữa các đám mây với nhau, đôi khi phóng thẳng xuống mặt đất. Luồng điện cực mạnh này khiến không khí xung quanh bị nung nóng đột ngột lên đến hàng nghìn độ, giãn nở cực nhanh và tạo ra tiếng nổ lớn mà ta gọi là sấm.\n\nSở dĩ chúng ta luôn nhìn thấy chớp trước rồi mới nghe thấy sấm là vì ánh sáng truyền đi nhanh hơn âm thanh rất nhiều lần. Dựa vào khoảng thời gian giữa lúc thấy chớp và nghe thấy sấm, người ta có thể ước tính được khoảng cách từ nơi mình đứng đến chỗ sét đánh: cứ khoảng ba giây tương ứng với một ki-lô-mét. Vì sét có thể gây nguy hiểm, các em nên tránh đứng dưới cây cao hoặc cầm đồ vật kim loại khi trời có giông sét.",
  },
];
