import type { Exercise } from "@/data-access/types";

// CA-01 — Câu và các thành phần chính (chủ ngữ, vị ngữ). Câu ví dụ tự biên
// soạn (Mục 10.1 hướng B).
export const CA01_EXERCISES: Exercise[] = [
  {
    id: "ca-01-mcq-1",
    topicIds: ["CA-01"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Trong câu "Bạn Lan học bài rất chăm chỉ.", đâu là chủ ngữ?',
    explanation: "\"Bạn Lan\" trả lời câu hỏi \"Ai?\" và là chủ ngữ của câu.",
    mcq: {
      options: ["Bạn Lan", "học bài", "rất chăm chỉ", "chăm chỉ"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"Bạn Lan\" là chủ ngữ, trả lời câu hỏi \"Ai?\".",
        "\"Học bài\" là một phần của vị ngữ, không phải chủ ngữ.",
        "\"Rất chăm chỉ\" là một phần của vị ngữ, không phải chủ ngữ.",
        "\"Chăm chỉ\" chỉ là một từ trong vị ngữ, không phải chủ ngữ đầy đủ.",
      ],
    },
  },
  {
    id: "ca-01-mcq-2",
    topicIds: ["CA-01"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Sáng nay, em đi học sớm.", "Sáng nay" đóng vai trò gì?',
    explanation: "\"Sáng nay\" là trạng ngữ chỉ thời gian, không phải chủ ngữ — chủ ngữ của câu là \"em\".",
    mcq: {
      options: ["Chủ ngữ", "Vị ngữ", "Trạng ngữ", "Không có vai trò gì"],
      answerIndex: 2,
      distractorNotes: [
        "\"Sáng nay\" không trả lời câu hỏi \"Ai?\" nên không phải chủ ngữ — chủ ngữ thực sự là \"em\".",
        "Trạng ngữ không phải vị ngữ.",
        "Đúng — \"Sáng nay\" bổ sung ý nghĩa thời gian cho câu, là trạng ngữ.",
        "\"Sáng nai\" có vai trò trạng ngữ, không phải là thành phần thừa.",
      ],
    },
  },
  {
    id: "ca-01-fill-1",
    topicIds: ["CA-01"],
    level: "M1",
    questionType: "fill",
    prompt:
      "Điền từ còn thiếu: Trong một câu đơn, hai thành phần chính là chủ ngữ và ___.",
    explanation: "Câu đơn có hai thành phần chính: chủ ngữ và vị ngữ.",
    fill: { acceptedAnswers: ["vị ngữ"], strictMode: false, isSet: false },
  },
  {
    id: "ca-01-order-1",
    topicIds: ["CA-01"],
    level: "M2",
    questionType: "order",
    prompt: "Sắp xếp các phần dưới đây thành một câu có đủ chủ ngữ và vị ngữ.",
    explanation: "Câu đúng: \"Con mèo nhà em đang ngủ trên ghế.\" — chủ ngữ \"Con mèo nhà em\" đứng trước, vị ngữ \"đang ngủ trên ghế\" đứng sau.",
    order: {
      items: [
        { id: "o1", label: "Con mèo nhà em" },
        { id: "o2", label: "đang ngủ" },
        { id: "o3", label: "trên ghế" },
      ],
      correctOrder: ["o1", "o2", "o3"],
    },
  },
  {
    id: "ca-01-mcq-3",
    topicIds: ["CA-01"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Trong câu "Đàn chim bay về tổ.", đâu là vị ngữ?',
    explanation: "\"Bay về tổ\" là hoạt động của đàn chim, trả lời câu hỏi \"làm gì?\" — là vị ngữ.",
    mcq: {
      options: ["Đàn chim", "bay về tổ", "về tổ", "Đàn"],
      answerIndex: 1,
      distractorNotes: [
        "\"Đàn chim\" là chủ ngữ, trả lời câu hỏi \"Con gì?\".",
        "Đúng — \"bay về tổ\" trả lời câu hỏi \"làm gì?\", là vị ngữ.",
        "\"Về tổ\" chỉ là một phần của vị ngữ, thiếu động từ chính \"bay\".",
        "\"Đàn\" chỉ là một từ trong chủ ngữ, không phải chủ ngữ đầy đủ.",
      ],
    },
  },
  {
    id: "ca-01-mcq-4",
    topicIds: ["CA-01"],
    level: "M2",
    questionType: "mcq",
    prompt: "Câu nào dưới đây bị THIẾU vị ngữ?",
    explanation: "\"Những bông hoa hồng đỏ thắm trong vườn nhà em.\" chỉ là một cụm danh từ dài, không có động từ/tính từ làm vị ngữ.",
    mcq: {
      options: [
        "Em đi học.",
        "Những bông hoa hồng đỏ thắm trong vườn nhà em.",
        "Trời mưa to.",
        "Bạn Lan đang đọc sách.",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Câu này đủ chủ ngữ \"Em\" và vị ngữ \"đi học\".",
        "Đúng — đây chỉ là một cụm danh từ dài, không có vị ngữ hoàn chỉnh.",
        "Câu này đủ chủ ngữ \"Trời\" và vị ngữ \"mưa to\".",
        "Câu này đủ chủ ngữ \"Bạn Lan\" và vị ngữ \"đang đọc sách\".",
      ],
    },
  },
  {
    id: "ca-01-mcq-5",
    topicIds: ["CA-01"],
    level: "M1",
    questionType: "mcq",
    prompt: "Vị ngữ thường trả lời cho câu hỏi nào?",
    explanation: "Vị ngữ trả lời cho các câu hỏi \"làm gì?\", \"thế nào?\", \"là gì?\".",
    mcq: {
      options: ["Ai? / Con gì? / Cái gì?", "Làm gì? / Thế nào? / Là gì?", "Ở đâu?", "Khi nào?"],
      answerIndex: 1,
      distractorNotes: [
        "Đây là câu hỏi mà CHỦ NGỮ trả lời, không phải vị ngữ.",
        "Đúng — vị ngữ trả lời cho các câu hỏi này.",
        "Đây là câu hỏi của trạng ngữ chỉ nơi chốn.",
        "Đây là câu hỏi của trạng ngữ chỉ thời gian.",
      ],
    },
  },
  {
    id: "ca-01-mcq-6",
    topicIds: ["CA-01"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Rất đẹp!" có đủ chủ ngữ và vị ngữ không?',
    explanation: "\"Rất đẹp!\" chỉ có phần miêu tả, thiếu chủ ngữ (đẹp cái gì/ai đẹp không rõ), nên đây là câu đặc biệt/thiếu thành phần, không phải câu đầy đủ hai thành phần chính.",
    mcq: {
      options: [
        "Có, đủ cả chủ ngữ và vị ngữ",
        "Không, câu này thiếu chủ ngữ",
        "Không, câu này thiếu vị ngữ",
        "Không, câu này thiếu cả chủ ngữ và vị ngữ",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Câu này không có phần nào trả lời \"Ai?\"/\"Cái gì?\" nên chưa đủ chủ ngữ.",
        "Đúng — \"rất đẹp\" là phần miêu tả (có thể coi là vị ngữ) nhưng thiếu chủ ngữ đứng trước.",
        "Câu này có phần vị ngữ \"rất đẹp\".",
        "Câu này vẫn có vị ngữ, chỉ thiếu chủ ngữ.",
      ],
    },
  },
  {
    id: "ca-01-match-1",
    topicIds: ["CA-01"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi cụm chủ ngữ ở cột trái với cụm vị ngữ phù hợp ở cột phải để tạo thành câu hoàn chỉnh, có nghĩa.",
    explanation: "\"Đàn cá\" đi với \"bơi tung tăng trong hồ\"; \"Bà em\" đi với \"đang kể chuyện cổ tích\"; \"Mặt trời\" đi với \"toả nắng ấm áp\".",
    match: {
      leftItems: [
        { id: "l1", label: "Đàn cá" },
        { id: "l2", label: "Bà em" },
        { id: "l3", label: "Mặt trời" },
      ],
      rightItems: [
        { id: "r1", label: "toả nắng ấm áp" },
        { id: "r2", label: "bơi tung tăng trong hồ" },
        { id: "r3", label: "đang kể chuyện cổ tích" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r3" },
        { leftId: "l3", rightId: "r1" },
      ],
    },
  },
  {
    id: "ca-01-fill-2",
    topicIds: ["CA-01"],
    level: "M1",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Trong câu "Bố em đang sửa xe.", chủ ngữ là ___.',
    explanation: "\"Bố em\" trả lời câu hỏi \"Ai?\", là chủ ngữ.",
    fill: { acceptedAnswers: ["Bố em", "bố em"], strictMode: false, isSet: false },
  },
  {
    id: "ca-01-mcq-7",
    topicIds: ["CA-01"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Trong câu "Những chiếc lá vàng rơi lả tả xuống sân trường.", chủ ngữ là gì?',
    explanation: "\"Những chiếc lá vàng\" là cụm danh từ đầy đủ làm chủ ngữ, trả lời câu hỏi \"Cái gì?\".",
    mcq: {
      options: ["Những chiếc lá vàng", "rơi lả tả", "xuống sân trường", "lả tả"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"những chiếc lá vàng\" là cụm danh từ đầy đủ, trả lời câu hỏi \"Cái gì?\".",
        "\"Rơi lả tả\" là một phần của vị ngữ.",
        "\"Xuống sân trường\" là một phần của vị ngữ, chỉ nơi chốn.",
        "\"Lả tả\" chỉ là một từ láy trong vị ngữ, không phải chủ ngữ.",
      ],
    },
  },
  {
    id: "ca-01-mcq-8",
    topicIds: ["CA-01"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Cả lớp im lặng lắng nghe cô giáo giảng bài.", đâu là vị ngữ?',
    explanation: "\"Im lặng lắng nghe cô giáo giảng bài\" là hoạt động/trạng thái của cả lớp, trả lời câu hỏi \"làm gì?/thế nào?\" — là vị ngữ.",
    mcq: {
      options: ["Cả lớp", "im lặng lắng nghe cô giáo giảng bài", "cô giáo", "giảng bài"],
      answerIndex: 1,
      distractorNotes: [
        "\"Cả lớp\" là chủ ngữ, trả lời câu hỏi \"Ai?\".",
        "Đúng — đây là toàn bộ phần vị ngữ của câu.",
        "\"Cô giáo\" chỉ là một phần nhỏ trong vị ngữ, không phải toàn bộ vị ngữ.",
        "\"Giảng bài\" chỉ là một phần nhỏ trong vị ngữ, không phải toàn bộ vị ngữ.",
      ],
    },
  },
];
