import type { Exercise } from "@/data-access/types";

// CA-04 — Các kiểu câu chia theo mục đích nói. Câu ví dụ tự biên soạn (Mục
// 10.1 hướng B).
export const CA04_EXERCISES: Exercise[] = [
  {
    id: "ca-04-mcq-1",
    topicIds: ["CA-04"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Câu "Ôi, cảnh đẹp quá!" thuộc kiểu câu nào?',
    explanation: "Câu bộc lộ cảm xúc (từ \"Ôi\", \"quá\", dấu chấm than) là câu cảm.",
    mcq: {
      options: ["Câu kể", "Câu hỏi", "Câu khiến", "Câu cảm"],
      answerIndex: 3,
      distractorNotes: [
        "Câu kể dùng để kể, tả, thông báo, không bộc lộ cảm xúc mạnh như câu này.",
        "Câu hỏi cần có từ nghi vấn và dấu chấm hỏi, câu này không có.",
        "Câu khiến dùng để yêu cầu, đề nghị, câu này không yêu cầu điều gì.",
        "Đúng — từ \"Ôi\" và \"quá\" cùng dấu chấm than thể hiện đây là câu cảm.",
      ],
    },
  },
  {
    id: "ca-04-mcq-2",
    topicIds: ["CA-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu nào dưới đây là câu khiến?',
    explanation: "\"Hãy giữ trật tự!\" có từ \"hãy\" dùng để yêu cầu, đề nghị — đây là câu khiến.",
    mcq: {
      options: [
        "Hôm nay trời rất đẹp.",
        "Hãy giữ trật tự!",
        "Bạn có đi học không?",
        "Ôi, đẹp quá!",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Đây là câu kể, thông báo về thời tiết.",
        "Đúng — từ \"hãy\" thể hiện lời yêu cầu, đề nghị.",
        "Đây là câu hỏi, có từ nghi vấn \"có...không\".",
        "Đây là câu cảm, bộc lộ cảm xúc.",
      ],
    },
  },
  {
    id: "ca-04-fill-1",
    topicIds: ["CA-04"],
    level: "M1",
    questionType: "fill",
    prompt: "Điền từ còn thiếu: Câu dùng để nêu yêu cầu, đề nghị hoặc ra lệnh được gọi là câu ___.",
    explanation: "Câu khiến dùng để nêu yêu cầu, đề nghị hoặc ra lệnh, thường có từ \"hãy, đừng, chớ, nên\".",
    fill: { acceptedAnswers: ["khiến"], strictMode: false, isSet: false },
  },
  {
    id: "ca-04-mcq-3",
    topicIds: ["CA-04"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Câu "Bạn có thích đọc sách không?" thuộc kiểu câu nào?',
    explanation: "Câu có cấu trúc nghi vấn \"có...không\" và dấu chấm hỏi — là câu hỏi.",
    mcq: {
      options: ["Câu kể", "Câu hỏi", "Câu khiến", "Câu cảm"],
      answerIndex: 1,
      distractorNotes: [
        "Câu kể không dùng cấu trúc nghi vấn.",
        "Đúng — cấu trúc \"có...không\" và dấu chấm hỏi cho thấy đây là câu hỏi.",
        "Câu khiến không hỏi mà yêu cầu, đề nghị.",
        "Câu cảm bộc lộ cảm xúc, không hỏi.",
      ],
    },
  },
  {
    id: "ca-04-mcq-4",
    topicIds: ["CA-04"],
    level: "M2",
    questionType: "mcq",
    prompt: "Câu kể dùng để làm gì?",
    explanation: "Câu kể dùng để kể, tả hoặc thông báo về một sự việc, không dùng để hỏi, yêu cầu hay bộc lộ cảm xúc mạnh.",
    mcq: {
      options: [
        "Nêu yêu cầu, đề nghị",
        "Hỏi về điều chưa biết",
        "Kể, tả hoặc thông báo về sự việc",
        "Bộc lộ cảm xúc mạnh",
      ],
      answerIndex: 2,
      distractorNotes: [
        "Đây là chức năng của câu khiến.",
        "Đây là chức năng của câu hỏi.",
        "Đúng — đây là chức năng chính của câu kể.",
        "Đây là chức năng của câu cảm.",
      ],
    },
  },
  {
    id: "ca-04-mcq-5",
    topicIds: ["CA-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Đừng chạy trên hành lang!" thuộc kiểu câu nào?',
    explanation: "Từ \"đừng\" dùng để ngăn cấm, đề nghị không làm việc gì — đây là câu khiến.",
    mcq: {
      options: ["Câu kể", "Câu hỏi", "Câu khiến", "Câu cảm"],
      answerIndex: 2,
      distractorNotes: [
        "Câu này không kể hay thông báo sự việc.",
        "Câu này không hỏi điều gì.",
        "Đúng — từ \"đừng\" thể hiện lời đề nghị không nên làm, là câu khiến.",
        "Câu này không bộc lộ cảm xúc mạnh dù có dấu chấm than — dấu chấm than ở đây chỉ nhấn mạnh lời đề nghị.",
      ],
    },
  },
  {
    id: "ca-04-mcq-6",
    topicIds: ["CA-04"],
    level: "M2",
    questionType: "mcq",
    prompt: "Dấu câu nào thường dùng để kết thúc câu cảm?",
    explanation: "Câu cảm thường kết thúc bằng dấu chấm than để nhấn mạnh cảm xúc.",
    mcq: {
      options: ["Dấu chấm (.)", "Dấu chấm hỏi (?)", "Dấu chấm than (!)", "Dấu hai chấm (:)"],
      answerIndex: 2,
      distractorNotes: [
        "Dấu chấm thường dùng cho câu kể.",
        "Dấu chấm hỏi dùng cho câu hỏi.",
        "Đúng — dấu chấm than thường dùng để kết thúc câu cảm.",
        "Dấu hai chấm dùng để báo hiệu lời dẫn hoặc liệt kê.",
      ],
    },
  },
  {
    id: "ca-04-fill-2",
    topicIds: ["CA-04"],
    level: "M1",
    questionType: "fill",
    prompt: "Điền từ còn thiếu: Câu dùng để hỏi về điều mình chưa biết được gọi là câu ___.",
    explanation: "Câu hỏi dùng để hỏi về điều người nói chưa biết, cần được trả lời.",
    fill: { acceptedAnswers: ["hỏi"], strictMode: false, isSet: false },
  },
  {
    id: "ca-04-mcq-7",
    topicIds: ["CA-04"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Câu "Bạn có thể đóng cửa sổ giúp mình không?" tuy có hình thức câu hỏi nhưng thực chất được dùng với mục đích gì?',
    explanation: "Đây là câu hỏi mang tính lịch sự, thực chất dùng để đề nghị/yêu cầu (đóng cửa sổ), không phải để hỏi thông tin.",
    mcq: {
      options: [
        "Hỏi thông tin về khả năng của người nghe",
        "Đề nghị, yêu cầu một cách lịch sự",
        "Bộc lộ cảm xúc",
        "Kể lại một sự việc",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Người nói không thực sự muốn biết về \"khả năng\", mà muốn nhờ giúp đỡ.",
        "Đúng — đây là cách dùng câu hỏi để đề nghị một cách lịch sự, tế nhị.",
        "Câu này không bộc lộ cảm xúc mạnh.",
        "Câu này không kể lại sự việc nào.",
      ],
    },
  },
  {
    id: "ca-04-match-1",
    topicIds: ["CA-04"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi câu ở cột trái với đúng kiểu câu (theo mục đích nói) ở cột phải.",
    explanation: "\"Trời hôm nay nắng đẹp.\" — câu kể; \"Bạn tên là gì?\" — câu hỏi; \"Hãy về nhà đúng giờ!\" — câu khiến.",
    match: {
      leftItems: [
        { id: "l1", label: "Trời hôm nay nắng đẹp." },
        { id: "l2", label: "Bạn tên là gì?" },
        { id: "l3", label: "Hãy về nhà đúng giờ!" },
      ],
      rightItems: [
        { id: "r1", label: "Câu khiến" },
        { id: "r2", label: "Câu kể" },
        { id: "r3", label: "Câu hỏi" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r3" },
        { leftId: "l3", rightId: "r1" },
      ],
    },
  },
  {
    id: "ca-04-mcq-8",
    topicIds: ["CA-04"],
    level: "M2",
    questionType: "mcq",
    prompt: "Có mấy kiểu câu chia theo mục đích nói đã học?",
    explanation: "Có 4 kiểu: câu kể, câu hỏi, câu khiến, câu cảm.",
    mcq: {
      options: ["2 kiểu", "3 kiểu", "4 kiểu", "5 kiểu"],
      answerIndex: 2,
      distractorNotes: [
        "Thiếu 2 kiểu so với thực tế.",
        "Thiếu 1 kiểu so với thực tế.",
        "Đúng — có 4 kiểu: câu kể, câu hỏi, câu khiến, câu cảm.",
        "Chỉ có 4 kiểu, không phải 5.",
      ],
    },
  },
  {
    id: "ca-04-mcq-9",
    topicIds: ["CA-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Chao ôi, chú chó này thật đáng yêu!" thuộc kiểu câu nào?',
    explanation: "Từ cảm thán \"chao ôi\" cùng dấu chấm than thể hiện đây là câu cảm, bộc lộ cảm xúc thích thú.",
    mcq: {
      options: ["Câu kể", "Câu hỏi", "Câu khiến", "Câu cảm"],
      answerIndex: 3,
      distractorNotes: [
        "Câu kể không bộc lộ cảm xúc mạnh như thế này.",
        "Câu này không có từ nghi vấn.",
        "Câu này không yêu cầu, đề nghị điều gì.",
        "Đúng — \"chao ôi\" và dấu chấm than thể hiện cảm xúc, là câu cảm.",
      ],
    },
  },
];
