import type { Exercise } from "@/data-access/types";

// CA-02 — Trạng ngữ và các loại trạng ngữ. Câu ví dụ tự biên soạn (Mục 10.1
// hướng B).
export const CA02_EXERCISES: Exercise[] = [
  {
    id: "ca-02-mcq-1",
    topicIds: ["CA-02"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Trạng ngữ trong câu "Vì trời mưa to, chúng em phải nghỉ học." trả lời cho câu hỏi nào?',
    explanation: "Trạng ngữ \"Vì trời mưa to\" nêu nguyên nhân, trả lời câu hỏi \"Vì sao?\".",
    mcq: {
      options: ["Khi nào?", "Ở đâu?", "Vì sao?", "Để làm gì?"],
      answerIndex: 2,
      distractorNotes: [
        "Trạng ngữ chỉ thời gian trả lời câu hỏi này, câu trên là trạng ngữ chỉ nguyên nhân.",
        "Trạng ngữ chỉ nơi chốn trả lời câu hỏi này, câu trên là trạng ngữ chỉ nguyên nhân.",
        "Đúng — \"Vì trời mưa to\" nêu nguyên nhân của việc nghỉ học.",
        "Trạng ngữ chỉ mục đích trả lời câu hỏi này, câu trên là trạng ngữ chỉ nguyên nhân.",
      ],
    },
  },
  {
    id: "ca-02-mcq-2",
    topicIds: ["CA-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu nào dưới đây có trạng ngữ chỉ mục đích?',
    explanation: "\"Để đạt kết quả tốt\" nêu mục đích của hành động ôn bài, trả lời câu hỏi \"Để làm gì?\".",
    mcq: {
      options: [
        "Sáng nay, em dậy sớm hơn mọi ngày.",
        "Để đạt kết quả tốt, em cần ôn bài đều đặn.",
        "Ở sân trường, các bạn đang chơi nhảy dây.",
        "Bằng chiếc xe đạp cũ, em đến trường mỗi ngày.",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Đây là trạng ngữ chỉ thời gian.",
        "Đúng — \"Để đạt kết quả tốt\" là trạng ngữ chỉ mục đích.",
        "Đây là trạng ngữ chỉ nơi chốn.",
        "Đây là trạng ngữ chỉ phương tiện.",
      ],
    },
  },
  {
    id: "ca-02-fill-1",
    topicIds: ["CA-02"],
    level: "M1",
    questionType: "fill",
    prompt:
      "Điền từ còn thiếu: Trạng ngữ thường đứng ở đầu câu và ngăn cách với nòng cốt câu bằng dấu ___.",
    explanation: "Trạng ngữ đứng đầu câu thường được ngăn cách với phần còn lại của câu bằng dấu phẩy.",
    fill: { acceptedAnswers: ["phẩy", "dấu phẩy"], strictMode: false, isSet: false },
  },
  {
    id: "ca-02-mcq-3",
    topicIds: ["CA-02"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Trong câu "Trên cành cây, những chú chim đang ríu rít hót.", trạng ngữ "Trên cành cây" thuộc loại nào?',
    explanation: "\"Trên cành cây\" chỉ vị trí, nơi diễn ra sự việc — đây là trạng ngữ chỉ nơi chốn.",
    mcq: {
      options: ["Trạng ngữ chỉ thời gian", "Trạng ngữ chỉ nơi chốn", "Trạng ngữ chỉ nguyên nhân", "Trạng ngữ chỉ mục đích"],
      answerIndex: 1,
      distractorNotes: [
        "\"Trên cành cây\" không nêu thời gian.",
        "Đúng — \"Trên cành cây\" nêu vị trí, nơi diễn ra sự việc.",
        "\"Trên cành cây\" không nêu nguyên nhân.",
        "\"Trên cành cây\" không nêu mục đích.",
      ],
    },
  },
  {
    id: "ca-02-mcq-4",
    topicIds: ["CA-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trạng ngữ trong câu "Bằng đôi tay khéo léo, bà em đan chiếc khăn len." thuộc loại nào?',
    explanation: "\"Bằng đôi tay khéo léo\" nêu công cụ/cách thức thực hiện hành động — trạng ngữ chỉ phương tiện/cách thức.",
    mcq: {
      options: ["Trạng ngữ chỉ thời gian", "Trạng ngữ chỉ phương tiện", "Trạng ngữ chỉ nguyên nhân", "Trạng ngữ chỉ nơi chốn"],
      answerIndex: 1,
      distractorNotes: [
        "\"Bằng đôi tay khéo léo\" không nêu thời gian.",
        "Đúng — trạng ngữ này nêu phương tiện/cách thức thực hiện hành động.",
        "\"Bằng đôi tay khéo léo\" không nêu nguyên nhân.",
        "\"Bằng đôi tay khéo léo\" không nêu nơi chốn.",
      ],
    },
  },
  {
    id: "ca-02-mcq-5",
    topicIds: ["CA-02"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Trạng ngữ trong câu "Tối qua, cả nhà em cùng xem phim." trả lời cho câu hỏi nào?',
    explanation: "\"Tối qua\" chỉ thời điểm sự việc diễn ra, trả lời câu hỏi \"Khi nào?\".",
    mcq: {
      options: ["Khi nào?", "Ở đâu?", "Vì sao?", "Bằng cách nào?"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"Tối qua\" chỉ thời điểm, trả lời câu hỏi \"Khi nào?\".",
        "\"Tối qua\" không chỉ nơi chốn.",
        "\"Tối qua\" không nêu nguyên nhân.",
        "\"Tối qua\" không nêu cách thức.",
      ],
    },
  },
  {
    id: "ca-02-mcq-6",
    topicIds: ["CA-02"],
    level: "M2",
    questionType: "mcq",
    prompt: "Trạng ngữ có vai trò gì trong câu?",
    explanation: "Trạng ngữ bổ sung ý nghĩa về thời gian, nơi chốn, nguyên nhân, mục đích, cách thức... cho câu, không phải thành phần chính.",
    mcq: {
      options: [
        "Là thành phần chính, bắt buộc phải có trong mọi câu",
        "Bổ sung ý nghĩa về thời gian, nơi chốn, nguyên nhân... cho câu",
        "Thay thế cho chủ ngữ khi câu không có chủ ngữ",
        "Luôn đứng ở cuối câu",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Trạng ngữ là thành phần phụ, không bắt buộc phải có trong câu (khác chủ ngữ, vị ngữ).",
        "Đúng — trạng ngữ bổ sung ý nghĩa hoàn cảnh cho câu.",
        "Trạng ngữ không có chức năng thay thế chủ ngữ.",
        "Trạng ngữ có thể đứng ở đầu câu, giữa câu hoặc cuối câu, không cố định.",
      ],
    },
  },
  {
    id: "ca-02-fill-2",
    topicIds: ["CA-02"],
    level: "M1",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Trong câu "Ở trường, em học rất nhiều điều bổ ích.", trạng ngữ là ___.',
    explanation: "\"Ở trường\" là trạng ngữ chỉ nơi chốn.",
    fill: { acceptedAnswers: ["Ở trường", "ở trường"], strictMode: false, isSet: false },
  },
  {
    id: "ca-02-mcq-7",
    topicIds: ["CA-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu nào dưới đây có trạng ngữ chỉ nguyên nhân?',
    explanation: "\"Vì chăm chỉ luyện tập\" nêu lý do đạt giải, trả lời câu hỏi \"Vì sao?\".",
    mcq: {
      options: [
        "Vì chăm chỉ luyện tập, bạn ấy đã đạt giải nhất.",
        "Trong lớp học, các bạn đang làm bài kiểm tra.",
        "Chiều nay, em sẽ đi đá bóng cùng bạn.",
        "Để cây mau lớn, em tưới nước mỗi ngày.",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"Vì chăm chỉ luyện tập\" nêu nguyên nhân đạt giải.",
        "Đây là trạng ngữ chỉ nơi chốn.",
        "Đây là trạng ngữ chỉ thời gian.",
        "Đây là trạng ngữ chỉ mục đích.",
      ],
    },
  },
  {
    id: "ca-02-match-1",
    topicIds: ["CA-02"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi trạng ngữ ở cột trái với loại trạng ngữ đúng ở cột phải.",
    explanation: "\"Vì trời lạnh\" — nguyên nhân; \"Trong vườn\" — nơi chốn; \"Để rèn luyện sức khoẻ\" — mục đích.",
    match: {
      leftItems: [
        { id: "l1", label: "Vì trời lạnh" },
        { id: "l2", label: "Trong vườn" },
        { id: "l3", label: "Để rèn luyện sức khoẻ" },
      ],
      rightItems: [
        { id: "r1", label: "Trạng ngữ chỉ mục đích" },
        { id: "r2", label: "Trạng ngữ chỉ nguyên nhân" },
        { id: "r3", label: "Trạng ngữ chỉ nơi chốn" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r3" },
        { leftId: "l3", rightId: "r1" },
      ],
    },
  },
  {
    id: "ca-02-mcq-8",
    topicIds: ["CA-02"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Trong câu "Với sự cố gắng không ngừng, cuối cùng em cũng vượt qua kỳ thi.", trạng ngữ "Với sự cố gắng không ngừng" gần nhất với loại trạng ngữ nào?',
    explanation: "\"Với sự cố gắng không ngừng\" nêu cách thức, phương tiện tinh thần giúp đạt được kết quả — gần với trạng ngữ chỉ phương tiện/cách thức.",
    mcq: {
      options: ["Trạng ngữ chỉ phương tiện/cách thức", "Trạng ngữ chỉ nơi chốn", "Trạng ngữ chỉ thời gian", "Trạng ngữ chỉ mục đích"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — trạng ngữ này nêu cách thức đạt được kết quả.",
        "Không có ý nghĩa nơi chốn nào ở đây.",
        "Không có ý nghĩa thời gian nào ở đây.",
        "Không nêu mục đích, mà nêu cách thức đạt được điều đã nói.",
      ],
    },
  },
  {
    id: "ca-02-fill-3",
    topicIds: ["CA-02"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Trong câu "Ngày mai, lớp em sẽ đi tham quan bảo tàng.", trạng ngữ "Ngày mai" trả lời cho câu hỏi ___?',
    explanation: "\"Ngày mai\" chỉ thời điểm, trả lời câu hỏi \"Khi nào?\".",
    fill: { acceptedAnswers: ["Khi nào", "khi nào"], strictMode: false, isSet: false },
  },
];
