import type { Exercise } from "@/data-access/types";

// CA-05 — Câu đơn và câu ghép. Câu ví dụ tự biên soạn (Mục 10.1 hướng B).
export const CA05_EXERCISES: Exercise[] = [
  {
    id: "ca-05-mcq-1",
    topicIds: ["CA-05"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Câu "Em học bài." là câu đơn hay câu ghép?',
    explanation: "Câu chỉ có một cụm chủ ngữ – vị ngữ (\"Em\" / \"học bài\") nên là câu đơn.",
    mcq: {
      options: ["Câu đơn", "Câu ghép", "Không xác định được", "Cả hai đều đúng"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — câu chỉ có một cụm chủ ngữ – vị ngữ.",
        "Câu ghép cần có từ hai cụm chủ ngữ – vị ngữ trở lên, câu này chỉ có một.",
        "Có thể xác định được dựa vào số cụm chủ ngữ – vị ngữ.",
        "Một câu chỉ có thể là câu đơn hoặc câu ghép, không thể là cả hai.",
      ],
    },
  },
  {
    id: "ca-05-mcq-2",
    topicIds: ["CA-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Trời mưa to nên đường phố ngập nước." là câu đơn hay câu ghép?',
    explanation: "Câu có hai cụm chủ ngữ – vị ngữ (\"trời mưa to\" và \"đường phố ngập nước\"), nối bằng \"nên\" — đây là câu ghép.",
    mcq: {
      options: ["Câu đơn", "Câu ghép", "Câu thiếu chủ ngữ", "Câu thiếu vị ngữ"],
      answerIndex: 1,
      distractorNotes: [
        "Câu có hai cụm chủ ngữ – vị ngữ, không phải câu đơn.",
        "Đúng — hai cụm chủ ngữ – vị ngữ được nối với nhau bằng \"nên\".",
        "Câu có đủ chủ ngữ ở cả hai vế.",
        "Câu có đủ vị ngữ ở cả hai vế.",
      ],
    },
  },
  {
    id: "ca-05-fill-1",
    topicIds: ["CA-05"],
    level: "M2",
    questionType: "fill",
    prompt:
      "Điền từ còn thiếu: Câu ghép có từ hai cụm chủ ngữ – vị ngữ trở lên, các cụm không ___ nhau.",
    explanation: "Các cụm chủ ngữ – vị ngữ trong câu ghép không bao chứa nhau (khác với câu đơn có thành phần mở rộng).",
    fill: { acceptedAnswers: ["bao chứa"], strictMode: false, isSet: false },
  },
  {
    id: "ca-05-mcq-3",
    topicIds: ["CA-05"],
    level: "M1",
    questionType: "mcq",
    prompt: "Câu đơn có mấy cụm chủ ngữ – vị ngữ?",
    explanation: "Câu đơn chỉ có một cụm chủ ngữ – vị ngữ.",
    mcq: {
      options: ["Chỉ 1 cụm", "Đúng 2 cụm", "Từ 2 cụm trở lên", "Không có cụm nào"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — câu đơn chỉ có một cụm chủ ngữ – vị ngữ.",
        "Đây là đặc điểm của câu ghép có 2 vế.",
        "Đây là đặc điểm của câu ghép nói chung.",
        "Câu đơn vẫn phải có ít nhất một cụm chủ ngữ – vị ngữ.",
      ],
    },
  },
  {
    id: "ca-05-mcq-4",
    topicIds: ["CA-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Lan học giỏi Toán còn Hùng học giỏi Văn." là câu đơn hay câu ghép?',
    explanation: "Câu có hai cụm chủ ngữ – vị ngữ (\"Lan học giỏi Toán\" và \"Hùng học giỏi Văn\") nối bằng \"còn\" — là câu ghép.",
    mcq: {
      options: ["Câu đơn", "Câu ghép", "Câu đặc biệt", "Không xác định được"],
      answerIndex: 1,
      distractorNotes: [
        "Câu có hai cụm chủ ngữ – vị ngữ, không phải câu đơn.",
        "Đúng — hai cụm chủ ngữ – vị ngữ được nối bằng \"còn\".",
        "Đây là câu ghép bình thường, không phải câu đặc biệt.",
        "Có thể xác định rõ dựa vào số cụm chủ ngữ – vị ngữ.",
      ],
    },
  },
  {
    id: "ca-05-mcq-5",
    topicIds: ["CA-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu nào dưới đây là câu đơn có thành phần mở rộng (nhiều chủ ngữ hoặc vị ngữ nhưng vẫn là MỘT cụm)?',
    explanation: "\"Lan và Hùng cùng đi học.\" tuy có hai chủ ngữ (Lan, Hùng) nhưng chung một vị ngữ \"cùng đi học\" — vẫn là câu đơn có chủ ngữ mở rộng.",
    mcq: {
      options: [
        "Lan và Hùng cùng đi học.",
        "Trời mưa nên em ở nhà.",
        "Vì bận việc nên bố về muộn.",
        "Em học bài còn mẹ nấu cơm.",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"Lan\" và \"Hùng\" cùng chung một vị ngữ, vẫn là một cụm chủ ngữ – vị ngữ (câu đơn).",
        "Đây là câu ghép có hai cụm chủ ngữ – vị ngữ riêng biệt.",
        "Đây là câu ghép có hai cụm chủ ngữ – vị ngữ riêng biệt.",
        "Đây là câu ghép có hai cụm chủ ngữ – vị ngữ riêng biệt.",
      ],
    },
  },
  {
    id: "ca-05-mcq-6",
    topicIds: ["CA-05"],
    level: "M1",
    questionType: "mcq",
    prompt: "Để phân biệt câu đơn và câu ghép, ta cần dựa vào yếu tố nào?",
    explanation: "Cần đếm số cụm chủ ngữ – vị ngữ riêng biệt (không bao chứa nhau) trong câu.",
    mcq: {
      options: [
        "Độ dài của câu",
        "Số cụm chủ ngữ – vị ngữ riêng biệt trong câu",
        "Số dấu phẩy trong câu",
        "Câu có dấu chấm than hay không",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Câu dài hay ngắn không quyết định câu đơn hay ghép.",
        "Đúng — đây là tiêu chí chính xác để phân biệt.",
        "Số dấu phẩy không phải tiêu chí đáng tin cậy (câu đơn vẫn có thể có dấu phẩy).",
        "Loại dấu câu cuối câu không liên quan đến việc câu là đơn hay ghép.",
      ],
    },
  },
  {
    id: "ca-05-fill-2",
    topicIds: ["CA-05"],
    level: "M1",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Câu "Em đi học." là câu ___.',
    explanation: "Câu chỉ có một cụm chủ ngữ – vị ngữ nên là câu đơn.",
    fill: { acceptedAnswers: ["đơn", "câu đơn"], strictMode: false, isSet: false },
  },
  {
    id: "ca-05-mcq-7",
    topicIds: ["CA-05"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Câu "Mặt trời lặn, bầu trời chuyển dần sang màu tím." có mấy cụm chủ ngữ – vị ngữ?',
    explanation: "Câu có hai cụm: \"Mặt trời lặn\" và \"bầu trời chuyển dần sang màu tím\", ngăn cách bằng dấu phẩy (không dùng quan hệ từ) — vẫn là câu ghép.",
    mcq: {
      options: ["1 cụm", "2 cụm", "3 cụm", "Không có cụm nào"],
      answerIndex: 1,
      distractorNotes: [
        "Câu có 2 cụm chủ ngữ – vị ngữ, không phải 1.",
        "Đúng — có 2 cụm: \"Mặt trời lặn\" và \"bầu trời chuyển dần sang màu tím\".",
        "Câu chỉ có 2 cụm, không phải 3.",
        "Câu vẫn có đủ chủ ngữ, vị ngữ ở cả hai vế.",
      ],
    },
  },
  {
    id: "ca-05-match-1",
    topicIds: ["CA-05"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi câu ở cột trái với đúng loại câu ở cột phải.",
    explanation: "\"Em học bài.\" — câu đơn; \"Trời mưa nên em ở nhà.\" — câu ghép; \"Lan và Hoa cùng chơi nhảy dây.\" — câu đơn (chủ ngữ mở rộng).",
    match: {
      leftItems: [
        { id: "l1", label: "Em học bài." },
        { id: "l2", label: "Trời mưa nên em ở nhà." },
        { id: "l3", label: "Lan và Hoa cùng chơi nhảy dây." },
      ],
      rightItems: [
        { id: "r1", label: "Câu đơn" },
        { id: "r2", label: "Câu ghép" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r1" },
        { leftId: "l2", rightId: "r2" },
        { leftId: "l3", rightId: "r1" },
      ],
    },
  },
  {
    id: "ca-05-mcq-8",
    topicIds: ["CA-05"],
    level: "M2",
    questionType: "mcq",
    prompt: "Các vế trong câu ghép có thể được nối với nhau bằng cách nào?",
    explanation: "Các vế câu ghép có thể nối trực tiếp bằng dấu phẩy hoặc nối bằng quan hệ từ/cặp quan hệ từ.",
    mcq: {
      options: [
        "Chỉ nối bằng dấu phẩy",
        "Chỉ nối bằng quan hệ từ",
        "Nối bằng dấu phẩy hoặc quan hệ từ/cặp quan hệ từ",
        "Không thể nối được, phải viết thành các câu riêng",
      ],
      answerIndex: 2,
      distractorNotes: [
        "Các vế còn có thể nối bằng quan hệ từ.",
        "Các vế còn có thể nối trực tiếp bằng dấu phẩy, không nhất thiết cần quan hệ từ.",
        "Đúng — có hai cách nối chính: trực tiếp (dấu phẩy) hoặc bằng quan hệ từ.",
        "Câu ghép chính là cách nối các vế câu vào chung một câu.",
      ],
    },
  },
  {
    id: "ca-05-mcq-9",
    topicIds: ["CA-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Gió thổi mạnh, cây cối nghiêng ngả." là câu đơn hay câu ghép?',
    explanation: "Câu có hai cụm chủ ngữ – vị ngữ (\"gió thổi mạnh\" và \"cây cối nghiêng ngả\"), nối trực tiếp bằng dấu phẩy — là câu ghép.",
    mcq: {
      options: ["Câu đơn", "Câu ghép", "Câu thiếu chủ ngữ", "Câu thiếu vị ngữ"],
      answerIndex: 1,
      distractorNotes: [
        "Câu có hai cụm chủ ngữ – vị ngữ, không phải câu đơn.",
        "Đúng — hai cụm được nối trực tiếp bằng dấu phẩy, không cần quan hệ từ.",
        "Cả hai vế đều có chủ ngữ đầy đủ.",
        "Cả hai vế đều có vị ngữ đầy đủ.",
      ],
    },
  },
];
