import type { Exercise } from "@/data-access/types";

// CA-08 — Chữa lỗi câu. `[BỔ SUNG]`. Câu tự biên soạn (Mục 10.1 hướng B).
export const CA08_EXERCISES: Exercise[] = [
  {
    id: "ca-08-mcq-1",
    topicIds: ["CA-08"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Qua bài văn cho thấy bạn Nam là người chăm chỉ." mắc lỗi gì?',
    explanation: "\"Qua bài văn\" chỉ là trạng ngữ, câu này thiếu chủ ngữ (ai \"cho thấy\"?).",
    mcq: {
      options: ["Thiếu chủ ngữ", "Thiếu vị ngữ", "Lặp từ", "Câu này đúng, không mắc lỗi"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"qua bài văn\" là trạng ngữ, câu thiếu chủ ngữ đứng sau trạng ngữ.",
        "Câu có vị ngữ \"cho thấy bạn Nam là người chăm chỉ\", không thiếu vị ngữ.",
        "Câu này không có từ nào bị lặp lại.",
        "Câu này thiếu chủ ngữ, cần sửa lại.",
      ],
    },
  },
  {
    id: "ca-08-mcq-2",
    topicIds: ["CA-08"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu nào dưới đây đã được sửa ĐÚNG từ câu sai "Qua bài văn cho thấy bạn Nam là người chăm chỉ."?',
    explanation: "Thêm chủ ngữ \"em\" vào sau trạng ngữ \"qua bài văn\" giúp câu có đủ chủ ngữ, vị ngữ.",
    mcq: {
      options: [
        "Qua bài văn cho thấy bạn Nam là người chăm chỉ.",
        "Qua bài văn, em thấy bạn Nam là người chăm chỉ.",
        "Bài văn cho thấy cho thấy bạn Nam chăm chỉ.",
        "Bạn Nam.",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Đây chính là câu sai ban đầu, chưa được sửa.",
        "Đúng — thêm chủ ngữ \"em\" sau trạng ngữ giúp câu đủ thành phần.",
        "Câu này bị lặp từ \"cho thấy\" hai lần, vẫn còn lỗi.",
        "Câu này quá ngắn, không diễn đạt đủ ý.",
      ],
    },
  },
  {
    id: "ca-08-mcq-3",
    topicIds: ["CA-08"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Vì bạn ấy chăm chỉ nên bạn ấy chăm chỉ nên đạt điểm cao." mắc lỗi gì?',
    explanation: "Cụm \"bạn ấy chăm chỉ nên\" bị lặp lại không cần thiết, khiến câu rườm rà.",
    mcq: {
      options: ["Thiếu chủ ngữ", "Sai quan hệ từ", "Lặp từ không cần thiết", "Thiếu vị ngữ"],
      answerIndex: 2,
      distractorNotes: [
        "Câu này có đủ chủ ngữ \"bạn ấy\".",
        "Cặp quan hệ từ \"vì...nên\" dùng đúng, chỉ là bị lặp lại một lần không cần thiết.",
        "Đúng — cụm \"bạn ấy chăm chỉ nên\" bị lặp lại, cần bỏ bớt.",
        "Câu này có đủ vị ngữ.",
      ],
    },
  },
  {
    id: "ca-08-fill-1",
    topicIds: ["CA-08"],
    level: "M2",
    questionType: "fill",
    prompt: "Điền từ còn thiếu: Một câu đúng ngữ pháp cần có đủ ___ và vị ngữ.",
    explanation: "Câu đúng ngữ pháp cần có đủ chủ ngữ và vị ngữ.",
    fill: { acceptedAnswers: ["chủ ngữ"], strictMode: false, isSet: false },
  },
  {
    id: "ca-08-mcq-4",
    topicIds: ["CA-08"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Bạn Lan tuy học giỏi nhưng bạn ấy còn hát rất hay." mắc lỗi gì về quan hệ từ?',
    explanation: "Cặp \"tuy...nhưng\" thể hiện quan hệ tương phản, nhưng nội dung hai vế (học giỏi, hát hay) đều là ưu điểm, không đối lập nhau — dùng sai quan hệ từ.",
    mcq: {
      options: [
        "Thiếu chủ ngữ",
        "Dùng sai cặp quan hệ từ (hai vế không mang ý tương phản)",
        "Lặp từ không cần thiết",
        "Câu này đúng, không mắc lỗi",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Câu có đủ chủ ngữ ở cả hai vế.",
        "Đúng — hai vế đều là ưu điểm (học giỏi, hát hay), không đối lập, nên dùng \"tuy...nhưng\" là sai; nên dùng \"không những...mà còn\".",
        "Câu này không có từ nào lặp lại không cần thiết.",
        "Câu này dùng sai quan hệ từ, cần sửa lại.",
      ],
    },
  },
  {
    id: "ca-08-mcq-5",
    topicIds: ["CA-08"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Câu nào dưới đây đã sửa ĐÚNG câu sai "Bạn Lan tuy học giỏi nhưng bạn ấy còn hát rất hay."?',
    explanation: "Vì hai vế đều là ưu điểm, bổ sung cho nhau (không đối lập), nên dùng cặp \"không những...mà còn\" mới đúng quan hệ ý nghĩa.",
    mcq: {
      options: [
        "Bạn Lan tuy học giỏi nhưng bạn ấy còn hát rất hay.",
        "Bạn Lan không những học giỏi mà còn hát rất hay.",
        "Bạn Lan học giỏi nhưng hát rất hay nhưng.",
        "Lan.",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Đây là câu sai ban đầu, chưa được sửa.",
        "Đúng — \"không những...mà còn\" phù hợp với quan hệ tăng tiến giữa hai ưu điểm.",
        "Câu này lặp từ \"nhưng\" một cách vô nghĩa, sai ngữ pháp.",
        "Câu này quá ngắn, không diễn đạt đủ ý ban đầu.",
      ],
    },
  },
  {
    id: "ca-08-mcq-6",
    topicIds: ["CA-08"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Bằng đôi bàn tay của mình đã tạo nên sản phẩm này." mắc lỗi gì?',
    explanation: "\"Bằng đôi bàn tay của mình\" là trạng ngữ, câu thiếu chủ ngữ đứng sau trạng ngữ (ai đã tạo nên sản phẩm?).",
    mcq: {
      options: ["Thiếu chủ ngữ", "Thiếu vị ngữ", "Lặp từ", "Sai quan hệ từ"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — thiếu chủ ngữ đứng sau trạng ngữ \"bằng đôi bàn tay của mình\".",
        "Câu có vị ngữ \"đã tạo nên sản phẩm này\".",
        "Câu này không có từ lặp lại.",
        "Câu này không dùng quan hệ từ nào để so sánh.",
      ],
    },
  },
  {
    id: "ca-08-mcq-7",
    topicIds: ["CA-08"],
    level: "M2",
    questionType: "mcq",
    prompt: "Trước khi nộp bài, vì sao cần đọc lại và chữa lỗi câu?",
    explanation: "Đọc lại giúp phát hiện câu thiếu thành phần, sai quan hệ từ, lặp từ, diễn đạt lủng củng — những lỗi dễ mắc khi viết vội mà không tự nhận ra ngay lúc viết.",
    mcq: {
      options: [
        "Để bài viết dài hơn",
        "Để phát hiện và sửa các lỗi câu (thiếu thành phần, sai quan hệ từ, lặp từ...) trước khi nộp",
        "Để thay đổi hoàn toàn nội dung bài viết",
        "Không cần thiết, chỉ cần viết một lần là đủ",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Đọc lại không nhằm mục đích kéo dài bài viết.",
        "Đúng — đây chính là mục đích của việc đọc lại, soát lỗi câu (liên hệ KN-05).",
        "Đọc lại để sửa lỗi diễn đạt, không phải thay đổi hoàn toàn nội dung.",
        "Viết vội một lần dễ mắc các lỗi câu mà không tự nhận ra ngay.",
      ],
    },
  },
  {
    id: "ca-08-fill-2",
    topicIds: ["CA-08"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Câu "Trạng ngữ không thể làm ___ của câu." — cần thêm chủ ngữ riêng phía sau trạng ngữ.',
    explanation: "Trạng ngữ chỉ là thành phần phụ, không thể thay thế vai trò của chủ ngữ trong câu.",
    fill: { acceptedAnswers: ["chủ ngữ"], strictMode: false, isSet: false },
  },
  {
    id: "ca-08-mcq-8",
    topicIds: ["CA-08"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Câu "Em rất thích đọc truyện cổ tích, truyện cổ tích giúp em hiểu thêm nhiều bài học hay." nên được chữa như thế nào cho gọn hơn?',
    explanation: "Có thể thay cụm \"truyện cổ tích\" lặp lại ở vế sau bằng đại từ \"chúng\" hoặc \"những câu chuyện ấy\" để tránh lặp từ không cần thiết.",
    mcq: {
      options: [
        "Giữ nguyên câu vì không có lỗi gì",
        "Thay \"truyện cổ tích\" ở vế sau bằng đại từ (VD \"chúng\") để tránh lặp từ",
        "Xoá bỏ hoàn toàn vế sau của câu",
        "Đổi toàn bộ câu thành câu hỏi",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Câu bị lặp từ \"truyện cổ tích\" một cách không cần thiết, nên chữa lại.",
        "Đúng — dùng phép thế (đại từ) giúp câu gọn hơn mà vẫn đủ ý (liên hệ CA-07).",
        "Xoá vế sau sẽ làm mất một phần nội dung quan trọng của câu.",
        "Đổi thành câu hỏi không giải quyết được lỗi lặp từ.",
      ],
    },
  },
  {
    id: "ca-08-mcq-9",
    topicIds: ["CA-08"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Nhờ chăm chỉ tập luyện nên đội bóng lớp em nên đã giành chức vô địch." mắc lỗi gì?',
    explanation: "Từ \"nên\" bị lặp lại hai lần liền nhau một cách không cần thiết.",
    mcq: {
      options: ["Thiếu chủ ngữ", "Thiếu vị ngữ", "Lặp từ \"nên\" không cần thiết", "Câu này đúng, không mắc lỗi"],
      answerIndex: 2,
      distractorNotes: [
        "Câu có đủ chủ ngữ \"đội bóng lớp em\".",
        "Câu có đủ vị ngữ \"đã giành chức vô địch\".",
        "Đúng — từ \"nên\" xuất hiện hai lần liền nhau, cần bỏ bớt một từ.",
        "Câu này có lỗi lặp từ, cần sửa lại.",
      ],
    },
  },
  {
    id: "ca-08-fill-3",
    topicIds: ["CA-08"],
    level: "M2",
    questionType: "fill",
    prompt: "Điền từ còn thiếu: Sau khi viết xong, cần đọc lại để phát hiện và ___ các lỗi câu trước khi nộp bài.",
    explanation: "Cần đọc lại để phát hiện và sửa các lỗi câu trước khi nộp bài (liên hệ KN-05).",
    fill: { acceptedAnswers: ["sửa"], strictMode: false, isSet: false },
  },
];
