import type { Exercise } from "@/data-access/types";

// CA-06 — Cách nối các vế câu ghép. Câu ví dụ tự biên soạn (Mục 10.1 hướng B).
export const CA06_EXERCISES: Exercise[] = [
  {
    id: "ca-06-mcq-1",
    topicIds: ["CA-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Cặp quan hệ từ "Vì...nên..." thể hiện mối quan hệ gì giữa hai vế câu ghép?',
    explanation: "Cặp quan hệ từ \"vì...nên\" thể hiện quan hệ nguyên nhân – kết quả.",
    mcq: {
      options: ["Nguyên nhân – kết quả", "Tương phản", "Giả thiết – kết quả", "Tăng tiến"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"vì\" nêu nguyên nhân, \"nên\" nêu kết quả.",
        "Quan hệ tương phản dùng cặp \"tuy...nhưng\".",
        "Quan hệ giả thiết – kết quả dùng cặp \"nếu...thì\".",
        "Quan hệ tăng tiến dùng cặp \"không những...mà còn\".",
      ],
    },
  },
  {
    id: "ca-06-mcq-2",
    topicIds: ["CA-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Tuy nhà nghèo nhưng bạn ấy học rất giỏi." thể hiện mối quan hệ gì giữa hai vế?',
    explanation: "Cặp quan hệ từ \"tuy...nhưng\" thể hiện quan hệ tương phản giữa hai vế câu.",
    mcq: {
      options: ["Nguyên nhân – kết quả", "Tương phản", "Giả thiết – kết quả", "Đồng thời"],
      answerIndex: 1,
      distractorNotes: [
        "Quan hệ nguyên nhân – kết quả dùng cặp \"vì...nên\".",
        "Đúng — \"tuy...nhưng\" thể hiện sự đối lập, tương phản giữa hai vế.",
        "Quan hệ giả thiết – kết quả dùng cặp \"nếu...thì\".",
        "Hai vế câu không diễn ra đồng thời mà mang tính đối lập.",
      ],
    },
  },
  {
    id: "ca-06-fill-1",
    topicIds: ["CA-06"],
    level: "M1",
    questionType: "fill",
    prompt: "Điền từ còn thiếu: Cặp quan hệ từ \"Nếu...thì...\" thể hiện quan hệ giả thiết – ___.",
    explanation: "Cặp quan hệ từ \"nếu...thì\" thể hiện quan hệ giả thiết – kết quả.",
    fill: { acceptedAnswers: ["kết quả"], strictMode: false, isSet: false },
  },
  {
    id: "ca-06-mcq-3",
    topicIds: ["CA-06"],
    level: "M1",
    questionType: "mcq",
    prompt: "Ngoài dùng cặp quan hệ từ, các vế câu ghép còn có thể nối với nhau bằng cách nào?",
    explanation: "Các vế câu ghép có thể nối trực tiếp với nhau bằng dấu phẩy, dấu chấm phẩy, không cần quan hệ từ.",
    mcq: {
      options: [
        "Nối trực tiếp bằng dấu câu (dấu phẩy, dấu chấm phẩy)",
        "Không có cách nào khác",
        "Chỉ có thể nối bằng từ \"và\"",
        "Chỉ có thể viết thành hai câu riêng biệt",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — có thể nối trực tiếp bằng dấu câu, không cần từ nối.",
        "Vẫn còn cách nối trực tiếp bằng dấu câu.",
        "\"Và\" chỉ là một trong nhiều quan hệ từ có thể dùng, không phải cách duy nhất.",
        "Câu ghép chính là việc nối các vế vào chung một câu, không phải viết riêng.",
      ],
    },
  },
  {
    id: "ca-06-mcq-4",
    topicIds: ["CA-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Cặp quan hệ từ nào phù hợp để điền vào câu: "___ em chăm chỉ học tập, ___ em sẽ đạt kết quả tốt."?',
    explanation: "Đây là quan hệ giả thiết – kết quả, phù hợp với cặp \"nếu...thì\".",
    mcq: {
      options: ["Vì...nên", "Tuy...nhưng", "Nếu...thì", "Không những...mà còn"],
      answerIndex: 2,
      distractorNotes: [
        "\"Vì...nên\" dùng cho quan hệ nguyên nhân đã xảy ra, không phù hợp với ý giả thiết \"nếu... thì...\".",
        "\"Tuy...nhưng\" dùng cho quan hệ tương phản, không phù hợp.",
        "Đúng — \"nếu...thì\" phù hợp với quan hệ giả thiết – kết quả.",
        "\"Không những...mà còn\" dùng cho quan hệ tăng tiến, không phù hợp.",
      ],
    },
  },
  {
    id: "ca-06-mcq-5",
    topicIds: ["CA-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Cặp quan hệ từ "Không những...mà còn..." thể hiện quan hệ gì?',
    explanation: "Cặp \"không những...mà còn\" thể hiện quan hệ tăng tiến (vế sau bổ sung, nâng cao ý của vế trước).",
    mcq: {
      options: ["Nguyên nhân – kết quả", "Tương phản", "Giả thiết – kết quả", "Tăng tiến"],
      answerIndex: 3,
      distractorNotes: [
        "Đây không phải quan hệ nguyên nhân – kết quả.",
        "Đây không phải quan hệ tương phản, hai vế đều mang ý khẳng định, bổ sung cho nhau.",
        "Đây không phải quan hệ giả thiết.",
        "Đúng — cặp này thể hiện quan hệ tăng tiến.",
      ],
    },
  },
  {
    id: "ca-06-mcq-6",
    topicIds: ["CA-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Bạn ấy không những học giỏi mà còn hát hay." dùng cặp quan hệ từ nào?',
    explanation: "Câu dùng cặp \"không những...mà còn\" để thể hiện quan hệ tăng tiến.",
    mcq: {
      options: ["Vì...nên", "Không những...mà còn", "Nếu...thì", "Tuy...nhưng"],
      answerIndex: 1,
      distractorNotes: [
        "Câu không dùng cặp này.",
        "Đúng — đây chính là cặp quan hệ từ được dùng trong câu.",
        "Câu không dùng cặp này.",
        "Câu không dùng cặp này.",
      ],
    },
  },
  {
    id: "ca-06-fill-2",
    topicIds: ["CA-06"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền quan hệ từ còn thiếu (chỉ điền vế đầu): "___ trời mưa to, đường sá bị ngập nước." (quan hệ nguyên nhân)',
    explanation: "\"Vì\" mở đầu cho vế nêu nguyên nhân, kết hợp với \"nên\" ở vế sau (có thể có hoặc lược bớt \"nên\").",
    fill: { acceptedAnswers: ["Vì", "vì"], strictMode: false, isSet: false },
  },
  {
    id: "ca-06-mcq-7",
    topicIds: ["CA-06"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Câu "Trời càng mưa to, nước sông càng dâng cao." dùng cặp từ hô ứng nào để nối hai vế?',
    explanation: "Cặp \"càng...càng\" là cặp từ hô ứng, thể hiện mức độ tăng dần song song giữa hai vế.",
    mcq: {
      options: ["Vì...nên", "Càng...càng", "Tuy...nhưng", "Nếu...thì"],
      answerIndex: 1,
      distractorNotes: [
        "Câu không dùng cặp quan hệ từ nguyên nhân – kết quả này.",
        "Đúng — \"càng...càng\" là cặp từ hô ứng nối hai vế câu ghép, thể hiện mức độ tăng dần song song.",
        "Câu không mang ý tương phản.",
        "Câu không mang ý giả thiết.",
      ],
    },
  },
  {
    id: "ca-06-match-1",
    topicIds: ["CA-06"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi cặp quan hệ từ ở cột trái với đúng quan hệ ý nghĩa ở cột phải.",
    explanation: "\"Vì...nên\" — nguyên nhân/kết quả; \"Tuy...nhưng\" — tương phản; \"Nếu...thì\" — giả thiết/kết quả.",
    match: {
      leftItems: [
        { id: "l1", label: "Vì...nên" },
        { id: "l2", label: "Tuy...nhưng" },
        { id: "l3", label: "Nếu...thì" },
      ],
      rightItems: [
        { id: "r1", label: "Giả thiết – kết quả" },
        { id: "r2", label: "Nguyên nhân – kết quả" },
        { id: "r3", label: "Tương phản" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r3" },
        { leftId: "l3", rightId: "r1" },
      ],
    },
  },
  {
    id: "ca-06-mcq-8",
    topicIds: ["CA-06"],
    level: "M2",
    questionType: "mcq",
    prompt: "Khi dùng cặp quan hệ từ để nối hai vế câu ghép, cần lưu ý điều gì?",
    explanation: "Cần dùng đủ cả hai từ trong cặp quan hệ từ, và chọn đúng cặp phù hợp với quan hệ ý nghĩa giữa hai vế.",
    mcq: {
      options: [
        "Chỉ cần dùng một từ trong cặp là đủ",
        "Dùng đủ cả cặp và chọn đúng cặp phù hợp với quan hệ ý nghĩa giữa hai vế",
        "Có thể dùng bất kỳ cặp nào cũng được",
        "Không cần quan tâm đến quan hệ ý nghĩa giữa hai vế",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Thiếu một từ trong cặp có thể khiến câu không rõ nghĩa hoặc sai ngữ pháp.",
        "Đúng — cần dùng đủ cặp và chọn đúng loại quan hệ phù hợp.",
        "Mỗi cặp quan hệ từ chỉ phù hợp với một loại quan hệ ý nghĩa nhất định.",
        "Quan hệ ý nghĩa giữa hai vế quyết định việc chọn cặp quan hệ từ nào.",
      ],
    },
  },
  {
    id: "ca-06-mcq-9",
    topicIds: ["CA-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Cặp quan hệ từ nào phù hợp: "___ trời rét đậm, ___ các bạn học sinh vẫn đến trường đầy đủ."?',
    explanation: "Nội dung hai vế đối lập nhau (trời rét nhưng vẫn đến trường đầy đủ) — phù hợp với cặp \"tuy...nhưng\".",
    mcq: {
      options: ["Vì...nên", "Tuy...nhưng", "Nếu...thì", "Càng...càng"],
      answerIndex: 1,
      distractorNotes: [
        "Hai vế mang ý đối lập, không phải nguyên nhân – kết quả thuận chiều.",
        "Đúng — \"tuy...nhưng\" phù hợp với ý đối lập giữa trời rét và việc vẫn đến trường đầy đủ.",
        "Đây không phải câu giả thiết.",
        "Đây không phải quan hệ tăng tiến song song.",
      ],
    },
  },
];
