import type { Exercise } from "@/data-access/types";

// CD-02 — Chính tả: thanh hỏi và thanh ngã. FR-M05: mọi câu fill trong
// nhóm CD dùng strictMode. Câu tự biên soạn (Mục 10.1).
export const CD02_EXERCISES: Exercise[] = [
  {
    id: "cd-02-fill-1",
    topicIds: ["CD-02"],
    level: "M1",
    questionType: "fill",
    prompt:
      "Điền từ đúng chính tả vào chỗ trống (phân biệt hỏi/ngã): \"Sau giờ học, em ___ ngơi một lúc rồi mới làm bài tập.\"",
    explanation: "Viết đúng là \"nghỉ\" (thanh hỏi, nghĩa là dừng làm việc để thư giãn), không viết \"nghĩ\" (thanh ngã, nghĩa là suy nghĩ).",
    fill: { acceptedAnswers: ["nghỉ"], strictMode: true, isSet: false },
  },
  {
    id: "cd-02-fill-2",
    topicIds: ["CD-02"],
    level: "M1",
    questionType: "fill",
    prompt:
      "Điền từ đúng chính tả vào chỗ trống (phân biệt hỏi/ngã): \"Bạn Nam đang ___ về bài toán khó.\"",
    explanation: "Viết đúng là \"suy nghĩ\" (thanh ngã, nghĩa là dùng trí óc để hiểu, đánh giá).",
    fill: { acceptedAnswers: ["suy nghĩ"], strictMode: true, isSet: false },
  },
  {
    id: "cd-02-mcq-1",
    topicIds: ["CD-02"],
    level: "M2",
    questionType: "mcq",
    prompt: "Từ nào dưới đây viết ĐÚNG chính tả?",
    explanation: "\"Sẵn sàng\" viết đúng: \"sẵn\" mang thanh ngã, \"sàng\" mang thanh huyền.",
    mcq: {
      options: ["Sẳn sàng", "Sẵn sàng", "Sẵn sàn", "Sẩn sàng"],
      answerIndex: 1,
      distractorNotes: [
        "Sai dấu ở tiếng \"sẳn\" (phải là \"sẵn\" — thanh ngã).",
        "Đúng — \"sẵn sàng\" viết đúng chính tả.",
        "Thiếu dấu ở tiếng \"sàn\" (phải là \"sàng\").",
        "Sai dấu ở tiếng \"sẩn\" (phải là \"sẵn\" — thanh ngã, không phải thanh hỏi).",
      ],
    },
  },
  {
    id: "cd-02-mcq-2",
    topicIds: ["CD-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu nào dưới đây dùng ĐÚNG từ "nghỉ"/"nghĩ"?',
    explanation: "\"Nghỉ hè\" dùng thanh hỏi vì nghĩa là dừng học để thư giãn — dùng đúng chính tả.",
    mcq: {
      options: [
        "Em đang nghĩ hè ở quê ngoại.",
        "Em đang nghỉ hè ở quê ngoại.",
        "Bạn Lan hay nghỉ trước khi trả lời câu hỏi khó.",
        "Cả hai câu đều sai chính tả.",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Sai — phải dùng \"nghỉ\" (thanh hỏi) vì đang nói về việc nghỉ ngơi, không phải suy nghĩ.",
        "Đúng — \"nghỉ hè\" dùng đúng thanh hỏi.",
        "Câu này nên dùng \"nghĩ\" (thanh ngã, suy nghĩ) vì đang nói về việc suy nghĩ trước khi trả lời.",
        "Câu thứ hai (\"Em đang nghỉ hè...\") viết đúng chính tả.",
      ],
    },
  },
  {
    id: "cd-02-fill-3",
    topicIds: ["CD-02"],
    level: "M2",
    questionType: "fill",
    prompt: "Điền từ đúng chính tả vào chỗ trống (phân biệt hỏi/ngã): \"Em ___ cửa sổ cho phòng thoáng khí.\"",
    explanation: "Viết đúng là \"mở\" (thanh hỏi, nghĩa là làm cho không còn đóng kín), không viết \"mỡ\" (thanh ngã, nghĩa là chất béo).",
    fill: { acceptedAnswers: ["mở"], strictMode: true, isSet: false },
  },
  {
    id: "cd-02-fill-4",
    topicIds: ["CD-02"],
    level: "M1",
    questionType: "fill",
    prompt: "Điền từ đúng chính tả vào chỗ trống (phân biệt hỏi/ngã): \"Em ___ tay chào tạm biệt bạn.\"",
    explanation: "Viết đúng là \"vẫy\" (thanh ngã).",
    fill: { acceptedAnswers: ["vẫy"], strictMode: true, isSet: false },
  },
  {
    id: "cd-02-mcq-3",
    topicIds: ["CD-02"],
    level: "M2",
    questionType: "mcq",
    prompt: "Từ nào dưới đây viết ĐÚNG chính tả?",
    explanation: "\"Rực rỡ\" viết đúng, với thanh ngã ở tiếng \"rỡ\".",
    mcq: {
      options: ["Rực rở", "Rực rỡ", "Rựt rỡ", "Rực rợ"],
      answerIndex: 1,
      distractorNotes: [
        "Sai dấu ở tiếng \"rở\" (phải là \"rỡ\" — thanh ngã).",
        "Đúng — \"rực rỡ\" viết đúng chính tả.",
        "Sai âm cuối ở tiếng \"rựt\" (phải là \"rực\").",
        "Sai dấu ở tiếng \"rợ\" (phải là \"rỡ\" — thanh ngã, không phải thanh nặng).",
      ],
    },
  },
  {
    id: "cd-02-mcq-4",
    topicIds: ["CD-02"],
    level: "M1",
    questionType: "mcq",
    prompt: "Thanh hỏi được viết bằng dấu gì?",
    explanation: "Thanh hỏi được viết bằng dấu hỏi (?) đặt trên chữ cái.",
    mcq: {
      options: ["Dấu hỏi (?)", "Dấu ngã (~)", "Dấu huyền (`)", "Dấu sắc (´)"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — thanh hỏi dùng dấu hỏi.",
        "Đây là dấu của thanh ngã.",
        "Đây là dấu của thanh huyền.",
        "Đây là dấu của thanh sắc.",
      ],
    },
  },
  {
    id: "cd-02-mcq-5",
    topicIds: ["CD-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây mang thanh ngã?',
    explanation: "\"Sữa\" mang thanh ngã (dấu ~). \"Sửa\", \"múa\", \"cửa\" đều mang thanh hỏi hoặc không dấu ngã.",
    mcq: {
      options: ["sửa (chữa)", "sữa (uống)", "múa", "cửa"],
      answerIndex: 1,
      distractorNotes: [
        "\"Sửa\" (sửa chữa) mang thanh hỏi, không phải thanh ngã.",
        "Đúng — \"sữa\" (để uống) mang thanh ngã.",
        "\"Múa\" mang thanh sắc.",
        "\"Cửa\" mang thanh hỏi.",
      ],
    },
  },
  {
    id: "cd-02-match-1",
    topicIds: ["CD-02"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi từ ở cột trái với đúng thanh điệu (hỏi/ngã) ở cột phải.",
    explanation: "\"Nghỉ\" (nghỉ ngơi) — thanh hỏi; \"nghĩ\" (suy nghĩ) — thanh ngã; \"sửa\" (sửa chữa) — thanh hỏi; \"sữa\" (đồ uống) — thanh ngã.",
    match: {
      leftItems: [
        { id: "l1", label: "nghỉ (ngơi)" },
        { id: "l2", label: "nghĩ (suy nghĩ)" },
        { id: "l3", label: "sữa (đồ uống)" },
      ],
      rightItems: [
        { id: "r1", label: "Thanh ngã" },
        { id: "r2", label: "Thanh hỏi" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r1" },
        { leftId: "l3", rightId: "r1" },
      ],
    },
  },
  {
    id: "cd-02-mcq-6",
    topicIds: ["CD-02"],
    level: "M2",
    questionType: "mcq",
    prompt: "Vì sao thanh hỏi và thanh ngã dễ bị viết sai?",
    explanation: "Ở nhiều vùng miền (đặc biệt miền Trung, miền Nam), người nói phát âm hai thanh này gần giống nhau, khiến khi viết dễ bị lẫn nếu không nhớ mặt chữ.",
    mcq: {
      options: [
        "Vì hai thanh này không tồn tại trong tiếng Việt chuẩn",
        "Vì nhiều vùng miền phát âm hai thanh này gần giống nhau",
        "Vì đây là hai thanh mới xuất hiện gần đây",
        "Vì hai thanh này chỉ dùng trong văn viết",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Cả hai thanh đều tồn tại và được công nhận trong tiếng Việt chuẩn.",
        "Đúng — đây là nguyên nhân chính gây nhầm lẫn khi viết.",
        "Đây là hai trong sáu thanh điệu cơ bản của tiếng Việt, không phải mới xuất hiện.",
        "Hai thanh này dùng trong cả văn nói và văn viết.",
      ],
    },
  },
  {
    id: "cd-02-fill-5",
    topicIds: ["CD-02"],
    level: "M2",
    questionType: "fill",
    prompt: "Điền từ đúng chính tả vào chỗ trống (phân biệt hỏi/ngã): \"Bạn ấy trả lời câu hỏi rất ___ ràng, dễ hiểu.\"",
    explanation: "Viết đúng là \"rõ\" (thanh ngã, nghĩa là dễ thấy, dễ nhận ra).",
    fill: { acceptedAnswers: ["rõ"], strictMode: true, isSet: false },
  },
];
