import type { Exercise } from "@/data-access/types";

// CD-05 — Dấu câu. Câu tự biên soạn (Mục 10.1).
export const CD05_EXERCISES: Exercise[] = [
  {
    id: "cd-05-mcq-1",
    topicIds: ["CD-05"],
    level: "M1",
    questionType: "mcq",
    prompt: "Dấu câu nào dùng để kết thúc một câu hỏi?",
    explanation: "Dấu chấm hỏi (?) dùng để kết thúc câu hỏi.",
    mcq: {
      options: ["Dấu chấm (.)", "Dấu phẩy (,)", "Dấu chấm hỏi (?)", "Dấu hai chấm (:)"],
      answerIndex: 2,
      distractorNotes: [
        "Dấu chấm dùng để kết thúc câu kể.",
        "Dấu phẩy dùng để ngăn cách các bộ phận trong câu, không kết thúc câu.",
        "Đúng — dấu chấm hỏi kết thúc câu hỏi.",
        "Dấu hai chấm dùng để báo hiệu lời dẫn hoặc phần liệt kê, không kết thúc câu.",
      ],
    },
  },
  {
    id: "cd-05-mcq-2",
    topicIds: ["CD-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Mẹ hỏi: \'Con đã làm bài tập chưa?\'", dấu hai chấm có tác dụng gì?',
    explanation: "Dấu hai chấm ở đây báo hiệu phần lời dẫn trực tiếp (lời mẹ hỏi) sắp xuất hiện.",
    mcq: {
      options: [
        "Báo hiệu phần lời dẫn trực tiếp sắp xuất hiện",
        "Kết thúc câu",
        "Ngăn cách hai vế câu ghép",
        "Thể hiện ý còn tiếp tục",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — dấu hai chấm báo hiệu lời dẫn trực tiếp phía sau.",
        "Dấu hai chấm không dùng để kết thúc câu.",
        "Đây không phải chức năng chính của dấu hai chấm trong câu này.",
        "Đây là chức năng của dấu chấm lửng, không phải dấu hai chấm.",
      ],
    },
  },
  {
    id: "cd-05-mcq-3",
    topicIds: ["CD-05"],
    level: "M2",
    questionType: "mcq",
    prompt: "Câu nào dưới đây dùng dấu chấm than PHÙ HỢP?",
    explanation: "\"Ôi, cảnh đẹp quá!\" là câu cảm thán, phù hợp dùng dấu chấm than. Câu kể bình thường không cần dấu chấm than.",
    mcq: {
      options: [
        "Hôm nay em đi học!",
        "Ôi, cảnh đẹp quá!",
        "Bạn tên là gì!",
        "Em ăn cơm rồi!",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Đây là câu kể bình thường, không mang sắc thái cảm thán, nên dùng dấu chấm là phù hợp hơn.",
        "Đúng — đây là câu cảm thán, thể hiện cảm xúc ngạc nhiên, thích thú, phù hợp dùng dấu chấm than.",
        "Đây là câu hỏi, nên dùng dấu chấm hỏi, không phải dấu chấm than.",
        "Đây là câu kể bình thường, không cần dấu chấm than.",
      ],
    },
  },
  {
    id: "cd-05-fill-1",
    topicIds: ["CD-05"],
    level: "M1",
    questionType: "fill",
    prompt: "Điền dấu câu còn thiếu vào cuối câu: \"Hôm nay trời đẹp quá___\" (câu cảm thán)",
    explanation: "Câu cảm thán kết thúc bằng dấu chấm than (!).",
    fill: { acceptedAnswers: ["!"], strictMode: true, isSet: false },
  },
  {
    id: "cd-05-mcq-4",
    topicIds: ["CD-05"],
    level: "M1",
    questionType: "mcq",
    prompt: "Dấu phẩy dùng để làm gì trong câu?",
    explanation: "Dấu phẩy dùng để ngăn cách các bộ phận cùng chức năng hoặc ngăn cách trạng ngữ với nòng cốt câu.",
    mcq: {
      options: [
        "Kết thúc câu kể",
        "Ngăn cách các bộ phận trong câu (VD: các từ liệt kê, trạng ngữ với nòng cốt câu)",
        "Kết thúc câu hỏi",
        "Báo hiệu lời dẫn trực tiếp",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Đây là chức năng của dấu chấm.",
        "Đúng — đây là chức năng chính của dấu phẩy.",
        "Đây là chức năng của dấu chấm hỏi.",
        "Đây là chức năng của dấu hai chấm.",
      ],
    },
  },
  {
    id: "cd-05-mcq-5",
    topicIds: ["CD-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Em thích ăn táo, cam, chuối và nho.", dấu phẩy có tác dụng gì?',
    explanation: "Dấu phẩy ở đây ngăn cách các từ cùng chức năng (liệt kê các loại quả).",
    mcq: {
      options: [
        "Ngăn cách các từ liệt kê cùng chức năng",
        "Ngăn cách hai câu riêng biệt",
        "Báo hiệu lời dẫn trực tiếp",
        "Kết thúc câu",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — dấu phẩy ngăn cách các từ liệt kê (táo, cam, chuối, nho).",
        "Đây vẫn là một câu, dấu phẩy không tách thành hai câu riêng.",
        "Đây không phải lời dẫn trực tiếp.",
        "Dấu phẩy không dùng để kết thúc câu.",
      ],
    },
  },
  {
    id: "cd-05-mcq-6",
    topicIds: ["CD-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Dấu ngoặc kép trong câu "Cô giáo nói: \\"Các em hãy giữ trật tự.\\"" dùng để làm gì?',
    explanation: "Dấu ngoặc kép đánh dấu lời nói trực tiếp được dẫn lại nguyên văn.",
    mcq: {
      options: [
        "Đánh dấu lời nói trực tiếp được dẫn lại nguyên văn",
        "Kết thúc câu",
        "Ngăn cách các từ liệt kê",
        "Thể hiện sự ngập ngừng",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — dấu ngoặc kép đánh dấu lời dẫn trực tiếp.",
        "Dấu ngoặc kép không dùng để kết thúc câu.",
        "Đây là chức năng của dấu phẩy.",
        "Đây là chức năng của dấu chấm lửng.",
      ],
    },
  },
  {
    id: "cd-05-mcq-7",
    topicIds: ["CD-05"],
    level: "M2",
    questionType: "mcq",
    prompt: "Dấu chấm lửng (...) thường dùng để thể hiện điều gì?",
    explanation: "Dấu chấm lửng thể hiện ý còn tiếp tục, chưa nói hết, hoặc sự ngập ngừng, bỏ lửng.",
    mcq: {
      options: [
        "Kết thúc câu kể một cách chắc chắn",
        "Ý còn tiếp tục, chưa nói hết, hoặc sự ngập ngừng",
        "Ngăn cách các từ liệt kê",
        "Đánh dấu lời dẫn trực tiếp",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Dấu chấm lửng không thể hiện sự chắc chắn, dứt khoát.",
        "Đúng — đây là chức năng chính của dấu chấm lửng.",
        "Đây là chức năng của dấu phẩy.",
        "Đây là chức năng của dấu ngoặc kép.",
      ],
    },
  },
  {
    id: "cd-05-fill-2",
    topicIds: ["CD-05"],
    level: "M1",
    questionType: "fill",
    prompt: "Điền dấu câu còn thiếu vào cuối câu: \"Bạn tên là gì___\" (câu hỏi)",
    explanation: "Câu hỏi kết thúc bằng dấu chấm hỏi (?).",
    fill: { acceptedAnswers: ["?"], strictMode: true, isSet: false },
  },
  {
    id: "cd-05-match-1",
    topicIds: ["CD-05"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi dấu câu ở cột trái với đúng chức năng ở cột phải.",
    explanation: "Dấu chấm hỏi — kết thúc câu hỏi; dấu chấm than — kết thúc câu cảm/khiến; dấu hai chấm — báo hiệu lời dẫn/liệt kê; dấu phẩy — ngăn cách các bộ phận trong câu.",
    match: {
      leftItems: [
        { id: "l1", label: "Dấu chấm hỏi (?)" },
        { id: "l2", label: "Dấu chấm than (!)" },
        { id: "l3", label: "Dấu hai chấm (:)" },
        { id: "l4", label: "Dấu phẩy (,)" },
      ],
      rightItems: [
        { id: "r1", label: "Ngăn cách các bộ phận trong câu" },
        { id: "r2", label: "Kết thúc câu hỏi" },
        { id: "r3", label: "Báo hiệu lời dẫn hoặc phần liệt kê" },
        { id: "r4", label: "Kết thúc câu cảm/khiến" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r4" },
        { leftId: "l3", rightId: "r3" },
        { leftId: "l4", rightId: "r1" },
      ],
    },
  },
  {
    id: "cd-05-mcq-8",
    topicIds: ["CD-05"],
    level: "M3",
    questionType: "mcq",
    prompt: "Vì sao cần dùng đúng dấu câu khi viết văn?",
    explanation: "Dùng đúng dấu câu giúp câu văn rõ nghĩa, đúng ngữ điệu (hỏi, cảm thán, kể...) và tránh gây hiểu lầm cho người đọc.",
    mcq: {
      options: [
        "Để bài viết có nhiều ký hiệu hơn",
        "Để câu văn rõ nghĩa, đúng ngữ điệu và tránh gây hiểu lầm",
        "Không quan trọng, dấu câu chỉ mang tính trang trí",
        "Để bài viết dài hơn",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Đây không phải mục đích của dấu câu.",
        "Đúng — đây là lý do quan trọng nhất cần dùng đúng dấu câu.",
        "Dấu câu có chức năng ngữ pháp và ý nghĩa quan trọng, không chỉ trang trí.",
        "Độ dài bài viết không phải mục đích của dấu câu.",
      ],
    },
  },
  {
    id: "cd-05-mcq-9",
    topicIds: ["CD-05"],
    level: "M2",
    questionType: "mcq",
    prompt: "Dấu gạch ngang thường dùng để làm gì trong đoạn hội thoại?",
    explanation: "Dấu gạch ngang thường đặt ở đầu dòng để đánh dấu lời nói trực tiếp của từng nhân vật trong đoạn hội thoại.",
    mcq: {
      options: [
        "Đánh dấu lời nói trực tiếp của từng nhân vật ở đầu dòng",
        "Kết thúc câu hỏi",
        "Ngăn cách các từ liệt kê",
        "Thể hiện ý còn tiếp tục",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là chức năng phổ biến của dấu gạch ngang trong hội thoại.",
        "Đây là chức năng của dấu chấm hỏi.",
        "Đây là chức năng của dấu phẩy.",
        "Đây là chức năng của dấu chấm lửng.",
      ],
    },
  },
];
