import type { Exercise } from "@/data-access/types";

// CD-03 — Chính tả: âm cuối và vần dễ lẫn. FR-M05: mọi câu fill dùng
// strictMode. Câu tự biên soạn (Mục 10.1).
export const CD03_EXERCISES: Exercise[] = [
  {
    id: "cd-03-fill-1",
    topicIds: ["CD-03"],
    level: "M1",
    questionType: "fill",
    prompt:
      "Điền từ đúng chính tả vào chỗ trống (phân biệt n/ng): \"Trong vườn có một cây ___ toả bóng mát.\" (loài cây gắn với hình ảnh sân trường)",
    explanation: "Viết đúng là \"bàng\" (âm cuối ng, chỉ cây bàng) — không viết \"bàn\" (âm cuối n, chỉ đồ vật).",
    fill: { acceptedAnswers: ["bàng"], strictMode: true, isSet: false },
  },
  {
    id: "cd-03-fill-2",
    topicIds: ["CD-03"],
    level: "M2",
    questionType: "fill",
    prompt:
      "Điền từ đúng chính tả vào chỗ trống (phân biệt vần iu/ưu): \"Đàn chim hót ___ lo trên cành cây.\"",
    explanation: "Viết đúng là \"líu\" (vần iu) — không viết \"lưu\" (vần ưu, nghĩa khác hẳn).",
    fill: { acceptedAnswers: ["líu"], strictMode: true, isSet: false },
  },
  {
    id: "cd-03-mcq-1",
    topicIds: ["CD-03"],
    level: "M1",
    questionType: "mcq",
    prompt: "Từ nào dưới đây viết ĐÚNG chính tả?",
    explanation: "\"Con hươu\" viết đúng với vần \"ươu\".",
    mcq: {
      options: ["Con hiêu", "Con hươu", "Con hiu", "Con hiểu"],
      answerIndex: 1,
      distractorNotes: [
        "Sai vần — không có từ \"hiêu\" mang nghĩa con vật này.",
        "Đúng — \"con hươu\" viết đúng chính tả.",
        "Sai vần — \"hiu\" không đúng.",
        "\"Hiểu\" là một từ khác hoàn toàn về nghĩa (biết, hiểu rõ), không liên quan đến con vật.",
      ],
    },
  },
  {
    id: "cd-03-mcq-2",
    topicIds: ["CD-03"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu nào dưới đây dùng ĐÚNG chính tả (phân biệt âm cuối n/ng)?',
    explanation: "\"Bàn học\" đúng chính tả với âm cuối n, vì đang nói đến đồ vật, không phải cây bàng.",
    mcq: {
      options: [
        "Em ngồi vào bàng học để làm bài tập.",
        "Em ngồi vào bàn học để làm bài tập.",
        "Sân trường có một cây bàn rất to.",
        "Cả hai câu đều viết đúng.",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Sai — phải viết \"bàn học\" (âm cuối n) vì đây là đồ vật, không phải cây bàng.",
        "Đúng — \"bàn học\" viết đúng chính tả.",
        "Sai — phải viết \"cây bàng\" (âm cuối ng) vì đây là loài cây.",
        "Chỉ có câu thứ hai (\"bàn học\") viết đúng chính tả.",
      ],
    },
  },
  {
    id: "cd-03-fill-3",
    topicIds: ["CD-03"],
    level: "M2",
    questionType: "fill",
    prompt: "Điền từ đúng chính tả vào chỗ trống (phân biệt âm cuối c/t): \"Chiếc áo này có màu sắc ___ hẳn với chiếc áo kia.\"",
    explanation: "Viết đúng là \"khác\" (âm cuối c, nghĩa là không giống nhau) — không viết \"khát\" (âm cuối t, nghĩa là muốn uống nước, không phù hợp câu này).",
    fill: { acceptedAnswers: ["khác"], strictMode: true, isSet: false },
  },
  {
    id: "cd-03-fill-4",
    topicIds: ["CD-03"],
    level: "M2",
    questionType: "fill",
    prompt: "Điền từ đúng chính tả vào chỗ trống (phân biệt âm cuối n/ng): \"Bác thợ mỏ đi lấy ___ để đốt lò sưởi.\"",
    explanation: "Viết đúng là \"than\" (âm cuối n, chỉ nhiên liệu màu đen dùng để đốt).",
    fill: { acceptedAnswers: ["than"], strictMode: true, isSet: false },
  },
  {
    id: "cd-03-mcq-3",
    topicIds: ["CD-03"],
    level: "M1",
    questionType: "mcq",
    prompt: "Từ nào dưới đây viết ĐÚNG chính tả (phân biệt vần iu/ưu)?",
    explanation: "\"Líu lo\" viết đúng với vần iu ở tiếng \"líu\".",
    mcq: {
      options: ["Lưu lo", "Líu lo", "Lứu lo", "Lỉu lo"],
      answerIndex: 1,
      distractorNotes: [
        "Sai vần — phải là \"líu\" (vần iu), không phải \"lưu\" (vần ưu).",
        "Đúng — \"líu lo\" viết đúng chính tả.",
        "Không có từ \"lứu\" trong tiếng Việt.",
        "Sai dấu — phải là \"líu\" (dấu sắc), không phải \"lỉu\" (dấu hỏi).",
      ],
    },
  },
  {
    id: "cd-03-mcq-4",
    topicIds: ["CD-03"],
    level: "M2",
    questionType: "mcq",
    prompt: "Con vật nào dưới đây có tên viết với vần \"ươu\"?",
    explanation: "\"Hươu\" là loài vật có tên viết với vần \"ươu\".",
    mcq: {
      options: ["Con hươu", "Con hiểu", "Con khỉ", "Con voi"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"hươu\" viết với vần \"ươu\".",
        "\"Hiểu\" không phải tên con vật, và không cùng vần \"ươu\".",
        "\"Khỉ\" không có vần \"ươu\".",
        "\"Voi\" không có vần \"ươu\".",
      ],
    },
  },
  {
    id: "cd-03-mcq-5",
    topicIds: ["CD-03"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu nào dưới đây dùng ĐÚNG chính tả (phân biệt âm cuối c/t)?',
    explanation: "\"Khác nhau\" viết đúng với âm cuối c.",
    mcq: {
      options: [
        "Hai bức tranh này có màu sắc khát nhau.",
        "Hai bức tranh này có màu sắc khác nhau.",
        "Em cảm thấy rất khác nước sau khi chạy bộ.",
        "Cả ba câu đều đúng.",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Sai — phải viết \"khác nhau\" (âm cuối c), không phải \"khát nhau\".",
        "Đúng — \"khác nhau\" viết đúng chính tả, phù hợp nghĩa \"không giống nhau\".",
        "Sai — phải viết \"khát nước\" (âm cuối t, nghĩa là muốn uống nước).",
        "Chỉ có câu thứ hai viết đúng.",
      ],
    },
  },
  {
    id: "cd-03-match-1",
    topicIds: ["CD-03"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi từ ở cột trái với đúng nghĩa của nó ở cột phải.",
    explanation: "\"Khác\" (âm cuối c) nghĩa là không giống nhau; \"khát\" (âm cuối t) nghĩa là muốn uống nước; \"bàn\" (âm cuối n) là đồ vật; \"bàng\" (âm cuối ng) là loài cây.",
    match: {
      leftItems: [
        { id: "l1", label: "khác" },
        { id: "l2", label: "khát" },
        { id: "l3", label: "bàng" },
      ],
      rightItems: [
        { id: "r1", label: "Muốn uống nước" },
        { id: "r2", label: "Loài cây sân trường" },
        { id: "r3", label: "Không giống nhau" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r3" },
        { leftId: "l2", rightId: "r1" },
        { leftId: "l3", rightId: "r2" },
      ],
    },
  },
  {
    id: "cd-03-mcq-6",
    topicIds: ["CD-03"],
    level: "M3",
    questionType: "mcq",
    prompt: "Vì sao âm cuối n/ng, c/t dễ bị viết sai?",
    explanation: "Ở nhiều vùng miền, cách phát âm âm cuối n/ng hoặc c/t gần giống nhau, khiến người viết dễ nhầm lẫn nếu không nhớ mặt chữ và nghĩa của từ.",
    mcq: {
      options: [
        "Vì các âm cuối này không tồn tại trong tiếng Việt",
        "Vì cách phát âm ở nhiều vùng miền gần giống nhau, dễ gây nhầm lẫn",
        "Vì đây là các âm mượn từ tiếng nước ngoài",
        "Vì các từ có âm cuối n/ng, c/t đều rất hiếm gặp",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Các âm cuối này hoàn toàn tồn tại và phổ biến trong tiếng Việt.",
        "Đúng — đây là nguyên nhân chính khiến nhiều người viết sai các âm cuối này.",
        "Đây là các âm thuần Việt, không phải âm mượn.",
        "Các từ có âm cuối này rất phổ biến trong tiếng Việt.",
      ],
    },
  },
  {
    id: "cd-03-fill-5",
    topicIds: ["CD-03"],
    level: "M2",
    questionType: "fill",
    prompt: "Điền từ đúng chính tả vào chỗ trống (phân biệt âm cuối n/ng): \"Con thuyền lướt nhẹ trên mặt hồ ___ lặng.\"",
    explanation: "Viết đúng là \"phẳng\" (âm cuối ng, nghĩa là bằng, không gợn sóng).",
    fill: { acceptedAnswers: ["phẳng"], strictMode: true, isSet: false },
  },
];
