import type { Exercise } from "@/data-access/types";

// NT-05 — Từ Hán Việt và mở rộng vốn từ theo chủ điểm. Ví dụ tự biên soạn
// (Mục 10.1 hướng B).
export const NT05_EXERCISES: Exercise[] = [
  {
    id: "nt-05-mcq-1",
    topicIds: ["NT-05"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây là từ Hán Việt tương ứng với từ thuần Việt "cha mẹ"?',
    explanation: "\"Phụ mẫu\" là từ Hán Việt mang sắc thái trang trọng, cùng nghĩa với \"cha mẹ\".",
    mcq: {
      options: ["Phụ mẫu", "Ông bà", "Con cái", "Anh chị"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"phụ mẫu\" là từ Hán Việt trang trọng chỉ cha mẹ.",
        "\"Ông bà\" chỉ thế hệ trên cha mẹ, không cùng nghĩa.",
        "\"Con cái\" chỉ thế hệ con, không cùng nghĩa với \"cha mẹ\".",
        "\"Anh chị\" chỉ anh chị em, không cùng nghĩa với \"cha mẹ\".",
      ],
    },
  },
  {
    id: "nt-05-mcq-2",
    topicIds: ["NT-05"],
    level: "M2",
    questionType: "mcq",
    prompt: "Từ Hán Việt thường mang sắc thái như thế nào so với từ thuần Việt cùng nghĩa?",
    explanation: "Từ Hán Việt thường trang trọng, khái quát hơn — thường dùng trong văn viết, hoàn cảnh trang trọng.",
    mcq: {
      options: [
        "Trang trọng, khái quát hơn từ thuần Việt cùng nghĩa",
        "Thân mật, gần gũi hơn từ thuần Việt cùng nghĩa",
        "Luôn ngắn hơn từ thuần Việt cùng nghĩa",
        "Không có sự khác biệt nào so với từ thuần Việt",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là đặc điểm sắc thái nổi bật của từ Hán Việt.",
        "Đây là đặc điểm của từ thuần Việt so với từ Hán Việt, ngược lại với câu hỏi.",
        "Độ dài không phải là đặc điểm phân biệt sắc thái giữa hai loại từ.",
        "Từ Hán Việt và từ thuần Việt cùng nghĩa thường khác nhau về sắc thái sử dụng.",
      ],
    },
  },
  {
    id: "nt-05-mcq-3",
    topicIds: ["NT-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây KHÔNG thuộc chủ điểm "Tổ quốc"?',
    explanation: "\"Bàn ghế\" là đồ vật trong nhà, không liên quan đến chủ điểm Tổ quốc, đất nước.",
    mcq: {
      options: ["Giang sơn", "Quốc gia", "Bàn ghế", "Đất nước"],
      answerIndex: 2,
      distractorNotes: [
        "\"Giang sơn\" là từ Hán Việt chỉ đất nước, thuộc chủ điểm Tổ quốc.",
        "\"Quốc gia\" thuộc chủ điểm Tổ quốc.",
        "Đúng — \"bàn ghế\" là đồ vật, không liên quan đến chủ điểm Tổ quốc.",
        "\"Đất nước\" thuộc chủ điểm Tổ quốc.",
      ],
    },
  },
  {
    id: "nt-05-mcq-4",
    topicIds: ["NT-05"],
    level: "M1",
    questionType: "mcq",
    prompt: "Từ Hán Việt là gì?",
    explanation: "Từ Hán Việt là từ mượn gốc Hán, đã được Việt hoá và sử dụng phổ biến trong tiếng Việt.",
    mcq: {
      options: [
        "Từ mượn gốc Hán, đã được Việt hoá",
        "Từ thuần tuý do người Việt tự tạo ra",
        "Từ mượn từ tiếng Anh",
        "Từ chỉ dùng trong văn nói hằng ngày",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là định nghĩa của từ Hán Việt.",
        "Đây là định nghĩa của từ thuần Việt, ngược lại với từ Hán Việt.",
        "Từ Hán Việt mượn gốc Hán, không phải tiếng Anh.",
        "Từ Hán Việt thường dùng trong văn viết, hoàn cảnh trang trọng hơn là văn nói hằng ngày.",
      ],
    },
  },
  {
    id: "nt-05-mcq-5",
    topicIds: ["NT-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ Hán Việt nào tương ứng với từ thuần Việt "nhà"?',
    explanation: "\"Gia\" là yếu tố Hán Việt tương ứng với \"nhà\" (VD: gia đình = nhà + đình).",
    mcq: {
      options: ["Gia", "Thuỷ", "Sơn", "Thiên"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"gia\" tương ứng với \"nhà\" trong tiếng Hán Việt (VD: gia đình).",
        "\"Thuỷ\" tương ứng với \"nước\" (VD: thuỷ sản).",
        "\"Sơn\" tương ứng với \"núi\" (VD: sơn cước).",
        "\"Thiên\" tương ứng với \"trời\" (VD: thiên nhiên).",
      ],
    },
  },
  {
    id: "nt-05-fill-1",
    topicIds: ["NT-05"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền từ Hán Việt còn thiếu: từ thuần Việt "nước" tương ứng với yếu tố Hán Việt ___ (VD: quốc gia).',
    explanation: "\"Quốc\" là yếu tố Hán Việt tương ứng với \"nước\" (VD: quốc gia, Tổ quốc, quốc kỳ).",
    fill: { acceptedAnswers: ["quốc"], strictMode: false, isSet: false },
  },
  {
    id: "nt-05-mcq-6",
    topicIds: ["NT-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây thuộc chủ điểm "gia đình"?',
    explanation: "\"Phụ huynh\" (cha mẹ, người giám hộ) thuộc chủ điểm gia đình.",
    mcq: {
      options: ["Phụ huynh", "Quốc gia", "Sông núi", "Trường học"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"phụ huynh\" liên quan trực tiếp đến chủ điểm gia đình.",
        "\"Quốc gia\" thuộc chủ điểm Tổ quốc, không phải gia đình.",
        "\"Sông núi\" thuộc chủ điểm thiên nhiên/Tổ quốc.",
        "\"Trường học\" thuộc chủ điểm học tập/nhà trường.",
      ],
    },
  },
  {
    id: "nt-05-mcq-7",
    topicIds: ["NT-05"],
    level: "M2",
    questionType: "mcq",
    prompt: "Câu nào dưới đây dùng từ Hán Việt phù hợp với hoàn cảnh trang trọng?",
    explanation: "\"Kính thưa quý vị đại biểu\" dùng nhiều từ Hán Việt (kính, quý vị, đại biểu) phù hợp với hoàn cảnh trang trọng như lễ khai giảng, hội nghị.",
    mcq: {
      options: [
        "Kính thưa quý vị đại biểu, hôm nay chúng ta tổ chức lễ khai giảng.",
        "Ê, đi chơi không?",
        "Tớ đói bụng quá rồi.",
        "Cậu ăn cơm chưa?",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — câu này dùng nhiều từ Hán Việt trang trọng, phù hợp với hoàn cảnh lễ nghi.",
        "Đây là câu nói thân mật, thông thường, không phù hợp hoàn cảnh trang trọng.",
        "Đây là câu nói thân mật, thông thường.",
        "Đây là câu nói thân mật, thông thường.",
      ],
    },
  },
  {
    id: "nt-05-match-1",
    topicIds: ["NT-05"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi từ Hán Việt ở cột trái với từ thuần Việt tương ứng ở cột phải.",
    explanation: "phụ mẫu–cha mẹ, gia đình–nhà, quốc gia–đất nước, huynh đệ–anh em.",
    match: {
      leftItems: [
        { id: "l1", label: "Phụ mẫu" },
        { id: "l2", label: "Gia đình" },
        { id: "l3", label: "Quốc gia" },
        { id: "l4", label: "Huynh đệ" },
      ],
      rightItems: [
        { id: "r1", label: "Đất nước" },
        { id: "r2", label: "Cha mẹ" },
        { id: "r3", label: "Anh em" },
        { id: "r4", label: "Nhà" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r4" },
        { leftId: "l3", rightId: "r1" },
        { leftId: "l4", rightId: "r3" },
      ],
    },
  },
  {
    id: "nt-05-mcq-8",
    topicIds: ["NT-05"],
    level: "M3",
    questionType: "mcq",
    prompt: "Vì sao cần biết phân biệt từ Hán Việt và từ thuần Việt khi viết văn?",
    explanation: "Biết phân biệt giúp chọn từ phù hợp với hoàn cảnh giao tiếp (trang trọng hay thân mật), tránh dùng sai sắc thái.",
    mcq: {
      options: [
        "Để bài viết dùng toàn từ Hán Việt cho có vẻ hay",
        "Để chọn từ phù hợp với hoàn cảnh giao tiếp, tránh sai sắc thái biểu cảm",
        "Không cần thiết, hai loại từ này có thể dùng thay thế nhau bất kỳ lúc nào",
        "Để đếm số lượng từ Hán Việt trong bài",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Dùng toàn từ Hán Việt không phải lúc nào cũng phù hợp, có thể khiến câu văn xa lạ, khó hiểu.",
        "Đúng — đây là lý do quan trọng nhất để phân biệt hai loại từ này.",
        "Hai loại từ có sắc thái khác nhau, không phải lúc nào cũng thay thế được cho nhau.",
        "Đây không phải mục đích của việc phân biệt từ Hán Việt/thuần Việt.",
      ],
    },
  },
  {
    id: "nt-05-mcq-9",
    topicIds: ["NT-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ Hán Việt nào tương ứng với từ thuần Việt "học trò"?',
    explanation: "\"Học sinh\" là từ Hán Việt tương ứng với \"học trò\" trong tiếng thuần Việt.",
    mcq: {
      options: ["Học sinh", "Giáo viên", "Nhà trường", "Bài tập"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"học sinh\" (Hán Việt) tương ứng với \"học trò\" (thuần Việt).",
        "\"Giáo viên\" chỉ người dạy học, không phải người học.",
        "\"Nhà trường\" chỉ nơi học tập, không phải người học.",
        "\"Bài tập\" không liên quan đến người học.",
      ],
    },
  },
  {
    id: "nt-05-mcq-10",
    topicIds: ["NT-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây thuộc chủ điểm "thiên nhiên"?',
    explanation: "\"Sơn thuỷ\" (núi sông) là từ Hán Việt thuộc chủ điểm thiên nhiên.",
    mcq: {
      options: ["Sơn thuỷ", "Phụ huynh", "Học sinh", "Quốc kỳ"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"sơn thuỷ\" (núi sông) thuộc chủ điểm thiên nhiên.",
        "\"Phụ huynh\" thuộc chủ điểm gia đình.",
        "\"Học sinh\" thuộc chủ điểm học tập.",
        "\"Quốc kỳ\" thuộc chủ điểm Tổ quốc.",
      ],
    },
  },
];
