import type { Exercise } from "@/data-access/types";

// NT-06 — Thành ngữ, tục ngữ, ca dao. Dùng các câu quen thuộc, thuộc phạm
// vi công cộng (Mục 10.1 hướng A).
export const NT06_EXERCISES: Exercise[] = [
  {
    id: "nt-06-mcq-1",
    topicIds: ["NT-06"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Câu "Có công mài sắt, có ngày nên kim" khuyên chúng ta điều gì?',
    explanation: "Câu tục ngữ khuyên con người phải kiên trì, chăm chỉ thì mới đạt được thành công.",
    mcq: {
      options: [
        "Phải kiên trì, chăm chỉ thì mới đạt được thành công",
        "Nên đi mua kim ở chợ",
        "Sắt quý hơn kim",
        "Không nên làm việc vất vả",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là bài học (nghĩa bóng) của câu tục ngữ.",
        "Đây là hiểu theo nghĩa đen, không phải bài học câu tục ngữ muốn truyền tải.",
        "Câu tục ngữ không so sánh giá trị giữa sắt và kim.",
        "Câu tục ngữ khuyến khích sự chăm chỉ, kiên trì, không phải né tránh vất vả.",
      ],
    },
  },
  {
    id: "nt-06-mcq-2",
    topicIds: ["NT-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Thành ngữ "nước đổ lá khoai" dùng để chỉ điều gì?',
    explanation: "Nước đổ lên lá khoai (lá trơn) sẽ trôi hết ngay, không đọng lại — thành ngữ chỉ việc làm vô ích, không có kết quả hoặc lời khuyên không được tiếp thu.",
    mcq: {
      options: [
        "Việc làm vô ích, không có kết quả (hoặc lời khuyên không được tiếp thu)",
        "Một cách tưới cây hiệu quả",
        "Trời đang mưa to",
        "Một món ăn từ lá khoai",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là nghĩa bóng của thành ngữ, không phải nghĩa đen về việc tưới nước.",
        "Thành ngữ không nói về kỹ thuật tưới cây.",
        "Thành ngữ mang nghĩa bóng, không tả hiện tượng thời tiết.",
        "Thành ngữ không liên quan đến việc ăn uống.",
      ],
    },
  },
  {
    id: "nt-06-mcq-3",
    topicIds: ["NT-06"],
    level: "M2",
    questionType: "mcq",
    prompt: "Điểm khác biệt chính giữa thành ngữ và tục ngữ là gì?",
    explanation: "Thành ngữ là cụm từ cố định (không phải câu hoàn chỉnh), còn tục ngữ là một câu hoàn chỉnh đúc kết kinh nghiệm sống.",
    mcq: {
      options: [
        "Thành ngữ là cụm từ cố định, tục ngữ là câu hoàn chỉnh đúc kết kinh nghiệm",
        "Thành ngữ dài hơn tục ngữ",
        "Tục ngữ luôn có vần, thành ngữ thì không bao giờ có vần",
        "Không có sự khác biệt nào",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là điểm khác biệt cơ bản nhất giữa hai loại.",
        "Độ dài không phải là tiêu chí phân biệt chính.",
        "Một số thành ngữ vẫn có yếu tố vần điệu, đây không phải tiêu chí tuyệt đối.",
        "Hai khái niệm này khác nhau rõ rệt về cấu trúc.",
      ],
    },
  },
  {
    id: "nt-06-fill-1",
    topicIds: ["NT-06"],
    level: "M1",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: "Có công mài sắt, có ngày nên ___".',
    explanation: "Đây là câu tục ngữ quen thuộc \"Có công mài sắt, có ngày nên kim\".",
    fill: { acceptedAnswers: ["kim"], strictMode: false, isSet: false },
  },
  {
    id: "nt-06-mcq-4",
    topicIds: ["NT-06"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Câu tục ngữ "Uống nước nhớ nguồn" khuyên chúng ta điều gì?',
    explanation: "Câu tục ngữ khuyên con người phải biết ơn, nhớ đến người/nơi đã tạo ra thành quả mà mình đang hưởng.",
    mcq: {
      options: [
        "Phải biết ơn, nhớ đến công lao của người đi trước",
        "Nên uống nhiều nước mỗi ngày",
        "Nước từ nguồn sạch hơn nước máy",
        "Không nên lãng phí nước",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là bài học (nghĩa bóng) của câu tục ngữ.",
        "Đây là hiểu theo nghĩa đen, không phải bài học câu tục ngữ muốn truyền tải.",
        "Câu tục ngữ không so sánh chất lượng nước.",
        "Câu tục ngữ nói về lòng biết ơn, không phải về tiết kiệm nước.",
      ],
    },
  },
  {
    id: "nt-06-mcq-5",
    topicIds: ["NT-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Thành ngữ "chân cứng đá mềm" thường được dùng để chúc điều gì?',
    explanation: "Thành ngữ này thường dùng để chúc người đi xa được khoẻ mạnh, vượt qua mọi khó khăn, gian khổ trên đường.",
    mcq: {
      options: [
        "Chúc sức khoẻ, vững vàng vượt qua khó khăn khi đi đường xa",
        "Chúc có đôi chân đẹp",
        "Chúc mua được đá quý",
        "Chúc học giỏi môn Toán",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là lời chúc phổ biến khi tiễn ai đó đi xa.",
        "Đây không phải nghĩa bóng của thành ngữ, chỉ là hiểu theo nghĩa đen.",
        "Thành ngữ không liên quan đến việc mua bán đá quý.",
        "Thành ngữ không liên quan đến việc học Toán.",
      ],
    },
  },
  {
    id: "nt-06-fill-2",
    topicIds: ["NT-06"],
    level: "M1",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: "Uống nước nhớ ___".',
    explanation: "Đây là câu tục ngữ quen thuộc \"Uống nước nhớ nguồn\".",
    fill: { acceptedAnswers: ["nguồn"], strictMode: false, isSet: false },
  },
  {
    id: "nt-06-mcq-6",
    topicIds: ["NT-06"],
    level: "M2",
    questionType: "mcq",
    prompt: "Ca dao thường được viết theo thể thơ nào?",
    explanation: "Ca dao thường được viết theo thể thơ lục bát (câu 6 chữ xen câu 8 chữ).",
    mcq: {
      options: ["Thể thơ lục bát", "Thể thơ Đường luật", "Thể thơ tự do hoàn toàn", "Văn xuôi"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — ca dao thường theo thể lục bát, dễ nhớ, dễ truyền miệng.",
        "Thể thơ Đường luật có niêm luật chặt chẽ, ít gặp trong ca dao dân gian.",
        "Ca dao thường có vần điệu theo thể lục bát, không hoàn toàn tự do.",
        "Ca dao là thơ, có vần điệu, không phải văn xuôi.",
      ],
    },
  },
  {
    id: "nt-06-mcq-7",
    topicIds: ["NT-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu nào dưới đây là MỘT câu tục ngữ hoàn chỉnh (không phải thành ngữ)?',
    explanation: "\"Đi một ngày đàng, học một sàng khôn\" là một câu hoàn chỉnh, đúc kết kinh nghiệm — là tục ngữ. \"Nước đổ lá khoai\" chỉ là cụm từ, là thành ngữ.",
    mcq: {
      options: [
        "Nước đổ lá khoai",
        "Đi một ngày đàng, học một sàng khôn",
        "Chân cứng đá mềm",
        "Mưa to gió lớn",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Đây là thành ngữ (cụm từ cố định), không phải câu hoàn chỉnh.",
        "Đúng — đây là câu hoàn chỉnh, đúc kết kinh nghiệm (đi nhiều nơi sẽ học được nhiều điều), là tục ngữ.",
        "Đây là thành ngữ (cụm từ cố định).",
        "Đây là thành ngữ (cụm từ cố định) miêu tả thời tiết xấu.",
      ],
    },
  },
  {
    id: "nt-06-match-1",
    topicIds: ["NT-06"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi câu ở cột trái với đúng bài học/nghĩa bóng ở cột phải.",
    explanation: "\"Có công mài sắt, có ngày nên kim\" — kiên trì sẽ thành công; \"Uống nước nhớ nguồn\" — biết ơn người đi trước; \"Nước đổ lá khoai\" — việc làm vô ích.",
    match: {
      leftItems: [
        { id: "l1", label: "Có công mài sắt, có ngày nên kim" },
        { id: "l2", label: "Uống nước nhớ nguồn" },
        { id: "l3", label: "Nước đổ lá khoai" },
      ],
      rightItems: [
        { id: "r1", label: "Việc làm vô ích, không có kết quả" },
        { id: "r2", label: "Kiên trì sẽ đạt được thành công" },
        { id: "r3", label: "Biết ơn người đi trước" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r3" },
        { leftId: "l3", rightId: "r1" },
      ],
    },
  },
  {
    id: "nt-06-mcq-8",
    topicIds: ["NT-06"],
    level: "M2",
    questionType: "mcq",
    prompt: "Vì sao cần hiểu đúng nghĩa bóng của thành ngữ, tục ngữ, không chỉ nghĩa đen?",
    explanation: "Thành ngữ, tục ngữ thường mang bài học, kinh nghiệm sống ẩn trong nghĩa bóng — chỉ hiểu nghĩa đen sẽ không nắm được thông điệp thực sự tác giả dân gian muốn truyền tải.",
    mcq: {
      options: [
        "Vì nghĩa đen luôn sai",
        "Vì bài học, kinh nghiệm sống thực sự nằm ở nghĩa bóng",
        "Vì nghĩa đen quá khó hiểu",
        "Không cần thiết, chỉ cần hiểu nghĩa đen là đủ",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Nghĩa đen không sai, chỉ là chưa đủ để hiểu trọn vẹn bài học.",
        "Đúng — đây là lý do quan trọng nhất để tìm hiểu nghĩa bóng.",
        "Nghĩa đen thường dễ hiểu, vấn đề là cần đi xa hơn để tìm bài học.",
        "Chỉ hiểu nghĩa đen sẽ bỏ lỡ bài học chính mà câu nói muốn truyền tải.",
      ],
    },
  },
  {
    id: "nt-06-mcq-9",
    topicIds: ["NT-06"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Câu tục ngữ "Ăn quả nhớ kẻ trồng cây" khuyên chúng ta điều gì?',
    explanation: "Câu tục ngữ khuyên phải biết ơn người đã tạo ra thành quả mà mình đang được hưởng, cùng ý nghĩa với \"Uống nước nhớ nguồn\".",
    mcq: {
      options: [
        "Phải biết ơn người đã tạo ra thành quả mình hưởng",
        "Nên trồng nhiều cây ăn quả",
        "Quả cây rất bổ dưỡng",
        "Không nên hái quả khi chưa chín",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là bài học (nghĩa bóng) của câu tục ngữ, cùng ý với \"uống nước nhớ nguồn\".",
        "Đây là hiểu theo nghĩa đen, không phải bài học của câu.",
        "Câu tục ngữ không nói về giá trị dinh dưỡng.",
        "Câu tục ngữ không nói về thời điểm hái quả.",
      ],
    },
  },
];
