import type { Exercise } from "@/data-access/types";

// NT-02 — Từ trái nghĩa. Ví dụ tự biên soạn (Mục 10.1 hướng B).
export const NT02_EXERCISES: Exercise[] = [
  {
    id: "nt-02-mcq-1",
    topicIds: ["NT-02"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Từ nào trái nghĩa với từ "chăm chỉ"?',
    explanation: "\"Lười biếng\" đối lập hoàn toàn với \"chăm chỉ\" trên cùng tiêu chí thái độ làm việc.",
    mcq: {
      options: ["Siêng năng", "Cần cù", "Lười biếng", "Nhanh nhẹn"],
      answerIndex: 2,
      distractorNotes: [
        "\"Siêng năng\" đồng nghĩa với \"chăm chỉ\", không phải trái nghĩa.",
        "\"Cần cù\" đồng nghĩa với \"chăm chỉ\", không phải trái nghĩa.",
        "Đúng — \"lười biếng\" đối lập hoàn toàn với \"chăm chỉ\".",
        "\"Nhanh nhẹn\" không cùng tiêu chí với \"chăm chỉ\" (tiêu chí tốc độ, không phải thái độ làm việc).",
      ],
    },
  },
  {
    id: "nt-02-mcq-2",
    topicIds: ["NT-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Canh này nhạt quá, mẹ cho thêm chút muối nhé!", từ trái nghĩa với "nhạt" ở đây là từ nào?',
    explanation: "Ở đây \"nhạt\" đang nói về vị giác (thiếu muối) nên từ trái nghĩa phù hợp là \"mặn\", không phải \"đậm\" (dùng cho màu sắc).",
    mcq: {
      options: ["Đậm", "Mặn", "Nhiều", "Ngọt"],
      answerIndex: 1,
      distractorNotes: [
        "\"Đậm\" là từ trái nghĩa của \"nhạt\" khi nói về MÀU SẮC, không phù hợp trong câu nói về vị canh.",
        "Đúng — trong ngữ cảnh vị giác (canh thiếu muối), \"nhạt\" trái nghĩa với \"mặn\".",
        "\"Nhiều\" không phải từ trái nghĩa của \"nhạt\".",
        "\"Ngọt\" là một vị khác, không đối lập trực tiếp với \"nhạt\" trong câu này.",
      ],
    },
  },
  {
    id: "nt-02-fill-1",
    topicIds: ["NT-02"],
    level: "M2",
    questionType: "fill",
    prompt: "Điền từ trái nghĩa: cao – ___",
    explanation: "\"Thấp\" trái nghĩa với \"cao\" trên tiêu chí chiều cao.",
    fill: { acceptedAnswers: ["thấp"], strictMode: false, isSet: false },
  },
  {
    id: "nt-02-mcq-3",
    topicIds: ["NT-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Cặp từ nào dưới đây KHÔNG phải là cặp từ trái nghĩa?',
    explanation: "\"Cao\" và \"xanh\" không cùng nói về một tiêu chí (chiều cao và màu sắc), nên không phải cặp trái nghĩa.",
    mcq: {
      options: ["To – nhỏ", "Vui – buồn", "Cao – xanh", "Nhanh – chậm"],
      answerIndex: 2,
      distractorNotes: [
        "\"To – nhỏ\" là cặp trái nghĩa đúng (cùng tiêu chí kích thước).",
        "\"Vui – buồn\" là cặp trái nghĩa đúng (cùng tiêu chí cảm xúc).",
        "Đúng — \"cao\" và \"xanh\" không cùng tiêu chí, không phải cặp trái nghĩa.",
        "\"Nhanh – chậm\" là cặp trái nghĩa đúng (cùng tiêu chí tốc độ).",
      ],
    },
  },
  {
    id: "nt-02-mcq-4",
    topicIds: ["NT-02"],
    level: "M1",
    questionType: "mcq",
    prompt: "Từ trái nghĩa là gì?",
    explanation: "Từ trái nghĩa là những từ có nghĩa đối lập nhau trên cùng một tiêu chí.",
    mcq: {
      options: [
        "Những từ có nghĩa giống nhau",
        "Những từ có nghĩa đối lập nhau trên cùng một tiêu chí",
        "Những từ giống nhau về âm nhưng khác nghĩa",
        "Những từ có nhiều nghĩa khác nhau",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Đây là định nghĩa của từ đồng nghĩa (NT-01).",
        "Đúng — đây là định nghĩa của từ trái nghĩa.",
        "Đây là định nghĩa của từ đồng âm (NT-03).",
        "Đây là định nghĩa của từ nhiều nghĩa (NT-04).",
      ],
    },
  },
  {
    id: "nt-02-mcq-5",
    topicIds: ["NT-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào trái nghĩa với "dũng cảm"?',
    explanation: "\"Nhút nhát\" đối lập với \"dũng cảm\" trên tiêu chí sự can đảm.",
    mcq: {
      options: ["Gan dạ", "Nhút nhát", "Mạnh mẽ", "Kiên cường"],
      answerIndex: 1,
      distractorNotes: [
        "\"Gan dạ\" đồng nghĩa với \"dũng cảm\".",
        "Đúng — \"nhút nhát\" đối lập với \"dũng cảm\".",
        "\"Mạnh mẽ\" gần nghĩa với \"dũng cảm\", không trái nghĩa.",
        "\"Kiên cường\" gần nghĩa với \"dũng cảm\", không trái nghĩa.",
      ],
    },
  },
  {
    id: "nt-02-fill-2",
    topicIds: ["NT-02"],
    level: "M1",
    questionType: "fill",
    prompt: "Điền từ trái nghĩa: to – ___",
    explanation: "\"Nhỏ\" trái nghĩa với \"to\" trên tiêu chí kích thước.",
    fill: { acceptedAnswers: ["nhỏ"], strictMode: false, isSet: false },
  },
  {
    id: "nt-02-mcq-6",
    topicIds: ["NT-02"],
    level: "M2",
    questionType: "mcq",
    prompt: "Từ trái nghĩa có tác dụng gì khi dùng trong câu văn?",
    explanation: "Từ trái nghĩa thường dùng để tạo sự đối lập, làm nổi bật đặc điểm của sự vật, sự việc được nói đến.",
    mcq: {
      options: [
        "Làm câu văn dài hơn",
        "Tạo sự đối lập, làm nổi bật đặc điểm sự vật, sự việc",
        "Không có tác dụng gì đặc biệt",
        "Chỉ dùng để đếm số lượng",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Đây không phải mục đích chính của từ trái nghĩa.",
        "Đúng — đây là tác dụng nổi bật của từ trái nghĩa.",
        "Từ trái nghĩa có tác dụng rõ rệt trong việc tạo đối lập, nhấn mạnh ý.",
        "Từ trái nghĩa không liên quan đến việc đếm số lượng.",
      ],
    },
  },
  {
    id: "nt-02-match-1",
    topicIds: ["NT-02"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi từ ở cột trái với từ trái nghĩa của nó ở cột phải.",
    explanation: "cao–thấp, chăm chỉ–lười biếng, vui–buồn, nhanh–chậm là các cặp từ trái nghĩa thường gặp.",
    match: {
      leftItems: [
        { id: "l1", label: "cao" },
        { id: "l2", label: "chăm chỉ" },
        { id: "l3", label: "vui" },
        { id: "l4", label: "nhanh" },
      ],
      rightItems: [
        { id: "r1", label: "buồn" },
        { id: "r2", label: "thấp" },
        { id: "r3", label: "chậm" },
        { id: "r4", label: "lười biếng" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r4" },
        { leftId: "l3", rightId: "r1" },
        { leftId: "l4", rightId: "r3" },
      ],
    },
  },
  {
    id: "nt-02-mcq-7",
    topicIds: ["NT-02"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Trong câu "Áo này mặc hơi rộng, em cần đổi cỡ nhỏ hơn.", từ trái nghĩa với "rộng" trong ngữ cảnh này là gì?',
    explanation: "Khi nói về kích cỡ quần áo, \"rộng\" trái nghĩa với \"chật\" (không phải \"hẹp\", thường dùng cho không gian).",
    mcq: {
      options: ["Hẹp", "Chật", "Nhỏ", "Dài"],
      answerIndex: 1,
      distractorNotes: [
        "\"Hẹp\" thường dùng để nói về không gian (đường hẹp), không phù hợp khi nói về quần áo.",
        "Đúng — khi nói về quần áo, \"rộng\" trái nghĩa với \"chật\".",
        "\"Nhỏ\" không phải từ trái nghĩa chính xác của \"rộng\" trong ngữ cảnh này.",
        "\"Dài\" nói về chiều dài, không đối lập với \"rộng\" trong ngữ cảnh này.",
      ],
    },
  },
  {
    id: "nt-02-mcq-8",
    topicIds: ["NT-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào trái nghĩa với "sạch sẽ"?',
    explanation: "\"Bẩn thỉu\" đối lập với \"sạch sẽ\" trên tiêu chí độ sạch.",
    mcq: {
      options: ["Gọn gàng", "Bẩn thỉu", "Ngăn nắp", "Tươm tất"],
      answerIndex: 1,
      distractorNotes: [
        "\"Gọn gàng\" không đối lập với \"sạch sẽ\", hai từ có thể cùng dùng để khen.",
        "Đúng — \"bẩn thỉu\" đối lập với \"sạch sẽ\".",
        "\"Ngăn nắp\" không đối lập với \"sạch sẽ\".",
        "\"Tươm tất\" không đối lập với \"sạch sẽ\".",
      ],
    },
  },
  {
    id: "nt-02-mcq-9",
    topicIds: ["NT-02"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Từ nào trái nghĩa với "khoẻ mạnh"?',
    explanation: "\"Ốm yếu\" đối lập với \"khoẻ mạnh\" trên tiêu chí sức khoẻ.",
    mcq: {
      options: ["Cường tráng", "Ốm yếu", "Nhanh nhẹn", "Vạm vỡ"],
      answerIndex: 1,
      distractorNotes: [
        "\"Cường tráng\" gần nghĩa với \"khoẻ mạnh\", không trái nghĩa.",
        "Đúng — \"ốm yếu\" đối lập với \"khoẻ mạnh\".",
        "\"Nhanh nhẹn\" không cùng tiêu chí sức khoẻ tổng thể.",
        "\"Vạm vỡ\" gần nghĩa với \"khoẻ mạnh\", không trái nghĩa.",
      ],
    },
  },
];
