import type { Exercise } from "@/data-access/types";

// NT-04 — Từ nhiều nghĩa: nghĩa gốc và nghĩa chuyển. Ví dụ tự biên soạn
// (Mục 10.1 hướng B).
export const NT04_EXERCISES: Exercise[] = [
  {
    id: "nt-04-mcq-1",
    topicIds: ["NT-04"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Trong câu "Đôi mắt em to tròn.", từ "mắt" được dùng với nghĩa nào?',
    explanation: "\"Mắt\" chỉ bộ phận cơ thể dùng để nhìn — đây là nghĩa gốc của từ \"mắt\".",
    mcq: {
      options: ["Nghĩa gốc", "Nghĩa chuyển", "Nghĩa đồng âm", "Không có nghĩa"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là nghĩa cơ bản, quen thuộc nhất của từ \"mắt\", là nghĩa gốc.",
        "Nghĩa chuyển là nghĩa được suy ra từ nghĩa gốc (ví dụ \"mắt lưới\"), câu này dùng đúng nghĩa gốc.",
        "\"Mắt\" ở đây không phải hiện tượng đồng âm.",
        "Từ \"mắt\" trong câu này có nghĩa rõ ràng.",
      ],
    },
  },
  {
    id: "nt-04-mcq-2",
    topicIds: ["NT-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Chiếc bàn có bốn chân vững chãi.", từ "chân" được dùng với nghĩa nào?',
    explanation: "\"Chân bàn\" chỉ phần dưới cùng đỡ cái bàn, có liên hệ với nghĩa gốc \"chân người\" (bộ phận để đứng, đỡ cơ thể) — đây là nghĩa chuyển.",
    mcq: {
      options: ["Nghĩa gốc", "Nghĩa chuyển", "Nghĩa đồng âm", "Không có nghĩa"],
      answerIndex: 1,
      distractorNotes: [
        "Nghĩa gốc của \"chân\" là bộ phận cơ thể người/động vật dùng để đi, đứng.",
        "Đúng — \"chân bàn\" được suy ra từ nghĩa gốc, vẫn có liên hệ (phần đỡ ở dưới cùng).",
        "\"Chân\" ở đây có liên hệ với nghĩa gốc, không phải hiện tượng đồng âm.",
        "Từ \"chân\" trong câu này có nghĩa rõ ràng, là nghĩa chuyển.",
      ],
    },
  },
  {
    id: "nt-04-fill-1",
    topicIds: ["NT-04"],
    level: "M2",
    questionType: "fill",
    prompt:
      "Điền từ còn thiếu: Khác với từ đồng âm, các nghĩa của từ nhiều nghĩa luôn có ___ với nhau.",
    explanation: "Nghĩa chuyển của từ nhiều nghĩa luôn có liên hệ với nghĩa gốc — đây là điểm khác biệt so với từ đồng âm.",
    fill: { acceptedAnswers: ["liên hệ"], strictMode: false, isSet: false },
  },
  {
    id: "nt-04-mcq-3",
    topicIds: ["NT-04"],
    level: "M1",
    questionType: "mcq",
    prompt: "Nghĩa gốc của một từ là gì?",
    explanation: "Nghĩa gốc là nghĩa đầu tiên, cơ bản, quen thuộc nhất của từ, làm cơ sở để tạo ra các nghĩa chuyển.",
    mcq: {
      options: [
        "Nghĩa đầu tiên, cơ bản, quen thuộc nhất của từ",
        "Nghĩa được suy ra, phát triển từ một nghĩa khác",
        "Nghĩa hoàn toàn không liên quan gì đến các nghĩa khác",
        "Nghĩa chỉ dùng trong văn nói",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là định nghĩa của nghĩa gốc.",
        "Đây là định nghĩa của nghĩa chuyển.",
        "Đây là đặc điểm của từ đồng âm (NT-03), không phải nghĩa gốc/nghĩa chuyển.",
        "Nghĩa gốc không giới hạn chỉ dùng trong văn nói.",
      ],
    },
  },
  {
    id: "nt-04-mcq-4",
    topicIds: ["NT-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Mũi kim rất nhọn.", từ "mũi" được dùng với nghĩa gì?',
    explanation: "\"Mũi kim\" chỉ phần đầu nhọn của kim, có liên hệ với nghĩa gốc \"mũi người\" (bộ phận nhô ra ở đầu) — là nghĩa chuyển.",
    mcq: {
      options: ["Nghĩa gốc", "Nghĩa chuyển", "Nghĩa đồng âm", "Không xác định được"],
      answerIndex: 1,
      distractorNotes: [
        "Nghĩa gốc của \"mũi\" là bộ phận trên khuôn mặt dùng để thở, ngửi.",
        "Đúng — \"mũi kim\" được suy ra từ nghĩa gốc, có liên hệ về hình dáng (phần nhô ra, nhọn).",
        "\"Mũi\" ở đây vẫn liên hệ với nghĩa gốc, không phải đồng âm.",
        "Có thể xác định được đây là nghĩa chuyển dựa vào sự liên hệ với nghĩa gốc.",
      ],
    },
  },
  {
    id: "nt-04-fill-2",
    topicIds: ["NT-04"],
    level: "M1",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: "Miệng giếng" là nghĩa ___ của từ "miệng" (nghĩa gốc là bộ phận trên khuôn mặt).',
    explanation: "\"Miệng giếng\" là nghĩa chuyển, được suy ra từ nghĩa gốc (miệng người), chỉ phần trên cùng, nơi mở ra của giếng.",
    fill: { acceptedAnswers: ["chuyển"], strictMode: false, isSet: false },
  },
  {
    id: "nt-04-mcq-5",
    topicIds: ["NT-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "lá" trong các cụm nào dưới đây được dùng theo nghĩa CHUYỂN?',
    explanation: "\"Lá thư\", \"lá cờ\" dùng \"lá\" theo nghĩa chuyển (vật mỏng, giống hình lá cây), khác với nghĩa gốc là bộ phận của cây.",
    mcq: {
      options: ["lá cây xanh", "lá thư", "lá của cây bàng", "chiếc lá vàng rơi"],
      answerIndex: 1,
      distractorNotes: [
        "\"Lá cây\" dùng đúng nghĩa gốc (bộ phận của cây).",
        "Đúng — \"lá thư\" dùng \"lá\" theo nghĩa chuyển (vật mỏng, phẳng giống hình lá cây).",
        "Đây dùng đúng nghĩa gốc (bộ phận của cây).",
        "Đây dùng đúng nghĩa gốc (bộ phận của cây).",
      ],
    },
  },
  {
    id: "nt-04-mcq-6",
    topicIds: ["NT-04"],
    level: "M2",
    questionType: "mcq",
    prompt: "Làm thế nào để xác định một nghĩa là nghĩa gốc hay nghĩa chuyển?",
    explanation: "Cần xem nghĩa nào cơ bản, quen thuộc nhất (nghĩa gốc), và nghĩa nào được suy ra, có liên hệ với nghĩa gốc đó (nghĩa chuyển).",
    mcq: {
      options: [
        "Xem từ nào xuất hiện trước trong câu",
        "Xem nghĩa nào cơ bản, quen thuộc nhất và nghĩa nào được suy ra có liên hệ với nghĩa đó",
        "Đếm số âm tiết của từ",
        "Xem từ đó có bao nhiêu chữ cái",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Vị trí trong câu không quyết định nghĩa gốc/nghĩa chuyển.",
        "Đúng — đây là cách xác định nghĩa gốc và nghĩa chuyển.",
        "Số âm tiết không liên quan đến việc xác định nghĩa gốc/nghĩa chuyển.",
        "Số chữ cái không liên quan đến việc xác định nghĩa gốc/nghĩa chuyển.",
      ],
    },
  },
  {
    id: "nt-04-match-1",
    topicIds: ["NT-04"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi cụm từ ở cột trái với đúng loại nghĩa của từ \"chân\" ở cột phải.",
    explanation: "\"Chân người\" — nghĩa gốc; \"chân bàn\", \"chân núi\" — nghĩa chuyển (có liên hệ về vị trí/chức năng đỡ, ở dưới cùng).",
    match: {
      leftItems: [
        { id: "l1", label: "Đôi chân của em" },
        { id: "l2", label: "Chân bàn" },
        { id: "l3", label: "Chân núi" },
      ],
      rightItems: [
        { id: "r1", label: "Nghĩa gốc" },
        { id: "r2", label: "Nghĩa chuyển" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r1" },
        { leftId: "l2", rightId: "r2" },
        { leftId: "l3", rightId: "r2" },
      ],
    },
  },
  {
    id: "nt-04-mcq-7",
    topicIds: ["NT-04"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Từ "ăn" trong câu "Chiếc xe này ăn xăng lắm." được dùng với nghĩa gì?',
    explanation: "\"Ăn xăng\" (tiêu tốn nhiều xăng) là nghĩa chuyển của \"ăn\", suy ra từ nghĩa gốc \"ăn\" (đưa thức ăn vào cơ thể), có liên hệ về ý nghĩa \"tiêu thụ, hấp thụ\".",
    mcq: {
      options: ["Nghĩa gốc", "Nghĩa chuyển", "Nghĩa đồng âm", "Không có nghĩa nào phù hợp"],
      answerIndex: 1,
      distractorNotes: [
        "Nghĩa gốc của \"ăn\" là đưa thức ăn vào cơ thể qua miệng.",
        "Đúng — \"ăn xăng\" là nghĩa chuyển, có liên hệ với ý nghĩa \"tiêu thụ\" của nghĩa gốc.",
        "\"Ăn\" ở đây vẫn liên hệ với nghĩa gốc, không phải đồng âm.",
        "Câu này vẫn có nghĩa phù hợp, là nghĩa chuyển.",
      ],
    },
  },
  {
    id: "nt-04-mcq-8",
    topicIds: ["NT-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "đầu" trong câu "Đầu làng có một cây đa cổ thụ." được dùng với nghĩa gì?',
    explanation: "\"Đầu làng\" chỉ vị trí bắt đầu của làng, có liên hệ với nghĩa gốc \"đầu người\" (phần trên cùng, phần đầu tiên) — là nghĩa chuyển.",
    mcq: {
      options: ["Nghĩa gốc", "Nghĩa chuyển", "Nghĩa đồng âm", "Không xác định được"],
      answerIndex: 1,
      distractorNotes: [
        "Nghĩa gốc của \"đầu\" là bộ phận trên cùng cơ thể người/động vật.",
        "Đúng — \"đầu làng\" được suy ra từ nghĩa gốc, có liên hệ về vị trí (điểm bắt đầu).",
        "\"Đầu\" ở đây vẫn liên hệ với nghĩa gốc, không phải đồng âm.",
        "Có thể xác định đây là nghĩa chuyển dựa vào sự liên hệ với nghĩa gốc.",
      ],
    },
  },
  {
    id: "nt-04-fill-3",
    topicIds: ["NT-04"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: "Cổ áo" là nghĩa ___ của từ "cổ" (nghĩa gốc là bộ phận nối đầu và thân).',
    explanation: "\"Cổ áo\" là nghĩa chuyển, được suy ra từ nghĩa gốc, chỉ phần trên của áo (vị trí tương ứng với cổ người).",
    fill: { acceptedAnswers: ["chuyển"], strictMode: false, isSet: false },
  },
];
