import type { Exercise } from "@/data-access/types";

// TC-01 — Tiếng và cấu tạo của tiếng. Ví dụ tự biên soạn (Mục 10.1 hướng B).
export const TC01_EXERCISES: Exercise[] = [
  {
    id: "tc-01-mcq-1",
    topicIds: ["TC-01"],
    level: "M1",
    questionType: "mcq",
    prompt: "Mỗi tiếng trong tiếng Việt có cấu tạo gồm mấy phần?",
    explanation: "Mỗi tiếng gồm 3 phần: âm đầu (có thể vắng), vần và thanh điệu.",
    mcq: {
      options: ["2 phần: âm đầu và vần", "3 phần: âm đầu, vần và thanh điệu", "4 phần", "Chỉ có vần"],
      answerIndex: 1,
      distractorNotes: [
        "Thiếu thanh điệu — mỗi tiếng đều mang một thanh điệu nhất định.",
        "Đúng — tiếng gồm âm đầu (có thể vắng), vần và thanh điệu.",
        "Tiếng chỉ có 3 phần, không phải 4.",
        "Ngoài vần, tiếng còn có âm đầu (có thể vắng) và thanh điệu.",
      ],
    },
  },
  {
    id: "tc-01-mcq-2",
    topicIds: ["TC-01"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Tiếng "ăn" có âm đầu là gì?',
    explanation: "Tiếng \"ăn\" không có phụ âm đầu — chỉ gồm vần \"ăn\" và thanh ngang.",
    mcq: {
      options: ["â", "ă", "n", "Không có âm đầu"],
      answerIndex: 3,
      distractorNotes: [
        "\"â\" không xuất hiện trong tiếng \"ăn\".",
        "\"ă\" là một phần của âm chính trong vần, không phải âm đầu.",
        "\"n\" là âm cuối của vần, không phải âm đầu.",
        "Đúng — tiếng \"ăn\" bắt đầu ngay bằng vần, không có phụ âm đầu.",
      ],
    },
  },
  {
    id: "tc-01-fill-1",
    topicIds: ["TC-01"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Tiếng "toán" có âm đầu là "t", vần là "oán" và mang thanh ___.',
    explanation: "Dấu sắc trên chữ \"a\" trong \"oán\" cho biết tiếng \"toán\" mang thanh sắc.",
    fill: { acceptedAnswers: ["sắc"], strictMode: false, isSet: false },
  },
  {
    id: "tc-01-mcq-3",
    topicIds: ["TC-01"],
    level: "M1",
    questionType: "mcq",
    prompt: "Vần của một tiếng gồm những bộ phận nào?",
    explanation: "Vần gồm âm đệm (có thể vắng), âm chính (bắt buộc có) và âm cuối (có thể vắng).",
    mcq: {
      options: ["Chỉ có âm chính", "Âm đệm, âm chính, âm cuối", "Chỉ có âm đầu và âm chính", "Âm đầu, âm đệm, âm cuối"],
      answerIndex: 1,
      distractorNotes: [
        "Vần có thể có thêm âm đệm và âm cuối, không chỉ âm chính.",
        "Đúng — vần gồm âm đệm (có thể vắng), âm chính (bắt buộc), âm cuối (có thể vắng).",
        "Âm đầu không thuộc phần vần, mà là phần riêng của tiếng.",
        "Âm chính là bộ phận bắt buộc phải có của vần, không thể thiếu.",
      ],
    },
  },
  {
    id: "tc-01-mcq-4",
    topicIds: ["TC-01"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Tiếng "loan" có âm đệm là gì?',
    explanation: "Trong \"loan\", chữ \"o\" đứng giữa \"l\" và \"an\" là âm đệm, \"a\" là âm chính, \"n\" là âm cuối.",
    mcq: {
      options: ["l", "o", "a", "n"],
      answerIndex: 1,
      distractorNotes: [
        "\"l\" là âm đầu, không phải âm đệm.",
        "Đúng — \"o\" là âm đệm, đứng giữa âm đầu và âm chính.",
        "\"a\" là âm chính, không phải âm đệm.",
        "\"n\" là âm cuối, không phải âm đệm.",
      ],
    },
  },
  {
    id: "tc-01-mcq-5",
    topicIds: ["TC-01"],
    level: "M2",
    questionType: "mcq",
    prompt: "Bộ phận nào của tiếng là bắt buộc phải có, không thể vắng mặt?",
    explanation: "Âm chính và thanh điệu là hai bộ phận bắt buộc phải có ở mọi tiếng; âm đầu và âm đệm có thể vắng.",
    mcq: {
      options: ["Âm đầu", "Âm đệm", "Âm chính và thanh điệu", "Âm cuối"],
      answerIndex: 2,
      distractorNotes: [
        "Âm đầu có thể vắng, ví dụ tiếng \"ăn\".",
        "Âm đệm có thể vắng ở phần lớn các tiếng.",
        "Đúng — mọi tiếng đều phải có âm chính và một thanh điệu.",
        "Âm cuối có thể vắng, ví dụ tiếng \"ba\".",
      ],
    },
  },
  {
    id: "tc-01-fill-2",
    topicIds: ["TC-01"],
    level: "M1",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Tiếng "ơi" không có âm đầu, chỉ gồm vần "ơi" và thanh ___.',
    explanation: "Tiếng \"ơi\" không có dấu thanh, mang thanh ngang (thanh bằng, không dấu).",
    fill: { acceptedAnswers: ["ngang"], strictMode: false, isSet: false },
  },
  {
    id: "tc-01-mcq-6",
    topicIds: ["TC-01"],
    level: "M2",
    questionType: "mcq",
    prompt: "Tiếng Việt có bao nhiêu thanh điệu?",
    explanation: "Tiếng Việt có 6 thanh điệu: ngang (không dấu), huyền, sắc, hỏi, ngã, nặng.",
    mcq: {
      options: ["4 thanh", "5 thanh", "6 thanh", "7 thanh"],
      answerIndex: 2,
      distractorNotes: [
        "Thiếu 2 thanh so với thực tế.",
        "Thiếu 1 thanh so với thực tế.",
        "Đúng — 6 thanh: ngang, huyền, sắc, hỏi, ngã, nặng.",
        "Tiếng Việt chỉ có 6 thanh, không phải 7.",
      ],
    },
  },
  {
    id: "tc-01-match-1",
    topicIds: ["TC-01"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi tiếng ở cột trái với âm đầu đúng của tiếng đó ở cột phải.",
    explanation: "\"toán\" — âm đầu \"t\"; \"nhà\" — âm đầu \"nh\"; \"ăn\" — không có âm đầu.",
    match: {
      leftItems: [
        { id: "l1", label: "toán" },
        { id: "l2", label: "nhà" },
        { id: "l3", label: "ăn" },
      ],
      rightItems: [
        { id: "r1", label: "Không có âm đầu" },
        { id: "r2", label: "t" },
        { id: "r3", label: "nh" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r3" },
        { leftId: "l3", rightId: "r1" },
      ],
    },
  },
  {
    id: "tc-01-mcq-7",
    topicIds: ["TC-01"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Tiếng "nguyễn" có âm cuối là gì?',
    explanation: "Trong \"nguyễn\": âm đầu \"ng\", âm đệm \"u\", âm chính \"yê\", âm cuối \"n\", thanh ngã.",
    mcq: {
      options: ["ng", "u", "yê", "n"],
      answerIndex: 3,
      distractorNotes: [
        "\"ng\" là âm đầu, không phải âm cuối.",
        "\"u\" là âm đệm, không phải âm cuối.",
        "\"yê\" là âm chính, không phải âm cuối.",
        "Đúng — \"n\" đứng cuối vần, là âm cuối.",
      ],
    },
  },
  {
    id: "tc-01-mcq-8",
    topicIds: ["TC-01"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Tiếng "hoa" có mấy thành phần trong vần?',
    explanation: "Vần \"oa\" gồm âm đệm \"o\" và âm chính \"a\" — 2 thành phần (không có âm cuối).",
    mcq: {
      options: ["1 thành phần", "2 thành phần", "3 thành phần", "4 thành phần"],
      answerIndex: 1,
      distractorNotes: [
        "Vần \"oa\" có cả âm đệm và âm chính, nhiều hơn 1 thành phần.",
        "Đúng — vần \"oa\" gồm âm đệm \"o\" và âm chính \"a\".",
        "Vần này không có âm cuối, nên chỉ có 2 thành phần.",
        "Vần chỉ có tối đa 3 thành phần (đệm, chính, cuối), tiếng này chỉ có 2.",
      ],
    },
  },
  {
    id: "tc-01-fill-3",
    topicIds: ["TC-01"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Tiếng "mèo" có âm đầu là "m" và mang thanh ___.',
    explanation: "Tiếng \"mèo\" mang dấu huyền, là thanh huyền.",
    fill: { acceptedAnswers: ["huyền"], strictMode: false, isSet: false },
  },
];
