import type { Exercise } from "@/data-access/types";

// TC-03 — Từ ghép: ghép tổng hợp và ghép phân loại. Ví dụ tự biên soạn (Mục
// 10.1 hướng B), cố ý tránh mọi từ trong DISPUTED_WORDS (FR-D03/D04).
export const TC03_EXERCISES: Exercise[] = [
  {
    id: "tc-03-mcq-1",
    topicIds: ["TC-03"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Từ "quần áo" là từ ghép loại nào?',
    explanation: "\"Quần\" và \"áo\" đều là trang phục, có nghĩa gần nhau và bình đẳng — đây là từ ghép tổng hợp.",
    mcq: {
      options: ["Ghép tổng hợp", "Ghép phân loại", "Từ láy", "Từ đơn"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"quần\" và \"áo\" bình đẳng về nghĩa, cùng chỉ chung \"trang phục\".",
        "Ghép phân loại cần một tiếng thu hẹp nghĩa của tiếng kia, ở đây không có quan hệ đó.",
        "Cả hai tiếng đều có nghĩa riêng rõ ràng, đây là từ ghép chứ không phải từ láy.",
        "\"Quần áo\" gồm hai tiếng, không phải từ đơn.",
      ],
    },
  },
  {
    id: "tc-03-mcq-2",
    topicIds: ["TC-03"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "xe đạp" là từ ghép loại nào?',
    explanation: "\"Đạp\" thu hẹp, phân loại rõ cho \"xe\" (loại xe đi bằng cách đạp) — đây là từ ghép phân loại.",
    mcq: {
      options: ["Ghép tổng hợp", "Ghép phân loại", "Từ láy", "Từ đơn"],
      answerIndex: 1,
      distractorNotes: [
        "Ghép tổng hợp cần hai tiếng bình đẳng về nghĩa, ở đây \"đạp\" đang bổ sung, phân loại cho \"xe\".",
        "Đúng — \"đạp\" phân loại cụ thể cho \"xe\", khác với xe máy, xe hơi.",
        "Cả hai tiếng đều có nghĩa riêng rõ ràng, đây là từ ghép chứ không phải từ láy.",
        "\"Xe đạp\" gồm hai tiếng, không phải từ đơn.",
      ],
    },
  },
  {
    id: "tc-03-fill-1",
    topicIds: ["TC-03"],
    level: "M1",
    questionType: "fill",
    prompt: "Điền từ còn thiếu: Từ ghép là từ được tạo thành bằng cách ghép các tiếng có quan hệ với nhau về ___.",
    explanation: "Từ ghép có quan hệ về nghĩa giữa các tiếng — khác với từ láy có quan hệ về âm.",
    fill: { acceptedAnswers: ["nghĩa"], strictMode: false, isSet: false },
  },
  {
    id: "tc-03-mcq-3",
    topicIds: ["TC-03"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Trong hai từ "bàn ghế" và "hoa hồng", từ nào là từ ghép phân loại?',
    explanation: "\"Bàn ghế\" là ghép tổng hợp (hai đồ vật bình đẳng); \"hoa hồng\" là ghép phân loại (\"hồng\" phân loại cụ thể cho \"hoa\").",
    mcq: {
      options: ["Bàn ghế", "Hoa hồng", "Cả hai đều là ghép tổng hợp", "Cả hai đều là ghép phân loại"],
      answerIndex: 1,
      distractorNotes: [
        "\"Bàn ghế\" là ghép tổng hợp — hai đồ vật bình đẳng, cùng chỉ chung \"đồ đạc\".",
        "Đúng — \"hồng\" thu hẹp, phân loại cụ thể cho \"hoa\", chỉ riêng loại hoa hồng.",
        "\"Hoa hồng\" là ghép phân loại, không phải ghép tổng hợp.",
        "\"Bàn ghế\" là ghép tổng hợp, không phải ghép phân loại.",
      ],
    },
  },
  {
    id: "tc-03-mcq-4",
    topicIds: ["TC-03"],
    level: "M1",
    questionType: "mcq",
    prompt: "Từ ghép tổng hợp có đặc điểm gì?",
    explanation: "Từ ghép tổng hợp có các tiếng gần nghĩa hoặc cùng loại, bình đẳng về nghĩa, chỉ ý nghĩa khái quát.",
    mcq: {
      options: [
        "Các tiếng bình đẳng về nghĩa, chỉ ý khái quát",
        "Một tiếng phân loại, thu hẹp nghĩa cho tiếng kia",
        "Các tiếng có quan hệ về âm thanh",
        "Chỉ có 1 tiếng có nghĩa",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là đặc điểm của từ ghép tổng hợp.",
        "Đây là đặc điểm của từ ghép phân loại.",
        "Đây là đặc điểm của từ láy, không phải từ ghép.",
        "Từ ghép thường có cả hai tiếng đều có nghĩa riêng.",
      ],
    },
  },
  {
    id: "tc-03-mcq-5",
    topicIds: ["TC-03"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "nhà cửa" là từ ghép loại nào?',
    explanation: "\"Nhà\" và \"cửa\" đều liên quan đến nơi ở, bình đẳng về nghĩa, chỉ ý khái quát \"chỗ ở nói chung\" — là ghép tổng hợp.",
    mcq: {
      options: ["Ghép tổng hợp", "Ghép phân loại", "Từ láy", "Từ đơn"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"nhà\" và \"cửa\" bình đẳng về nghĩa, cùng chỉ chung nơi ở.",
        "Không có tiếng nào phân loại, thu hẹp nghĩa cho tiếng còn lại.",
        "Cả hai tiếng đều có nghĩa riêng, đây là từ ghép, không phải từ láy.",
        "\"Nhà cửa\" gồm hai tiếng, không phải từ đơn.",
      ],
    },
  },
  {
    id: "tc-03-mcq-6",
    topicIds: ["TC-03"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "áo dài" là từ ghép loại nào?',
    explanation: "\"Dài\" thu hẹp, phân loại cho \"áo\" (loại áo dài, khác áo ngắn, áo khoác...) — là ghép phân loại.",
    mcq: {
      options: ["Ghép tổng hợp", "Ghép phân loại", "Từ láy", "Không phải từ ghép"],
      answerIndex: 1,
      distractorNotes: [
        "\"Dài\" không bình đẳng về nghĩa với \"áo\", mà đang bổ sung, phân loại cho \"áo\".",
        "Đúng — \"dài\" phân loại cụ thể loại áo, khác các loại áo khác.",
        "Cả hai tiếng đều có nghĩa riêng rõ ràng, đây là từ ghép.",
        "\"Áo dài\" là một từ ghép, không phải cụm từ ngẫu nhiên.",
      ],
    },
  },
  {
    id: "tc-03-fill-2",
    topicIds: ["TC-03"],
    level: "M1",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Từ "xe máy" là từ ghép ___ vì tiếng "máy" thu hẹp, phân loại cho "xe".',
    explanation: "\"Máy\" phân loại cụ thể loại xe (khác xe đạp, xe hơi), nên đây là từ ghép phân loại.",
    fill: { acceptedAnswers: ["phân loại"], strictMode: false, isSet: false },
  },
  {
    id: "tc-03-mcq-7",
    topicIds: ["TC-03"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "ăn uống" là từ ghép loại nào?',
    explanation: "\"Ăn\" và \"uống\" đều là hoạt động liên quan đến việc nạp thức ăn, đồ uống, bình đẳng về nghĩa — là ghép tổng hợp.",
    mcq: {
      options: ["Ghép tổng hợp", "Ghép phân loại", "Từ láy", "Từ đơn"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"ăn\" và \"uống\" bình đẳng về nghĩa, cùng chỉ chung hoạt động ăn uống.",
        "Không có tiếng nào phân loại, thu hẹp nghĩa cho tiếng còn lại.",
        "Cả hai tiếng đều có nghĩa riêng, là từ ghép, không phải từ láy.",
        "\"Ăn uống\" gồm hai tiếng, không phải từ đơn.",
      ],
    },
  },
  {
    id: "tc-03-match-1",
    topicIds: ["TC-03"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi từ ghép ở cột trái với đúng loại (tổng hợp/phân loại) ở cột phải.",
    explanation: "\"Bàn ghế\", \"ăn uống\" là ghép tổng hợp (các tiếng bình đẳng); \"xe đạp\", \"hoa hồng\" là ghép phân loại (một tiếng thu hẹp nghĩa).",
    match: {
      leftItems: [
        { id: "l1", label: "Bàn ghế" },
        { id: "l2", label: "Xe đạp" },
        { id: "l3", label: "Ăn uống" },
        { id: "l4", label: "Hoa hồng" },
      ],
      rightItems: [
        { id: "r1", label: "Ghép tổng hợp" },
        { id: "r2", label: "Ghép phân loại" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r1" },
        { leftId: "l2", rightId: "r2" },
        { leftId: "l3", rightId: "r1" },
        { leftId: "l4", rightId: "r2" },
      ],
    },
  },
  {
    id: "tc-03-mcq-8",
    topicIds: ["TC-03"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Vì sao "quần áo" được coi là từ ghép, không phải từ láy?',
    explanation: "Cả \"quần\" và \"áo\" đều có nghĩa riêng, độc lập khi đứng một mình — đây là dấu hiệu của từ ghép, khác với từ láy (các tiếng thường không có nghĩa riêng khi tách ra).",
    mcq: {
      options: [
        "Vì cả hai tiếng đều có nghĩa riêng khi đứng độc lập",
        "Vì hai tiếng có âm đầu giống nhau",
        "Vì hai tiếng có phần vần giống nhau",
        "Vì từ này có 2 tiếng",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây chính là dấu hiệu phân biệt từ ghép với từ láy.",
        "\"Quần\" và \"áo\" không có âm đầu giống nhau (qu và á khác nhau).",
        "\"Quần\" và \"áo\" không có phần vần giống nhau.",
        "Có 2 tiếng chỉ cho biết đây là từ phức, chưa xác định là ghép hay láy.",
      ],
    },
  },
  {
    id: "tc-03-mcq-9",
    topicIds: ["TC-03"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "cá vàng" là từ ghép loại nào?',
    explanation: "\"Vàng\" phân loại cụ thể cho \"cá\" (loại cá màu vàng, khác cá chép, cá rô...) — là ghép phân loại.",
    mcq: {
      options: ["Ghép tổng hợp", "Ghép phân loại", "Từ láy", "Từ đơn"],
      answerIndex: 1,
      distractorNotes: [
        "\"Vàng\" không bình đẳng về nghĩa với \"cá\", mà đang phân loại cho \"cá\".",
        "Đúng — \"vàng\" phân loại cụ thể loại cá.",
        "Cả hai tiếng đều có nghĩa riêng rõ ràng, đây là từ ghép.",
        "\"Cá vàng\" gồm hai tiếng, không phải từ đơn.",
      ],
    },
  },
];
