import type { Exercise } from "@/data-access/types";

// TC-02 — Từ, từ đơn và từ phức. Ví dụ tự biên soạn (Mục 10.1 hướng B).
export const TC02_EXERCISES: Exercise[] = [
  {
    id: "tc-02-mcq-1",
    topicIds: ["TC-02"],
    level: "M1",
    questionType: "mcq",
    prompt: "Từ đơn là gì?",
    explanation: "Từ đơn là từ chỉ gồm 1 tiếng.",
    mcq: {
      options: ["Từ gồm 1 tiếng", "Từ gồm 2 tiếng trở lên", "Từ có nghĩa mơ hồ", "Từ chỉ dùng trong văn nói"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — từ đơn chỉ có 1 tiếng.",
        "Đây là định nghĩa của từ phức, không phải từ đơn.",
        "Từ đơn vẫn có nghĩa rõ ràng, không mơ hồ.",
        "Từ đơn được dùng cả trong văn nói lẫn văn viết.",
      ],
    },
  },
  {
    id: "tc-02-mcq-2",
    topicIds: ["TC-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Bạn Lan có mái tóc dài và đôi mắt sáng.", từ nào dưới đây là từ phức?',
    explanation: "\"Mái tóc\" gồm 2 tiếng ghép lại mang một nghĩa — đây là từ phức. \"Có\", \"và\" là từ đơn.",
    mcq: {
      options: ["có", "và", "mái tóc", "Lan"],
      answerIndex: 2,
      distractorNotes: [
        "\"Có\" chỉ gồm 1 tiếng, là từ đơn.",
        "\"Và\" chỉ gồm 1 tiếng, là từ đơn.",
        "Đúng — \"mái tóc\" gồm 2 tiếng ghép lại, là từ phức.",
        "\"Lan\" là tên riêng, 1 tiếng, là từ đơn.",
      ],
    },
  },
  {
    id: "tc-02-fill-1",
    topicIds: ["TC-02"],
    level: "M2",
    questionType: "fill",
    prompt: "Điền từ còn thiếu: Từ phức được tạo thành từ ___ tiếng trở lên.",
    explanation: "Từ phức gồm 2 tiếng trở lên, khác với từ đơn chỉ có 1 tiếng.",
    fill: { acceptedAnswers: ["2", "hai"], strictMode: false, isSet: false },
  },
  {
    id: "tc-02-mcq-3",
    topicIds: ["TC-02"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Trong nhóm từ: "nhà, sách vở, đi, xinh đẹp, mưa" có bao nhiêu từ phức?',
    explanation: "\"Sách vở\" và \"xinh đẹp\" đều gồm 2 tiếng — là từ phức. \"Nhà\", \"đi\", \"mưa\" mỗi từ chỉ có 1 tiếng — là từ đơn.",
    mcq: {
      options: ["1", "2", "3", "4"],
      answerIndex: 1,
      distractorNotes: [
        "Có 2 từ phức trong nhóm này, không phải 1.",
        "Đúng — \"sách vở\" và \"xinh đẹp\" là 2 từ phức.",
        "\"Nhà\", \"đi\", \"mưa\" đều là từ đơn (1 tiếng), không tính vào từ phức.",
        "Cả nhóm chỉ có 5 từ, trong đó chỉ 2 từ là từ phức.",
      ],
    },
  },
  {
    id: "tc-02-mcq-4",
    topicIds: ["TC-02"],
    level: "M1",
    questionType: "mcq",
    prompt: "Từ là gì?",
    explanation: "Từ là đơn vị nhỏ nhất dùng để đặt câu, có nghĩa hoàn chỉnh.",
    mcq: {
      options: [
        "Đơn vị nhỏ nhất dùng để đặt câu, có nghĩa hoàn chỉnh",
        "Đơn vị phát âm nhỏ nhất",
        "Chỉ những từ có 2 tiếng trở lên",
        "Chỉ những từ chỉ sự vật",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là định nghĩa của từ.",
        "Đây là định nghĩa của tiếng (TC-01), không phải từ.",
        "Từ có thể là từ đơn (1 tiếng) hoặc từ phức (2 tiếng trở lên).",
        "Từ có nhiều loại nghĩa khác nhau, không chỉ chỉ sự vật.",
      ],
    },
  },
  {
    id: "tc-02-mcq-5",
    topicIds: ["TC-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu "Em rất yêu thương gia đình." có mấy từ đơn?',
    explanation: "\"Em\", \"rất\" là 2 từ đơn (mỗi từ 1 tiếng). \"Yêu thương\" và \"gia đình\" là từ phức (mỗi từ 2 tiếng).",
    mcq: {
      options: ["1", "2", "3", "4"],
      answerIndex: 1,
      distractorNotes: [
        "Có 2 từ đơn, không phải 1.",
        "Đúng — \"em\" và \"rất\" là 2 từ đơn.",
        "Chỉ có 2 từ đơn trong câu này.",
        "Câu chỉ có 2 từ đơn và 2 từ phức, không phải 4 từ đơn.",
      ],
    },
  },
  {
    id: "tc-02-fill-2",
    topicIds: ["TC-02"],
    level: "M1",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Từ "bàn ghế" là từ ___ vì gồm 2 tiếng.',
    explanation: "\"Bàn ghế\" gồm 2 tiếng nên là từ phức.",
    fill: { acceptedAnswers: ["phức"], strictMode: false, isSet: false },
  },
  {
    id: "tc-02-mcq-6",
    topicIds: ["TC-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây là từ đơn?',
    explanation: "\"Đẹp\" chỉ có 1 tiếng, là từ đơn. Các từ còn lại đều có 2 tiếng trở lên.",
    mcq: {
      options: ["xinh đẹp", "đẹp", "tươi đẹp", "đẹp đẽ"],
      answerIndex: 1,
      distractorNotes: [
        "\"Xinh đẹp\" gồm 2 tiếng, là từ phức.",
        "Đúng — \"đẹp\" chỉ có 1 tiếng, là từ đơn.",
        "\"Tươi đẹp\" gồm 2 tiếng, là từ phức.",
        "\"Đẹp đẽ\" gồm 2 tiếng, là từ phức.",
      ],
    },
  },
  {
    id: "tc-02-mcq-7",
    topicIds: ["TC-02"],
    level: "M2",
    questionType: "mcq",
    prompt: "Từ phức bao gồm những loại nào?",
    explanation: "Từ phức gồm hai loại chính: từ ghép (các tiếng có quan hệ về nghĩa) và từ láy (các tiếng có quan hệ về âm) — xem chi tiết TC-03, TC-04.",
    mcq: {
      options: ["Từ ghép và từ láy", "Chỉ có từ ghép", "Chỉ có từ láy", "Danh từ và động từ"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — từ phức gồm từ ghép và từ láy.",
        "Từ phức còn bao gồm cả từ láy.",
        "Từ phức còn bao gồm cả từ ghép.",
        "Danh từ, động từ là phân loại theo từ loại (TL), không phải phân loại từ đơn/từ phức.",
      ],
    },
  },
  {
    id: "tc-02-match-1",
    topicIds: ["TC-02"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi từ ở cột trái với đúng loại (từ đơn/từ phức) ở cột phải.",
    explanation: "\"Đi\" và \"mưa\" là từ đơn (1 tiếng); \"chăm chỉ\" và \"nhà cửa\" là từ phức (2 tiếng).",
    match: {
      leftItems: [
        { id: "l1", label: "đi" },
        { id: "l2", label: "chăm chỉ" },
        { id: "l3", label: "mưa" },
        { id: "l4", label: "nhà cửa" },
      ],
      rightItems: [
        { id: "r1", label: "Từ đơn" },
        { id: "r2", label: "Từ phức" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r1" },
        { leftId: "l2", rightId: "r2" },
        { leftId: "l3", rightId: "r1" },
        { leftId: "l4", rightId: "r2" },
      ],
    },
  },
  {
    id: "tc-02-mcq-8",
    topicIds: ["TC-02"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Câu "Bạn Hoa học giỏi và chăm ngoan." có mấy từ (không tính dấu câu)?',
    explanation: "Các từ: \"Bạn\", \"Hoa\", \"học\", \"giỏi\", \"và\", \"chăm ngoan\" — 6 từ (trong đó \"chăm ngoan\" là 1 từ phức gồm 2 tiếng).",
    mcq: {
      options: ["5 từ", "6 từ", "7 từ", "8 từ"],
      answerIndex: 1,
      distractorNotes: [
        "Thiếu 1 từ so với thực tế.",
        "Đúng — 6 từ: Bạn, Hoa, học, giỏi, và, chăm ngoan (chăm ngoan tính là 1 từ phức).",
        "Nếu tính \"chăm\" và \"ngoan\" là 2 từ riêng sẽ sai — đây là 1 từ phức duy nhất.",
        "Câu này có 7 tiếng nhưng chỉ 6 từ, vì \"chăm ngoan\" là 1 từ gồm 2 tiếng.",
      ],
    },
  },
  {
    id: "tc-02-mcq-9",
    topicIds: ["TC-02"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây là từ đơn?',
    explanation: "\"Hoa\" chỉ có 1 tiếng, là từ đơn.",
    mcq: {
      options: ["hoa", "hoa quả", "cây cối", "vườn tược"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"hoa\" chỉ có 1 tiếng, là từ đơn.",
        "\"Hoa quả\" gồm 2 tiếng, là từ phức.",
        "\"Cây cối\" gồm 2 tiếng, là từ phức.",
        "\"Vườn tược\" gồm 2 tiếng, là từ phức.",
      ],
    },
  },
];
