import type { Exercise } from "@/data-access/types";

// TC-04 — Từ láy: láy âm, láy vần, láy toàn bộ. Ví dụ tự biên soạn (Mục
// 10.1 hướng B), cố ý tránh mọi từ trong DISPUTED_WORDS (FR-D03/D04).
export const TC04_EXERCISES: Exercise[] = [
  {
    id: "tc-04-mcq-1",
    topicIds: ["TC-04"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Từ "long lanh" thuộc kiểu từ láy nào?',
    explanation: "Phụ âm đầu \"l\" lặp lại ở cả hai tiếng, phần vần khác nhau — đây là láy âm.",
    mcq: {
      options: ["Láy âm", "Láy vần", "Láy toàn bộ", "Không phải từ láy"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — phụ âm đầu \"l\" của hai tiếng giống nhau.",
        "Láy vần cần phần vần giống nhau, ở đây phần vần \"ong\" và \"anh\" khác nhau.",
        "Láy toàn bộ cần lặp lại gần như nguyên vẹn cả tiếng, ở đây hai tiếng khác nhau khá nhiều.",
        "\"Long lanh\" có phụ âm đầu lặp lại, là một từ láy.",
      ],
    },
  },
  {
    id: "tc-04-mcq-2",
    topicIds: ["TC-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "lác đác" thuộc kiểu từ láy nào?',
    explanation: "Phần vần \"ac\" lặp lại ở cả hai tiếng, phụ âm đầu khác nhau — đây là láy vần.",
    mcq: {
      options: ["Láy âm", "Láy vần", "Láy toàn bộ", "Không phải từ láy"],
      answerIndex: 1,
      distractorNotes: [
        "Láy âm cần phụ âm đầu giống nhau, ở đây \"l\" và \"đ\" khác nhau.",
        "Đúng — phần vần \"ac\" của hai tiếng giống nhau.",
        "Láy toàn bộ cần lặp lại gần như nguyên vẹn cả tiếng, ở đây hai tiếng khác nhau khá nhiều.",
        "\"Lác đác\" có phần vần lặp lại, là một từ láy.",
      ],
    },
  },
  {
    id: "tc-04-fill-1",
    topicIds: ["TC-04"],
    level: "M1",
    questionType: "fill",
    prompt: "Điền từ còn thiếu: Từ láy có quan hệ với nhau về ___ giữa các tiếng, khác với từ ghép có quan hệ về nghĩa.",
    explanation: "Từ láy có quan hệ về âm (âm thanh lặp lại một phần hoặc toàn bộ) giữa các tiếng.",
    fill: { acceptedAnswers: ["âm", "âm thanh"], strictMode: false, isSet: false },
  },
  {
    id: "tc-04-mcq-3",
    topicIds: ["TC-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "xanh xanh" thuộc kiểu từ láy nào?',
    explanation: "Tiếng \"xanh\" được lặp lại gần như nguyên vẹn — đây là láy toàn bộ.",
    mcq: {
      options: ["Láy âm", "Láy vần", "Láy toàn bộ", "Từ ghép"],
      answerIndex: 2,
      distractorNotes: [
        "Láy âm chỉ lặp phụ âm đầu, ở đây lặp lại cả tiếng.",
        "Láy vần chỉ lặp phần vần, ở đây lặp lại cả tiếng.",
        "Đúng — tiếng \"xanh\" được lặp lại nguyên vẹn, đây là láy toàn bộ.",
        "Đây là từ láy vì có quan hệ về âm, không phải từ ghép.",
      ],
    },
  },
  {
    id: "tc-04-mcq-4",
    topicIds: ["TC-04"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Từ "mênh mông" thuộc kiểu từ láy nào?',
    explanation: "Phụ âm đầu \"m\" lặp lại ở cả hai tiếng, phần vần \"ênh\" và \"ông\" khác nhau — đây là láy âm.",
    mcq: {
      options: ["Láy âm", "Láy vần", "Láy toàn bộ", "Không phải từ láy"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — phụ âm đầu \"m\" của hai tiếng giống nhau.",
        "Phần vần của hai tiếng khác nhau, không phải láy vần.",
        "Hai tiếng không lặp lại nguyên vẹn, không phải láy toàn bộ.",
        "\"Mênh mông\" có phụ âm đầu lặp lại, là một từ láy.",
      ],
    },
  },
  {
    id: "tc-04-mcq-5",
    topicIds: ["TC-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "bâng khuâng" thuộc kiểu từ láy nào?',
    explanation: "Phần vần \"âng\" lặp lại ở cả hai tiếng, phụ âm đầu \"b\" và \"kh\" khác nhau — đây là láy vần.",
    mcq: {
      options: ["Láy âm", "Láy vần", "Láy toàn bộ", "Không phải từ láy"],
      answerIndex: 1,
      distractorNotes: [
        "Phụ âm đầu của hai tiếng khác nhau, không phải láy âm.",
        "Đúng — phần vần \"âng\" của hai tiếng giống nhau.",
        "Hai tiếng không lặp lại nguyên vẹn, không phải láy toàn bộ.",
        "\"Bâng khuâng\" có phần vần lặp lại, là một từ láy.",
      ],
    },
  },
  {
    id: "tc-04-fill-2",
    topicIds: ["TC-04"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Từ "nho nhỏ" thuộc kiểu láy ___ vì tiếng gốc được lặp lại gần như nguyên vẹn (chỉ đổi thanh điệu).',
    explanation: "\"Nho nhỏ\" lặp lại tiếng \"nhỏ\" gần như nguyên vẹn, chỉ đổi thanh điệu — là láy toàn bộ.",
    fill: { acceptedAnswers: ["toàn bộ"], strictMode: false, isSet: false },
  },
  {
    id: "tc-04-mcq-6",
    topicIds: ["TC-04"],
    level: "M2",
    questionType: "mcq",
    prompt: "Từ láy có tác dụng gì trong câu văn, câu thơ?",
    explanation: "Từ láy có giá trị gợi tả (hình ảnh, âm thanh) và gợi cảm (cảm xúc), làm câu văn sinh động, giàu sức biểu cảm hơn.",
    mcq: {
      options: [
        "Chỉ dùng để đếm số lượng",
        "Gợi tả, gợi cảm, làm câu văn sinh động hơn",
        "Không có tác dụng đặc biệt",
        "Chỉ dùng trong văn nói, không dùng trong văn viết",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Từ láy không có chức năng đếm số lượng.",
        "Đúng — đây là tác dụng nổi bật của từ láy (liên hệ CT-04, CT-05).",
        "Từ láy có tác dụng rõ rệt trong việc gợi hình, gợi cảm.",
        "Từ láy được dùng phổ biến trong cả văn nói và văn viết, đặc biệt trong văn miêu tả.",
      ],
    },
  },
  {
    id: "tc-04-mcq-7",
    topicIds: ["TC-04"],
    level: "M3",
    questionType: "mcq",
    prompt: 'So sánh "long lanh" (láy âm) và "lác đác" (láy vần), điểm khác nhau cơ bản là gì?',
    explanation: "\"Long lanh\" lặp phụ âm đầu (\"l\"), phần vần khác nhau. \"Lác đác\" lặp phần vần (\"ac\"), phụ âm đầu khác nhau.",
    mcq: {
      options: [
        "\"Long lanh\" lặp phụ âm đầu, \"lác đác\" lặp phần vần",
        "\"Long lanh\" lặp phần vần, \"lác đác\" lặp phụ âm đầu",
        "Cả hai đều lặp phụ âm đầu",
        "Cả hai đều lặp phần vần",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây chính là điểm khác biệt giữa láy âm và láy vần.",
        "Ngược lại với thực tế — hãy xem lại từng từ.",
        "\"Lác đác\" không lặp phụ âm đầu (\"l\" khác \"đ\").",
        "\"Long lanh\" không lặp phần vần (\"ong\" khác \"anh\").",
      ],
    },
  },
  {
    id: "tc-04-match-1",
    topicIds: ["TC-04"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi từ láy ở cột trái với đúng kiểu láy ở cột phải.",
    explanation: "\"Long lanh\", \"mênh mông\" — láy âm; \"lác đác\", \"bâng khuâng\" — láy vần; \"xanh xanh\" — láy toàn bộ.",
    match: {
      leftItems: [
        { id: "l1", label: "Long lanh" },
        { id: "l2", label: "Lác đác" },
        { id: "l3", label: "Xanh xanh" },
      ],
      rightItems: [
        { id: "r1", label: "Láy toàn bộ" },
        { id: "r2", label: "Láy âm" },
        { id: "r3", label: "Láy vần" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r3" },
        { leftId: "l3", rightId: "r1" },
      ],
    },
  },
  {
    id: "tc-04-mcq-8",
    topicIds: ["TC-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Vì sao "long lanh" được coi là từ láy, không phải từ ghép?',
    explanation: "Khi tách riêng, \"long\" và \"lanh\" không có nghĩa rõ ràng, độc lập — khác với từ ghép (các tiếng thường có nghĩa riêng). Quan hệ giữa hai tiếng ở đây là quan hệ về âm.",
    mcq: {
      options: [
        "Vì hai tiếng không có nghĩa riêng rõ ràng khi tách ra, chỉ có quan hệ về âm",
        "Vì từ này có 2 tiếng",
        "Vì từ này chỉ đặc điểm",
        "Vì từ này dùng trong văn miêu tả",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây chính là dấu hiệu phân biệt từ láy với từ ghép.",
        "Có 2 tiếng chỉ cho biết đây là từ phức, chưa xác định là ghép hay láy.",
        "Việc chỉ đặc điểm không phải dấu hiệu phân biệt láy với ghép.",
        "Từ ghép cũng có thể dùng trong văn miêu tả, đây không phải dấu hiệu phân biệt.",
      ],
    },
  },
  {
    id: "tc-04-mcq-9",
    topicIds: ["TC-04"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Từ "rì rào" thuộc kiểu từ láy nào?',
    explanation: "Phụ âm đầu \"r\" lặp lại ở cả hai tiếng, phần vần \"ì\" và \"ào\" khác nhau — đây là láy âm.",
    mcq: {
      options: ["Láy âm", "Láy vần", "Láy toàn bộ", "Không phải từ láy"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — phụ âm đầu \"r\" của hai tiếng giống nhau.",
        "Phần vần của hai tiếng khác nhau.",
        "Hai tiếng không lặp lại nguyên vẹn.",
        "\"Rì rào\" có phụ âm đầu lặp lại, là một từ láy.",
      ],
    },
  },
];
