import type { Exercise } from "@/data-access/types";

// TL-03 — Tính từ và các loại tính từ. Ví dụ tự biên soạn (Mục 10.1 hướng B).
export const TL03_EXERCISES: Exercise[] = [
  {
    id: "tl-03-mcq-1",
    topicIds: ["TL-03"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Trong câu "Bông hoa đỏ rực.", từ nào là tính từ?',
    explanation: "\"Đỏ rực\" chỉ đặc điểm màu sắc của bông hoa — là tính từ.",
    mcq: {
      options: ["Bông", "hoa", "đỏ rực", "Không có tính từ"],
      answerIndex: 2,
      distractorNotes: [
        "\"Bông\" là danh từ chỉ đơn vị, không phải tính từ.",
        "\"Hoa\" là danh từ, không phải tính từ.",
        "Đúng — \"đỏ rực\" chỉ đặc điểm màu sắc, là tính từ.",
        "Câu này có tính từ \"đỏ rực\".",
      ],
    },
  },
  {
    id: "tl-03-mcq-2",
    topicIds: ["TL-03"],
    level: "M2",
    questionType: "mcq",
    prompt: "Tính từ thường có thể kết hợp với những từ chỉ mức độ nào?",
    explanation: "Tính từ thường kết hợp được với các từ chỉ mức độ như rất, hơi, quá, lắm.",
    mcq: {
      options: ["đã, đang, sẽ", "rất, hơi, quá, lắm", "và, hoặc, nhưng", "vì, nên, nếu, thì"],
      answerIndex: 1,
      distractorNotes: [
        "Đây là các từ chỉ thời gian thường đi kèm động từ, không phải tính từ.",
        "Đúng — tính từ thường kết hợp với các từ chỉ mức độ như rất, hơi, quá, lắm.",
        "Đây là các từ nối, không phải từ chỉ mức độ cho tính từ.",
        "Đây là quan hệ từ/cặp quan hệ từ (TL-05), không phải từ chỉ mức độ.",
      ],
    },
  },
  {
    id: "tl-03-fill-1",
    topicIds: ["TL-03"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: "Bạn ấy rất chăm chỉ." — "chăm chỉ" là tính từ chỉ ___.',
    explanation: "\"Chăm chỉ\" chỉ tính cách của bạn ấy.",
    fill: { acceptedAnswers: ["tính cách"], strictMode: false, isSet: false },
  },
  {
    id: "tl-03-mcq-3",
    topicIds: ["TL-03"],
    level: "M1",
    questionType: "mcq",
    prompt: "Tính từ là gì?",
    explanation: "Tính từ là từ chỉ đặc điểm, tính chất của sự vật, hoạt động, trạng thái.",
    mcq: {
      options: [
        "Từ chỉ đặc điểm, tính chất của sự vật, hoạt động, trạng thái",
        "Từ chỉ người, sự vật, hiện tượng",
        "Từ chỉ hoạt động cụ thể",
        "Từ dùng để hỏi",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là định nghĩa của tính từ.",
        "Đây là định nghĩa của danh từ (TL-01).",
        "Đây là định nghĩa của động từ (TL-02).",
        "Tính từ không phải từ để hỏi.",
      ],
    },
  },
  {
    id: "tl-03-mcq-4",
    topicIds: ["TL-03"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây là tính từ chỉ mùi vị?',
    explanation: "\"Ngọt\" chỉ vị giác, là tính từ chỉ mùi vị.",
    mcq: {
      options: ["chạy", "ngọt", "học", "nhà"],
      answerIndex: 1,
      distractorNotes: [
        "\"Chạy\" là động từ.",
        "Đúng — \"ngọt\" chỉ vị giác, là tính từ.",
        "\"Học\" là động từ.",
        "\"Nhà\" là danh từ.",
      ],
    },
  },
  {
    id: "tl-03-fill-2",
    topicIds: ["TL-03"],
    level: "M1",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Trong câu "Trời hôm nay rất lạnh.", từ chỉ đặc điểm thời tiết là ___.',
    explanation: "\"Lạnh\" là tính từ chỉ đặc điểm thời tiết.",
    fill: { acceptedAnswers: ["lạnh"], strictMode: false, isSet: false },
  },
  {
    id: "tl-03-mcq-5",
    topicIds: ["TL-03"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Chiếc váy màu hồng rất xinh.", có mấy tính từ?',
    explanation: "Câu có 2 tính từ: \"hồng\" (màu sắc) và \"xinh\" (đặc điểm, vẻ đẹp).",
    mcq: {
      options: ["1", "2", "3", "0"],
      answerIndex: 1,
      distractorNotes: [
        "Câu có 2 tính từ, không phải 1.",
        "Đúng — \"hồng\" và \"xinh\" đều là tính từ.",
        "Câu chỉ có 2 tính từ, không phải 3.",
        "Câu có 2 tính từ: \"hồng\" và \"xinh\".",
      ],
    },
  },
  {
    id: "tl-03-mcq-6",
    topicIds: ["TL-03"],
    level: "M2",
    questionType: "mcq",
    prompt: "Tính từ chỉ mức độ tuyệt đối (VD: \"đỏ rực\", \"trắng tinh\") có đặc điểm gì?",
    explanation: "Tính từ chỉ mức độ tuyệt đối thường không kết hợp thêm được với các từ chỉ mức độ khác như \"rất\" (vì bản thân nó đã ở mức độ cao nhất).",
    mcq: {
      options: [
        "Không thể kết hợp thêm với từ mức độ như \"rất\" vì đã ở mức cao nhất",
        "Luôn phải kết hợp với \"rất\"",
        "Không phải là tính từ",
        "Chỉ dùng cho màu sắc",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — VD không nói \"rất đỏ rực\" vì \"đỏ rực\" đã diễn tả mức độ tuyệt đối.",
        "Ngược lại — tính từ mức độ tuyệt đối thường KHÔNG kết hợp với \"rất\".",
        "Đây vẫn là tính từ, chỉ khác ở việc diễn tả mức độ tuyệt đối.",
        "Tính từ mức độ tuyệt đối có thể dùng cho nhiều loại đặc điểm khác, không chỉ màu sắc (VD: im lặng như tờ).",
      ],
    },
  },
  {
    id: "tl-03-match-1",
    topicIds: ["TL-03"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi tính từ ở cột trái với đúng loại đặc điểm mà nó miêu tả ở cột phải.",
    explanation: "\"Xanh\" — màu sắc; \"ngọt\" — mùi vị; \"chăm chỉ\" — tính cách; \"cao\" — hình dáng.",
    match: {
      leftItems: [
        { id: "l1", label: "xanh" },
        { id: "l2", label: "ngọt" },
        { id: "l3", label: "chăm chỉ" },
        { id: "l4", label: "cao" },
      ],
      rightItems: [
        { id: "r1", label: "Tính cách" },
        { id: "r2", label: "Hình dáng" },
        { id: "r3", label: "Màu sắc" },
        { id: "r4", label: "Mùi vị" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r3" },
        { leftId: "l2", rightId: "r4" },
        { leftId: "l3", rightId: "r1" },
        { leftId: "l4", rightId: "r2" },
      ],
    },
  },
  {
    id: "tl-03-mcq-7",
    topicIds: ["TL-03"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Trong câu "Bạn ấy chạy nhanh như gió.", từ nào là tính từ?',
    explanation: "\"Nhanh\" là tính từ chỉ tốc độ, bổ sung ý nghĩa cho động từ \"chạy\".",
    mcq: {
      options: ["chạy", "nhanh", "gió", "như"],
      answerIndex: 1,
      distractorNotes: [
        "\"Chạy\" là động từ, không phải tính từ.",
        "Đúng — \"nhanh\" là tính từ, bổ sung ý nghĩa cho động từ \"chạy\".",
        "\"Gió\" là danh từ.",
        "\"Như\" là từ so sánh, không phải tính từ.",
      ],
    },
  },
  {
    id: "tl-03-mcq-8",
    topicIds: ["TL-03"],
    level: "M2",
    questionType: "mcq",
    prompt: "Câu nào dưới đây KHÔNG chứa tính từ?",
    explanation: "\"Em đi học.\" chỉ có chủ ngữ và động từ, không có tính từ nào.",
    mcq: {
      options: [
        "Bầu trời trong xanh.",
        "Em đi học.",
        "Bông hoa rất đẹp.",
        "Bạn ấy cao lớn.",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Câu này có tính từ \"trong xanh\".",
        "Đúng — câu này không có tính từ nào, chỉ có động từ \"đi học\".",
        "Câu này có tính từ \"đẹp\".",
        "Câu này có tính từ \"cao lớn\".",
      ],
    },
  },
  {
    id: "tl-03-mcq-9",
    topicIds: ["TL-03"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây là tính từ chỉ hình dáng?',
    explanation: "\"Tròn\" chỉ hình dáng, là tính từ.",
    mcq: {
      options: ["tròn", "chạy", "ăn", "học"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"tròn\" chỉ hình dáng, là tính từ.",
        "\"Chạy\" là động từ.",
        "\"Ăn\" là động từ.",
        "\"Học\" là động từ.",
      ],
    },
  },
];
