import type { Exercise } from "@/data-access/types";

// TL-06 — Xác định từ loại trong ngữ cảnh; hiện tượng chuyển loại của từ.
// `[BỔ SUNG]`. Ví dụ tự biên soạn (Mục 10.1 hướng B).
export const TL06_EXERCISES: Exercise[] = [
  {
    id: "tl-06-mcq-1",
    topicIds: ["TL-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Cuộc thi rất hấp dẫn.", từ "thi" thuộc từ loại nào?',
    explanation: "Ở đây \"thi\" đứng sau \"cuộc\" (danh từ chỉ đơn vị), tạo thành cụm danh từ \"cuộc thi\" — \"thi\" đóng vai trò danh từ.",
    mcq: {
      options: ["Danh từ", "Động từ", "Tính từ", "Đại từ"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — trong cụm \"cuộc thi\", \"thi\" đóng vai trò danh từ (sự kiện thi đấu).",
        "\"Thi\" chỉ là động từ khi đứng độc lập chỉ hành động (VD \"em thi đỗ\"), ở đây nó nằm trong cụm danh từ.",
        "\"Thi\" ở đây không chỉ đặc điểm, tính chất.",
        "\"Thi\" ở đây không dùng để xưng hô hay thay thế.",
      ],
    },
  },
  {
    id: "tl-06-mcq-2",
    topicIds: ["TL-06"],
    level: "M3",
    questionType: "mcq",
    prompt: 'So sánh từ "cuốc" trong hai câu: (1) "Cái cuốc này rất sắc." và (2) "Bác nông dân đang cuốc đất." Nhận xét nào ĐÚNG?',
    explanation: "Ở câu (1), \"cuốc\" là danh từ (chỉ dụng cụ). Ở câu (2), \"cuốc\" là động từ (chỉ hành động dùng cuốc). Đây là hiện tượng chuyển loại của từ.",
    mcq: {
      options: [
        "Cả hai câu \"cuốc\" đều là danh từ",
        "Cả hai câu \"cuốc\" đều là động từ",
        "Câu (1) \"cuốc\" là danh từ, câu (2) \"cuốc\" là động từ — đây là hiện tượng chuyển loại",
        "\"Cuốc\" trong hai câu không liên quan gì đến nhau",
      ],
      answerIndex: 2,
      distractorNotes: [
        "Câu (2) \"cuốc\" chỉ hành động, là động từ, không phải danh từ.",
        "Câu (1) \"cuốc\" chỉ sự vật (dụng cụ), là danh từ, không phải động từ.",
        "Đúng — cùng một từ nhưng khác từ loại tuỳ ngữ cảnh, đây chính là hiện tượng chuyển loại của từ.",
        "Hai từ này có liên quan (dụng cụ cuốc và hành động dùng cuốc để làm việc).",
      ],
    },
  },
  {
    id: "tl-06-fill-1",
    topicIds: ["TL-06"],
    level: "M2",
    questionType: "fill",
    prompt: "Điền từ còn thiếu: Để xác định từ loại của một từ có nhiều cách dùng, cần dựa vào ___ cụ thể của câu, không dựa vào từ đó một cách cô lập.",
    explanation: "Cần dựa vào ngữ cảnh cụ thể của câu để xác định từ loại chính xác.",
    fill: { acceptedAnswers: ["ngữ cảnh"], strictMode: false, isSet: false },
  },
  {
    id: "tl-06-mcq-3",
    topicIds: ["TL-06"],
    level: "M1",
    questionType: "mcq",
    prompt: "Hiện tượng chuyển loại của từ là gì?",
    explanation: "Hiện tượng chuyển loại là khi một từ có thể thuộc nhiều từ loại khác nhau tuỳ vào vị trí, chức năng của nó trong câu.",
    mcq: {
      options: [
        "Một từ có thể thuộc nhiều từ loại khác nhau tuỳ vị trí, chức năng trong câu",
        "Một từ chỉ có duy nhất một từ loại cố định",
        "Việc dịch một từ sang ngôn ngữ khác",
        "Việc thay đổi hoàn toàn nghĩa của từ",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là định nghĩa của hiện tượng chuyển loại.",
        "Đây là điều ngược lại với hiện tượng chuyển loại.",
        "Đây không liên quan đến chuyển loại từ, mà là dịch thuật.",
        "Chuyển loại chỉ thay đổi chức năng ngữ pháp, không nhất thiết thay đổi hoàn toàn nghĩa gốc.",
      ],
    },
  },
  {
    id: "tl-06-mcq-4",
    topicIds: ["TL-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Chiếc cày này rất bền." và "Bác nông dân đang cày ruộng.", từ "cày" thể hiện điều gì?',
    explanation: "\"Cày\" là danh từ (chỉ dụng cụ) trong câu đầu, và là động từ (chỉ hành động) trong câu sau — đây là hiện tượng chuyển loại.",
    mcq: {
      options: [
        "Từ đồng âm hoàn toàn không liên quan",
        "Hiện tượng chuyển loại (danh từ ở câu 1, động từ ở câu 2)",
        "Từ đồng nghĩa",
        "Từ trái nghĩa",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Hai nghĩa này có liên quan (dụng cụ và hành động dùng dụng cụ đó), không phải đồng âm hoàn toàn không liên quan.",
        "Đúng — đây là ví dụ về hiện tượng chuyển loại của từ.",
        "Hai từ không cùng nghĩa để coi là đồng nghĩa.",
        "Hai từ không đối lập nhau về nghĩa.",
      ],
    },
  },
  {
    id: "tl-06-fill-2",
    topicIds: ["TL-06"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền từ loại còn thiếu: Trong câu "Em rất yêu bố mẹ.", từ "yêu" thuộc từ loại ___.',
    explanation: "\"Yêu\" chỉ trạng thái tình cảm, là động từ.",
    fill: { acceptedAnswers: ["động từ"], strictMode: false, isSet: false },
  },
  {
    id: "tl-06-mcq-5",
    topicIds: ["TL-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Tình yêu thương của mẹ thật bao la.", từ "yêu thương" đóng vai trò từ loại nào?',
    explanation: "Ở đây \"yêu thương\" đi sau \"tình\" tạo thành cụm danh từ \"tình yêu thương\" — đóng vai trò danh từ (khác với khi \"yêu thương\" đứng độc lập làm động từ).",
    mcq: {
      options: ["Danh từ", "Động từ", "Tính từ", "Quan hệ từ"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — trong cụm \"tình yêu thương\", từ này đóng vai trò danh từ.",
        "\"Yêu thương\" chỉ là động từ khi đứng độc lập làm vị ngữ (VD: \"mẹ yêu thương em\").",
        "Đây không chỉ đặc điểm, tính chất trong ngữ cảnh này.",
        "Đây không phải quan hệ từ.",
      ],
    },
  },
  {
    id: "tl-06-mcq-6",
    topicIds: ["TL-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "sáng" trong hai câu: (1) "Trời đã sáng." và (2) "Cây bút này rất sáng bóng." được dùng như thế nào?',
    explanation: "\"Sáng\" ở câu (1) là động từ (chỉ trạng thái trời trở nên có ánh sáng), ở câu (2) là tính từ (chỉ đặc điểm của cây bút) — hiện tượng chuyển loại.",
    mcq: {
      options: [
        "Câu (1) là tính từ, câu (2) là động từ",
        "Câu (1) là động từ, câu (2) là tính từ",
        "Cả hai câu đều là danh từ",
        "Cả hai câu đều là quan hệ từ",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Ngược lại với thực tế — hãy xem lại từng câu.",
        "Đúng — câu (1) \"sáng\" là động từ (trạng thái), câu (2) \"sáng\" là tính từ (đặc điểm).",
        "Không câu nào dùng \"sáng\" như danh từ ở đây.",
        "\"Sáng\" không phải quan hệ từ trong cả hai câu.",
      ],
    },
  },
  {
    id: "tl-06-match-1",
    topicIds: ["TL-06"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi câu ở cột trái với đúng từ loại của từ được gạch dưới (\"cuốc\") ở cột phải.",
    explanation: "\"Cái cuốc này rất sắc.\" — cuốc là danh từ; \"Bác nông dân đang cuốc đất.\" — cuốc là động từ.",
    match: {
      leftItems: [
        { id: "l1", label: "Cái cuốc này rất sắc." },
        { id: "l2", label: "Bác nông dân đang cuốc đất." },
      ],
      rightItems: [
        { id: "r1", label: "Cuốc là động từ" },
        { id: "r2", label: "Cuốc là danh từ" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r1" },
      ],
    },
  },
  {
    id: "tl-06-mcq-7",
    topicIds: ["TL-06"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Vì sao không thể xác định từ loại của một từ chỉ bằng cách tra từ điển mà không xét câu cụ thể?',
    explanation: "Vì nhiều từ có hiện tượng chuyển loại — cùng một từ có thể đóng vai trò từ loại khác nhau tuỳ vào vị trí và chức năng trong từng câu cụ thể.",
    mcq: {
      options: [
        "Vì từ điển luôn sai",
        "Vì nhiều từ có hiện tượng chuyển loại, từ loại phụ thuộc vào ngữ cảnh câu cụ thể",
        "Vì từ điển không có nghĩa của từ",
        "Vì không cần thiết phải xác định từ loại",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Từ điển không sai, chỉ là không đủ để xác định từ loại trong MỌI ngữ cảnh cụ thể.",
        "Đúng — đây là lý do quan trọng nhất cần xét ngữ cảnh khi xác định từ loại.",
        "Từ điển vẫn cung cấp nghĩa của từ, chỉ là chưa đủ để xác định từ loại trong câu cụ thể.",
        "Việc xác định từ loại rất cần thiết để hiểu đúng và dùng đúng ngữ pháp.",
      ],
    },
  },
  {
    id: "tl-06-mcq-8",
    topicIds: ["TL-06"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Bức tranh có màu xanh rất đẹp." và "Quả xoài này còn xanh, chưa chín.", từ "xanh" khác nhau như thế nào?',
    explanation: "Cả hai đều là tính từ, nhưng nghĩa khác nhau: câu 1 chỉ màu sắc, câu 2 chỉ trạng thái chưa chín (nghĩa chuyển) — đây là ví dụ về từ nhiều nghĩa (NT-04), không phải chuyển loại từ loại.",
    mcq: {
      options: [
        "Khác nhau về từ loại (danh từ và động từ)",
        "Cùng là tính từ nhưng khác nghĩa (màu sắc và trạng thái chưa chín) — đây là từ nhiều nghĩa, không phải chuyển loại",
        "Không có gì khác nhau",
        "Khác nhau hoàn toàn, không liên quan gì đến nhau",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Cả hai từ \"xanh\" đều là tính từ, không đổi từ loại.",
        "Đúng — đây là ví dụ về từ nhiều nghĩa (cùng từ loại, khác nghĩa có liên hệ), khác với hiện tượng chuyển loại (đổi từ loại).",
        "Hai nghĩa của \"xanh\" ở đây khác nhau về sắc thái sử dụng.",
        "Hai nghĩa vẫn có liên hệ với nhau (đều liên quan đến giai đoạn phát triển tự nhiên).",
      ],
    },
  },
  {
    id: "tl-06-fill-3",
    topicIds: ["TL-06"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền từ loại còn thiếu: Trong câu "Chiếc lá vàng rơi.", từ "vàng" thuộc từ loại ___.',
    explanation: "\"Vàng\" chỉ màu sắc của chiếc lá, là tính từ.",
    fill: { acceptedAnswers: ["tính từ"], strictMode: false, isSet: false },
  },
];
