import type { Exercise } from "@/data-access/types";

// TL-05 — Quan hệ từ và cặp quan hệ từ. Ví dụ tự biên soạn (Mục 10.1 hướng B).
export const TL05_EXERCISES: Exercise[] = [
  {
    id: "tl-05-mcq-1",
    topicIds: ["TL-05"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Cặp quan hệ từ "vì...nên" thể hiện quan hệ ý nghĩa gì?',
    explanation: "Cặp \"vì...nên\" thể hiện quan hệ nguyên nhân – kết quả.",
    mcq: {
      options: ["Nguyên nhân – kết quả", "Tương phản", "Điều kiện – kết quả", "Tăng tiến"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — \"vì...nên\" thể hiện quan hệ nguyên nhân – kết quả.",
        "Quan hệ tương phản thường dùng cặp \"tuy...nhưng\".",
        "Quan hệ điều kiện – kết quả thường dùng cặp \"nếu...thì\".",
        "Đây không phải quan hệ tăng tiến.",
      ],
    },
  },
  {
    id: "tl-05-mcq-2",
    topicIds: ["TL-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Câu nào dùng ĐÚNG cặp quan hệ từ để thể hiện quan hệ tương phản?',
    explanation: "\"Tuy nhà nghèo nhưng bạn ấy học rất giỏi.\" dùng đúng cặp \"tuy...nhưng\" cho quan hệ tương phản.",
    mcq: {
      options: [
        "Vì nhà nghèo nên bạn ấy học rất giỏi.",
        "Tuy nhà nghèo nhưng bạn ấy học rất giỏi.",
        "Nếu nhà nghèo thì bạn ấy học rất giỏi.",
        "Nhà nghèo và bạn ấy học rất giỏi.",
      ],
      answerIndex: 1,
      distractorNotes: [
        "\"Vì...nên\" thể hiện quan hệ nguyên nhân – kết quả, không phù hợp ý tương phản (nghèo nhưng vẫn giỏi).",
        "Đúng — \"tuy...nhưng\" phù hợp thể hiện quan hệ tương phản.",
        "\"Nếu...thì\" thể hiện quan hệ điều kiện – kết quả, không phù hợp ở đây.",
        "\"Và\" chỉ là quan hệ từ đơn, không thể hiện rõ quan hệ tương phản như một cặp quan hệ từ.",
      ],
    },
  },
  {
    id: "tl-05-fill-1",
    topicIds: ["TL-05"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền quan hệ từ còn thiếu: "___ trời mưa to, em vẫn đến trường đúng giờ." (quan hệ tương phản, chỉ điền vế đầu)',
    explanation: "\"Tuy\" mở đầu cho vế tương phản, kết hợp với \"vẫn\" ở vế sau.",
    fill: { acceptedAnswers: ["Tuy", "tuy"], strictMode: false, isSet: false },
  },
  {
    id: "tl-05-mcq-3",
    topicIds: ["TL-05"],
    level: "M1",
    questionType: "mcq",
    prompt: "Quan hệ từ dùng để làm gì?",
    explanation: "Quan hệ từ dùng để nối các từ ngữ hoặc các vế câu, thể hiện quan hệ ý nghĩa giữa chúng.",
    mcq: {
      options: [
        "Nối các từ ngữ hoặc các vế câu, thể hiện quan hệ ý nghĩa giữa chúng",
        "Chỉ đặc điểm của sự vật",
        "Chỉ hoạt động của sự vật",
        "Thay thế cho danh từ đã nhắc trước đó",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là chức năng của quan hệ từ.",
        "Đây là chức năng của tính từ.",
        "Đây là chức năng của động từ.",
        "Đây là chức năng của đại từ thay thế (TL-04).",
      ],
    },
  },
  {
    id: "tl-05-mcq-4",
    topicIds: ["TL-05"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây là quan hệ từ?',
    explanation: "\"Và\" là quan hệ từ, dùng để nối các từ ngữ hoặc vế câu có quan hệ ngang hàng.",
    mcq: {
      options: ["chạy", "và", "đẹp", "nhanh"],
      answerIndex: 1,
      distractorNotes: [
        "\"Chạy\" là động từ.",
        "Đúng — \"và\" là quan hệ từ.",
        "\"Đẹp\" là tính từ.",
        "\"Nhanh\" là tính từ.",
      ],
    },
  },
  {
    id: "tl-05-fill-2",
    topicIds: ["TL-05"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền quan hệ từ còn thiếu: "___ em chăm chỉ học tập, em sẽ đạt kết quả tốt." (điền vế đầu, quan hệ giả thiết)',
    explanation: "\"Nếu\" mở đầu cho vế giả thiết, kết hợp với \"sẽ\" ở vế sau.",
    fill: { acceptedAnswers: ["Nếu", "nếu"], strictMode: false, isSet: false },
  },
  {
    id: "tl-05-mcq-5",
    topicIds: ["TL-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Cặp quan hệ từ nào phù hợp: "___ trời rét, ___ các bạn vẫn hăng hái tập thể dục."?',
    explanation: "Nội dung hai vế đối lập nhau (trời rét nhưng vẫn tập thể dục hăng hái) — phù hợp với cặp \"tuy...nhưng\".",
    mcq: {
      options: ["Vì...nên", "Tuy...nhưng", "Nếu...thì", "Không những...mà còn"],
      answerIndex: 1,
      distractorNotes: [
        "Hai vế mang ý đối lập, không phải nguyên nhân – kết quả thuận chiều.",
        "Đúng — \"tuy...nhưng\" phù hợp với ý đối lập.",
        "Đây không phải câu giả thiết.",
        "Đây không phải quan hệ tăng tiến.",
      ],
    },
  },
  {
    id: "tl-05-mcq-6",
    topicIds: ["TL-05"],
    level: "M2",
    questionType: "mcq",
    prompt: "Cặp quan hệ từ khác quan hệ từ đơn ở điểm nào?",
    explanation: "Cặp quan hệ từ gồm hai từ đi liền với nhau, mỗi từ đứng ở một vế của câu ghép; quan hệ từ đơn chỉ có một từ.",
    mcq: {
      options: [
        "Cặp quan hệ từ gồm hai từ, mỗi từ đứng ở một vế câu ghép",
        "Cặp quan hệ từ chỉ dùng trong câu đơn",
        "Cặp quan hệ từ không có ý nghĩa gì",
        "Không có sự khác biệt nào",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là đặc điểm của cặp quan hệ từ so với quan hệ từ đơn.",
        "Cặp quan hệ từ dùng trong câu ghép (có 2 vế), không phải câu đơn.",
        "Cặp quan hệ từ mang ý nghĩa quan hệ rõ ràng giữa hai vế.",
        "Hai loại có sự khác biệt rõ rệt về số lượng từ và cách dùng.",
      ],
    },
  },
  {
    id: "tl-05-match-1",
    topicIds: ["TL-05"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi cặp quan hệ từ ở cột trái với đúng quan hệ ý nghĩa ở cột phải.",
    explanation: "\"Vì...nên\" — nguyên nhân/kết quả; \"Tuy...nhưng\" — tương phản; \"Nếu...thì\" — giả thiết/kết quả; \"Không những...mà còn\" — tăng tiến.",
    match: {
      leftItems: [
        { id: "l1", label: "Vì...nên" },
        { id: "l2", label: "Tuy...nhưng" },
        { id: "l3", label: "Nếu...thì" },
        { id: "l4", label: "Không những...mà còn" },
      ],
      rightItems: [
        { id: "r1", label: "Tương phản" },
        { id: "r2", label: "Nguyên nhân – kết quả" },
        { id: "r3", label: "Tăng tiến" },
        { id: "r4", label: "Giả thiết – kết quả" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r1" },
        { leftId: "l3", rightId: "r4" },
        { leftId: "l4", rightId: "r3" },
      ],
    },
  },
  {
    id: "tl-05-mcq-7",
    topicIds: ["TL-05"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Câu "Vì trời mưa nhưng em vẫn đi học đúng giờ." mắc lỗi gì?',
    explanation: "Câu dùng lẫn hai cặp quan hệ từ khác nhau (\"vì\" của cặp nguyên nhân-kết quả và \"nhưng\" của cặp tương phản), gây sai ngữ pháp.",
    mcq: {
      options: [
        "Không mắc lỗi gì",
        "Dùng lẫn hai cặp quan hệ từ khác nhau, không đúng cặp",
        "Thiếu chủ ngữ",
        "Lặp từ không cần thiết",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Câu này mắc lỗi về việc dùng sai cặp quan hệ từ.",
        "Đúng — \"vì\" và \"nhưng\" thuộc hai cặp khác nhau, không thể dùng chung; nên sửa thành \"tuy...nhưng\" hoặc bỏ \"nhưng\".",
        "Câu có đủ chủ ngữ ở cả hai vế.",
        "Câu này không có từ nào bị lặp lại.",
      ],
    },
  },
  {
    id: "tl-05-mcq-8",
    topicIds: ["TL-05"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây có thể dùng thay cho quan hệ từ "và" trong câu "Em thích đọc sách và xem phim."?',
    explanation: "\"Cùng với\" cũng thể hiện quan hệ ngang hàng, có thể thay thế \"và\" trong câu này.",
    mcq: {
      options: ["nhưng", "cùng với", "vì", "nên"],
      answerIndex: 1,
      distractorNotes: [
        "\"Nhưng\" thể hiện quan hệ tương phản, không phù hợp thay cho \"và\".",
        "Đúng — \"cùng với\" cũng thể hiện quan hệ ngang hàng, phù hợp thay thế \"và\".",
        "\"Vì\" thể hiện quan hệ nguyên nhân, không phù hợp.",
        "\"Nên\" thể hiện quan hệ kết quả, không phù hợp.",
      ],
    },
  },
  {
    id: "tl-05-mcq-9",
    topicIds: ["TL-05"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây KHÔNG phải là quan hệ từ?',
    explanation: "\"Chạy\" là động từ, không phải quan hệ từ.",
    mcq: {
      options: ["và", "nhưng", "chạy", "của"],
      answerIndex: 2,
      distractorNotes: [
        "\"Và\" là quan hệ từ.",
        "\"Nhưng\" là quan hệ từ.",
        "Đúng — \"chạy\" là động từ, không phải quan hệ từ.",
        "\"Của\" là quan hệ từ.",
      ],
    },
  },
];
