import type { Exercise } from "@/data-access/types";

// TL-02 — Động từ và các loại động từ. Ví dụ tự biên soạn (Mục 10.1 hướng B).
export const TL02_EXERCISES: Exercise[] = [
  {
    id: "tl-02-mcq-1",
    topicIds: ["TL-02"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Trong câu "Em đang học bài.", từ nào là động từ?',
    explanation: "\"Học\" chỉ hoạt động của em — là động từ.",
    mcq: {
      options: ["Em", "đang", "học", "bài"],
      answerIndex: 2,
      distractorNotes: [
        "\"Em\" là đại từ nhân xưng, không phải động từ.",
        "\"Đang\" là từ chỉ thời gian đi kèm động từ, không phải bản thân động từ.",
        "Đúng — \"học\" chỉ hoạt động, là động từ.",
        "\"Bài\" là danh từ, không phải động từ.",
      ],
    },
  },
  {
    id: "tl-02-mcq-2",
    topicIds: ["TL-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "yêu" trong câu "Em rất yêu mẹ." thuộc loại động từ nào?',
    explanation: "\"Yêu\" chỉ trạng thái tình cảm, không phải hoạt động cụ thể — là động từ chỉ trạng thái.",
    mcq: {
      options: ["Động từ chỉ hoạt động", "Động từ chỉ trạng thái", "Không phải động từ", "Danh từ"],
      answerIndex: 1,
      distractorNotes: [
        "\"Yêu\" không chỉ một hành động cụ thể như chạy, nhảy — đây là trạng thái tình cảm.",
        "Đúng — \"yêu\" chỉ trạng thái (tình cảm), là động từ chỉ trạng thái.",
        "\"Yêu\" vẫn là động từ.",
        "\"Yêu\" chỉ trạng thái, không phải danh từ.",
      ],
    },
  },
  {
    id: "tl-02-fill-1",
    topicIds: ["TL-02"],
    level: "M2",
    questionType: "fill",
    prompt: "Điền từ còn thiếu: Động từ là từ chỉ hoạt động hoặc ___ của sự vật.",
    explanation: "Động từ chỉ hoạt động hoặc trạng thái của sự vật.",
    fill: { acceptedAnswers: ["trạng thái"], strictMode: false, isSet: false },
  },
  {
    id: "tl-02-mcq-3",
    topicIds: ["TL-02"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây là động từ chỉ hoạt động?',
    explanation: "\"Chạy\" chỉ một hành động cụ thể của cơ thể — là động từ chỉ hoạt động.",
    mcq: {
      options: ["đẹp", "chạy", "vui vẻ", "cao"],
      answerIndex: 1,
      distractorNotes: [
        "\"Đẹp\" là tính từ, chỉ đặc điểm.",
        "Đúng — \"chạy\" chỉ hành động cụ thể, là động từ chỉ hoạt động.",
        "\"Vui vẻ\" là tính từ, chỉ trạng thái tâm lý (dùng làm vị ngữ mô tả đặc điểm).",
        "\"Cao\" là tính từ, chỉ đặc điểm.",
      ],
    },
  },
  {
    id: "tl-02-mcq-4",
    topicIds: ["TL-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ "biết" trong câu "Em biết bơi." thuộc loại động từ nào?',
    explanation: "\"Biết\" chỉ khả năng/trạng thái nhận thức, không phải hành động cụ thể — là động từ chỉ trạng thái.",
    mcq: {
      options: ["Động từ chỉ hoạt động", "Động từ chỉ trạng thái", "Tính từ", "Danh từ"],
      answerIndex: 1,
      distractorNotes: [
        "\"Biết\" không phải một hành động cơ thể cụ thể.",
        "Đúng — \"biết\" chỉ trạng thái nhận thức, là động từ chỉ trạng thái.",
        "\"Biết\" là động từ, không phải tính từ.",
        "\"Biết\" là động từ, không phải danh từ.",
      ],
    },
  },
  {
    id: "tl-02-fill-2",
    topicIds: ["TL-02"],
    level: "M1",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Động từ thường có thể kết hợp với các từ "đã", "đang", "___" để chỉ thời gian.',
    explanation: "Động từ thường kết hợp với \"đã\", \"đang\", \"sẽ\" để chỉ thời gian (quá khứ, hiện tại, tương lai).",
    fill: { acceptedAnswers: ["sẽ"], strictMode: false, isSet: false },
  },
  {
    id: "tl-02-mcq-5",
    topicIds: ["TL-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Bạn Nam đang vẽ một bức tranh đẹp.", có mấy động từ?',
    explanation: "Câu chỉ có 1 động từ: \"vẽ\" (hành động). \"Đẹp\" là tính từ, không phải động từ.",
    mcq: {
      options: ["1", "2", "3", "0"],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — chỉ có \"vẽ\" là động từ trong câu này.",
        "Câu chỉ có 1 động từ, không phải 2.",
        "Câu chỉ có 1 động từ, không phải 3.",
        "Câu có 1 động từ là \"vẽ\".",
      ],
    },
  },
  {
    id: "tl-02-match-1",
    topicIds: ["TL-02"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi từ ở cột trái với đúng loại (động từ chỉ hoạt động/trạng thái) ở cột phải.",
    explanation: "\"Chạy\", \"nhảy\" là động từ chỉ hoạt động; \"yêu\", \"biết\" là động từ chỉ trạng thái.",
    match: {
      leftItems: [
        { id: "l1", label: "chạy" },
        { id: "l2", label: "yêu" },
        { id: "l3", label: "nhảy" },
        { id: "l4", label: "biết" },
      ],
      rightItems: [
        { id: "r1", label: "Động từ chỉ hoạt động" },
        { id: "r2", label: "Động từ chỉ trạng thái" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r1" },
        { leftId: "l2", rightId: "r2" },
        { leftId: "l3", rightId: "r1" },
        { leftId: "l4", rightId: "r2" },
      ],
    },
  },
  {
    id: "tl-02-mcq-6",
    topicIds: ["TL-02"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Từ "cuốc" trong câu "Bác nông dân đang cuốc đất." là từ loại gì?',
    explanation: "Ở đây \"cuốc\" chỉ hành động dùng dụng cụ để làm đất — là động từ (liên hệ hiện tượng chuyển loại ở TL-06).",
    mcq: {
      options: ["Danh từ", "Động từ", "Tính từ", "Đại từ"],
      answerIndex: 1,
      distractorNotes: [
        "\"Cuốc\" chỉ là danh từ khi đứng riêng chỉ dụng cụ (VD: cái cuốc), ở đây nó chỉ hành động.",
        "Đúng — trong câu này, \"cuốc\" chỉ hành động, là động từ.",
        "\"Cuốc\" ở đây không chỉ đặc điểm, tính chất.",
        "\"Cuốc\" ở đây không dùng để xưng hô hay thay thế.",
      ],
    },
  },
  {
    id: "tl-02-mcq-7",
    topicIds: ["TL-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây là động từ chỉ trạng thái?',
    explanation: "\"Tồn tại\" chỉ trạng thái, không phải hành động cụ thể.",
    mcq: {
      options: ["nhảy", "hát", "tồn tại", "đi"],
      answerIndex: 2,
      distractorNotes: [
        "\"Nhảy\" là động từ chỉ hoạt động.",
        "\"Hát\" là động từ chỉ hoạt động.",
        "Đúng — \"tồn tại\" chỉ trạng thái, không phải hành động cụ thể.",
        "\"Đi\" là động từ chỉ hoạt động.",
      ],
    },
  },
  {
    id: "tl-02-mcq-8",
    topicIds: ["TL-02"],
    level: "M2",
    questionType: "mcq",
    prompt: "Động từ thường giữ vai trò gì trong câu?",
    explanation: "Động từ thường làm vị ngữ hoặc một phần của vị ngữ trong câu, nêu hoạt động/trạng thái của chủ ngữ.",
    mcq: {
      options: ["Chủ ngữ", "Vị ngữ (hoặc một phần vị ngữ)", "Trạng ngữ", "Không có vai trò ngữ pháp nào"],
      answerIndex: 1,
      distractorNotes: [
        "Chủ ngữ thường do danh từ/đại từ đảm nhiệm, không phải động từ.",
        "Đúng — động từ thường làm vị ngữ, nêu hoạt động/trạng thái của chủ ngữ.",
        "Trạng ngữ thường không phải động từ.",
        "Động từ có vai trò ngữ pháp quan trọng trong câu.",
      ],
    },
  },
  {
    id: "tl-02-mcq-9",
    topicIds: ["TL-02"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Đàn kiến đang tha thức ăn về tổ.", động từ trong câu là gì?',
    explanation: "\"Tha\" chỉ hành động, là động từ chính trong câu.",
    mcq: {
      options: ["Đàn kiến", "tha", "thức ăn", "tổ"],
      answerIndex: 1,
      distractorNotes: [
        "\"Đàn kiến\" là danh từ, làm chủ ngữ.",
        "Đúng — \"tha\" chỉ hành động, là động từ.",
        "\"Thức ăn\" là danh từ.",
        "\"Tổ\" là danh từ.",
      ],
    },
  },
];
