import type { Exercise } from "@/data-access/types";

// TL-04 — Đại từ (nhân xưng, đại từ thay thế). Ví dụ tự biên soạn (Mục
// 10.1 hướng B).
export const TL04_EXERCISES: Exercise[] = [
  {
    id: "tl-04-mcq-1",
    topicIds: ["TL-04"],
    level: "M1",
    questionType: "mcq",
    prompt: 'Trong câu "Tôi và bạn cùng đi học.", từ nào là đại từ nhân xưng?',
    explanation: "\"Tôi\" và \"bạn\" dùng để xưng hô giữa người nói và người nghe — là đại từ nhân xưng.",
    mcq: {
      options: ["đi, học", "Tôi, bạn", "và", "cùng"],
      answerIndex: 1,
      distractorNotes: [
        "\"Đi\", \"học\" là động từ, không phải đại từ.",
        "Đúng — \"tôi\", \"bạn\" là đại từ nhân xưng, dùng để xưng hô.",
        "\"Và\" là quan hệ từ, không phải đại từ.",
        "\"Cùng\" là từ chỉ mức độ/cách thức, không phải đại từ.",
      ],
    },
  },
  {
    id: "tl-04-mcq-2",
    topicIds: ["TL-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Lan rất chăm học. Điều đó khiến cô giáo rất vui.", từ "đó" thay thế cho điều gì?',
    explanation: "\"Đó\" là đại từ thay thế, thay cho ý \"Lan rất chăm học\" đã nói ở câu trước, tránh lặp lại cả câu.",
    mcq: {
      options: ["Thay cho \"cô giáo\"", "Thay cho ý \"Lan rất chăm học\"", "Thay cho \"Lan\"", "Không thay thế cho gì cả"],
      answerIndex: 1,
      distractorNotes: [
        "\"Cô giáo\" xuất hiện sau từ \"đó\", không phải điều \"đó\" thay thế.",
        "Đúng — \"đó\" thay thế cho cả ý \"Lan rất chăm học\" ở câu trước, tránh lặp lại.",
        "\"Đó\" thay thế cho cả một ý, không chỉ riêng tên \"Lan\".",
        "\"Đó\" là đại từ thay thế, có chức năng thay thế rõ ràng trong câu này.",
      ],
    },
  },
  {
    id: "tl-04-mcq-3",
    topicIds: ["TL-04"],
    level: "M1",
    questionType: "mcq",
    prompt: "Đại từ nhân xưng dùng để làm gì?",
    explanation: "Đại từ nhân xưng dùng để xưng hô giữa người nói, người nghe và người/vật được nhắc đến.",
    mcq: {
      options: [
        "Để xưng hô giữa người nói, người nghe và người/vật được nhắc đến",
        "Để chỉ đặc điểm của sự vật",
        "Để nối các vế câu",
        "Để chỉ hoạt động",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là chức năng của đại từ nhân xưng.",
        "Đây là chức năng của tính từ.",
        "Đây là chức năng của quan hệ từ.",
        "Đây là chức năng của động từ.",
      ],
    },
  },
  {
    id: "tl-04-mcq-4",
    topicIds: ["TL-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây là đại từ nhân xưng ngôi thứ ba?',
    explanation: "\"Họ\" dùng để chỉ những người được nói đến (không phải người nói hay người nghe trực tiếp) — là đại từ nhân xưng ngôi thứ ba.",
    mcq: {
      options: ["tôi", "bạn", "họ", "chúng ta"],
      answerIndex: 2,
      distractorNotes: [
        "\"Tôi\" là ngôi thứ nhất (người nói).",
        "\"Bạn\" là ngôi thứ hai (người nghe).",
        "Đúng — \"họ\" là ngôi thứ ba, chỉ người được nói đến.",
        "\"Chúng ta\" là ngôi thứ nhất số nhiều (bao gồm người nói).",
      ],
    },
  },
  {
    id: "tl-04-fill-1",
    topicIds: ["TL-04"],
    level: "M1",
    questionType: "fill",
    prompt: "Điền từ còn thiếu: Đại từ dùng để thay thế cho danh từ, động từ, tính từ hoặc cụm từ đã nói trước đó được gọi là đại từ ___.",
    explanation: "Đại từ thay thế dùng để thay cho từ ngữ đã nhắc trước đó, tránh lặp từ.",
    fill: { acceptedAnswers: ["thay thế"], strictMode: false, isSet: false },
  },
  {
    id: "tl-04-mcq-5",
    topicIds: ["TL-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Bà kể chuyện cổ tích. Em rất thích nghe vậy.", từ "vậy" thay thế cho điều gì?',
    explanation: "\"Vậy\" thay thế cho ý \"bà kể chuyện cổ tích\" ở câu trước.",
    mcq: {
      options: ["Thay cho \"bà\"", "Thay cho ý \"bà kể chuyện cổ tích\"", "Thay cho \"em\"", "Không thay thế cho gì"],
      answerIndex: 1,
      distractorNotes: [
        "\"Bà\" xuất hiện trước, không phải điều \"vậy\" thay thế riêng lẻ.",
        "Đúng — \"vậy\" thay thế cho cả ý \"bà kể chuyện cổ tích\".",
        "\"Vậy\" không thay thế cho \"em\".",
        "\"Vậy\" có chức năng thay thế rõ ràng trong câu này.",
      ],
    },
  },
  {
    id: "tl-04-mcq-6",
    topicIds: ["TL-04"],
    level: "M2",
    questionType: "mcq",
    prompt: "Vì sao cần dùng đại từ thay thế thay vì lặp lại từ ngữ đã nói?",
    explanation: "Dùng đại từ thay thế giúp câu văn gọn gàng hơn, tránh lặp từ nhàm chán, đồng thời vẫn tạo được sự liên kết giữa các câu (liên hệ CA-07).",
    mcq: {
      options: [
        "Để câu văn dài hơn",
        "Để tránh lặp từ nhàm chán và tạo sự liên kết giữa các câu",
        "Không có lý do gì đặc biệt",
        "Để câu văn khó hiểu hơn",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Đây không phải mục đích chính của việc dùng đại từ thay thế.",
        "Đúng — đây là lý do quan trọng để dùng đại từ thay thế.",
        "Đây là một kỹ năng quan trọng, có lý do rõ ràng.",
        "Mục đích ngược lại — giúp câu văn rõ ràng, gọn gàng hơn.",
      ],
    },
  },
  {
    id: "tl-04-match-1",
    topicIds: ["TL-04"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi từ ở cột trái với đúng loại đại từ ở cột phải.",
    explanation: "\"Tôi\", \"chúng ta\" là đại từ nhân xưng; \"đó\", \"vậy\" là đại từ thay thế.",
    match: {
      leftItems: [
        { id: "l1", label: "Tôi" },
        { id: "l2", label: "đó" },
        { id: "l3", label: "chúng ta" },
        { id: "l4", label: "vậy" },
      ],
      rightItems: [
        { id: "r1", label: "Đại từ nhân xưng" },
        { id: "r2", label: "Đại từ thay thế" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r1" },
        { leftId: "l2", rightId: "r2" },
        { leftId: "l3", rightId: "r1" },
        { leftId: "l4", rightId: "r2" },
      ],
    },
  },
  {
    id: "tl-04-mcq-7",
    topicIds: ["TL-04"],
    level: "M2",
    questionType: "mcq",
    prompt: "Câu nào dưới đây dùng đại từ nhân xưng?",
    explanation: "\"Chúng tôi\" là đại từ nhân xưng ngôi thứ nhất số nhiều.",
    mcq: {
      options: [
        "Bông hoa này rất đẹp.",
        "Chúng tôi cùng nhau học bài.",
        "Trời hôm nay nắng to.",
        "Con mèo đang ngủ.",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Câu này không có đại từ nhân xưng.",
        "Đúng — \"chúng tôi\" là đại từ nhân xưng.",
        "Câu này không có đại từ nhân xưng.",
        "Câu này không có đại từ nhân xưng.",
      ],
    },
  },
  {
    id: "tl-04-mcq-8",
    topicIds: ["TL-04"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Trong câu "Cả lớp đều yêu quý cô giáo vì cô luôn tận tâm với học sinh.", từ "cô" thứ hai đóng vai trò gì?',
    explanation: "\"Cô\" thứ hai thay thế cho \"cô giáo\" đã nhắc ở đầu câu, tránh lặp lại — đóng vai trò đại từ thay thế.",
    mcq: {
      options: [
        "Danh từ chỉ nghề nghiệp",
        "Đại từ thay thế cho \"cô giáo\"",
        "Động từ",
        "Tính từ",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Ở đây \"cô\" không dùng như danh từ chỉ nghề nghiệp độc lập, mà thay thế cho \"cô giáo\" đã nhắc.",
        "Đúng — \"cô\" ở đây đóng vai trò đại từ thay thế cho \"cô giáo\".",
        "\"Cô\" ở đây không chỉ hoạt động.",
        "\"Cô\" ở đây không chỉ đặc điểm.",
      ],
    },
  },
  {
    id: "tl-04-mcq-9",
    topicIds: ["TL-04"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây thường dùng làm đại từ xưng hô thân mật giữa bạn bè cùng lứa tuổi?',
    explanation: "\"Tớ\" và \"cậu\" thường dùng giữa bạn bè thân thiết, cùng lứa tuổi.",
    mcq: {
      options: ["Ngài", "Tớ", "Quý vị", "Thưa ông"],
      answerIndex: 1,
      distractorNotes: [
        "\"Ngài\" dùng trong hoàn cảnh trang trọng, không phải giữa bạn bè.",
        "Đúng — \"tớ\" thường dùng thân mật giữa bạn bè cùng lứa tuổi.",
        "\"Quý vị\" dùng trong hoàn cảnh trang trọng.",
        "\"Thưa ông\" dùng trong hoàn cảnh trang trọng, lễ phép với người lớn tuổi.",
      ],
    },
  },
  {
    id: "tl-04-fill-2",
    topicIds: ["TL-04"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: "Chúng tôi", "các bạn", "họ" là các đại từ ___.',
    explanation: "Đây đều là các đại từ nhân xưng.",
    fill: { acceptedAnswers: ["nhân xưng"], strictMode: false, isSet: false },
  },
];
