import type { Exercise } from "@/data-access/types";

// TL-01 — Danh từ và các loại danh từ. Ví dụ tự biên soạn (Mục 10.1 hướng B).
export const TL01_EXERCISES: Exercise[] = [
  {
    id: "tl-01-mcq-1",
    topicIds: ["TL-01"],
    level: "M1",
    questionType: "mcq",
    prompt: "Danh từ là gì?",
    explanation: "Danh từ là từ chỉ người, sự vật, hiện tượng, khái niệm.",
    mcq: {
      options: [
        "Từ chỉ người, sự vật, hiện tượng, khái niệm",
        "Từ chỉ hoạt động, trạng thái",
        "Từ chỉ đặc điểm, tính chất",
        "Từ dùng để nối các vế câu",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là định nghĩa của danh từ.",
        "Đây là định nghĩa của động từ (TL-02).",
        "Đây là định nghĩa của tính từ (TL-03).",
        "Đây là định nghĩa của quan hệ từ (TL-05).",
      ],
    },
  },
  {
    id: "tl-01-mcq-2",
    topicIds: ["TL-01"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Hà Nội là thủ đô của Việt Nam.", từ nào là danh từ riêng?',
    explanation: "\"Hà Nội\" và \"Việt Nam\" là tên riêng của địa danh, phải viết hoa — là danh từ riêng.",
    mcq: {
      options: ["là", "thủ đô", "Hà Nội, Việt Nam", "của"],
      answerIndex: 2,
      distractorNotes: [
        "\"Là\" là động từ, không phải danh từ.",
        "\"Thủ đô\" là danh từ chung, chỉ loại sự vật nói chung, không phải tên riêng.",
        "Đúng — \"Hà Nội\", \"Việt Nam\" là tên riêng của địa danh, viết hoa, là danh từ riêng.",
        "\"Của\" là quan hệ từ, không phải danh từ.",
      ],
    },
  },
  {
    id: "tl-01-mcq-3",
    topicIds: ["TL-01"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây là danh từ chỉ khái niệm (trừu tượng)?',
    explanation: "\"Niềm vui\" là danh từ chỉ khái niệm, không sờ thấy được nhưng vẫn là danh từ.",
    mcq: {
      options: ["Cái bàn", "Niềm vui", "Con mèo", "Quyển sách"],
      answerIndex: 1,
      distractorNotes: [
        "\"Cái bàn\" là danh từ chỉ sự vật cụ thể, sờ thấy được.",
        "Đúng — \"niềm vui\" là danh từ chỉ khái niệm, trừu tượng.",
        "\"Con mèo\" là danh từ chỉ sự vật cụ thể.",
        "\"Quyển sách\" là danh từ chỉ sự vật cụ thể.",
      ],
    },
  },
  {
    id: "tl-01-mcq-4",
    topicIds: ["TL-01"],
    level: "M1",
    questionType: "mcq",
    prompt: "Danh từ chung khác danh từ riêng ở điểm nào?",
    explanation: "Danh từ chung chỉ tên gọi chung của một loại sự vật, còn danh từ riêng chỉ tên riêng của một sự vật cụ thể và phải viết hoa.",
    mcq: {
      options: [
        "Danh từ chung chỉ tên gọi chung của một loại sự vật; danh từ riêng chỉ tên riêng, viết hoa",
        "Danh từ chung luôn dài hơn danh từ riêng",
        "Danh từ riêng chỉ dùng cho đồ vật",
        "Không có sự khác biệt nào",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là điểm khác biệt cơ bản giữa danh từ chung và danh từ riêng.",
        "Độ dài không phải là tiêu chí phân biệt.",
        "Danh từ riêng chủ yếu dùng cho tên người, địa danh, tổ chức, không giới hạn ở đồ vật.",
        "Hai loại danh từ có sự khác biệt rõ rệt về cách viết và ý nghĩa.",
      ],
    },
  },
  {
    id: "tl-01-mcq-5",
    topicIds: ["TL-01"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Trong câu "Tình bạn là điều quý giá.", từ nào là danh từ?',
    explanation: "\"Tình bạn\" và \"điều\" đều là danh từ (tình bạn chỉ khái niệm, điều chỉ sự việc trừu tượng).",
    mcq: {
      options: ["là, quý", "Tình bạn, điều", "giá", "là"],
      answerIndex: 1,
      distractorNotes: [
        "\"Là\" là động từ, \"quý\" là tính từ, cả hai đều không phải danh từ.",
        "Đúng — \"tình bạn\" và \"điều\" đều là danh từ chỉ khái niệm.",
        "\"Giá\" ở đây chỉ là một phần của từ \"quý giá\", không đứng riêng làm danh từ trong câu này.",
        "\"Là\" là động từ, không phải danh từ.",
      ],
    },
  },
  {
    id: "tl-01-fill-1",
    topicIds: ["TL-01"],
    level: "M2",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: Tên người, tên địa danh là danh từ ___, phải viết hoa.',
    explanation: "Tên người, tên địa danh thuộc loại danh từ riêng, luôn phải viết hoa.",
    fill: { acceptedAnswers: ["riêng"], strictMode: false, isSet: false },
  },
  {
    id: "tl-01-mcq-6",
    topicIds: ["TL-01"],
    level: "M2",
    questionType: "mcq",
    prompt: "Danh từ chỉ đơn vị dùng để làm gì?",
    explanation: "Danh từ chỉ đơn vị (con, cái, chiếc, quyển...) dùng để đếm hoặc phân loại sự vật đi kèm phía sau.",
    mcq: {
      options: [
        "Đếm hoặc phân loại sự vật đi kèm phía sau",
        "Chỉ hoạt động của sự vật",
        "Chỉ đặc điểm của sự vật",
        "Nối các câu với nhau",
      ],
      answerIndex: 0,
      distractorNotes: [
        "Đúng — đây là chức năng của danh từ chỉ đơn vị (VD: một CON mèo, hai CÁI bàn).",
        "Đây là chức năng của động từ.",
        "Đây là chức năng của tính từ.",
        "Đây là chức năng của quan hệ từ.",
      ],
    },
  },
  {
    id: "tl-01-match-1",
    topicIds: ["TL-01"],
    level: "M2",
    questionType: "match",
    prompt: "Nối mỗi từ ở cột trái với đúng loại danh từ ở cột phải.",
    explanation: "\"Hà Nội\" — danh từ riêng; \"cái bàn\" — danh từ chung (chỉ sự vật); \"niềm vui\" — danh từ chung (chỉ khái niệm).",
    match: {
      leftItems: [
        { id: "l1", label: "Hà Nội" },
        { id: "l2", label: "cái bàn" },
        { id: "l3", label: "niềm vui" },
      ],
      rightItems: [
        { id: "r1", label: "Danh từ chung (khái niệm)" },
        { id: "r2", label: "Danh từ riêng" },
        { id: "r3", label: "Danh từ chung (sự vật)" },
      ],
      correctPairs: [
        { leftId: "l1", rightId: "r2" },
        { leftId: "l2", rightId: "r3" },
        { leftId: "l3", rightId: "r1" },
      ],
    },
  },
  {
    id: "tl-01-mcq-7",
    topicIds: ["TL-01"],
    level: "M2",
    questionType: "mcq",
    prompt: 'Từ nào dưới đây KHÔNG phải là danh từ?',
    explanation: "\"Chạy\" chỉ hoạt động, là động từ, không phải danh từ.",
    mcq: {
      options: ["học sinh", "trường học", "chạy", "cây bút"],
      answerIndex: 2,
      distractorNotes: [
        "\"Học sinh\" là danh từ chỉ người.",
        "\"Trường học\" là danh từ chỉ nơi chốn.",
        "Đúng — \"chạy\" chỉ hoạt động, là động từ.",
        "\"Cây bút\" là danh từ chỉ đồ vật.",
      ],
    },
  },
  {
    id: "tl-01-mcq-8",
    topicIds: ["TL-01"],
    level: "M3",
    questionType: "mcq",
    prompt: 'Trong câu "Sự cố gắng của em đã được đền đáp.", từ nào là danh từ chỉ khái niệm?',
    explanation: "\"Sự cố gắng\" là danh từ trừu tượng, được tạo thành bằng cách thêm \"sự\" trước động từ \"cố gắng\" để biến thành danh từ.",
    mcq: {
      options: ["của", "Sự cố gắng", "đã", "được"],
      answerIndex: 1,
      distractorNotes: [
        "\"Của\" là quan hệ từ, không phải danh từ.",
        "Đúng — \"sự cố gắng\" là danh từ chỉ khái niệm trừu tượng.",
        "\"Đã\" là từ chỉ thời gian, không phải danh từ.",
        "\"Được\" không phải danh từ trong câu này.",
      ],
    },
  },
  {
    id: "tl-01-mcq-9",
    topicIds: ["TL-01"],
    level: "M2",
    questionType: "mcq",
    prompt: "Câu nào dưới đây có chứa danh từ riêng?",
    explanation: "\"Việt Nam\" là danh từ riêng chỉ tên quốc gia.",
    mcq: {
      options: [
        "Em rất yêu quê hương.",
        "Việt Nam là quê hương của em.",
        "Con sông chảy hiền hoà.",
        "Cây cối xanh tươi vào mùa xuân.",
      ],
      answerIndex: 1,
      distractorNotes: [
        "Câu này chỉ có danh từ chung.",
        "Đúng — \"Việt Nam\" là danh từ riêng (tên quốc gia).",
        "Câu này chỉ có danh từ chung.",
        "Câu này chỉ có danh từ chung.",
      ],
    },
  },
  {
    id: "tl-01-fill-2",
    topicIds: ["TL-01"],
    level: "M1",
    questionType: "fill",
    prompt: 'Điền từ còn thiếu: "Cái ghế", "con mèo" là các danh từ ___ (chỉ loại sự vật nói chung, không viết hoa).',
    explanation: "Đây là các danh từ chung, chỉ loại sự vật nói chung, không viết hoa.",
    fill: { acceptedAnswers: ["chung"], strictMode: false, isSet: false },
  },
];
